import {_electron as electron} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const dir='projects/activity-test',env={...process.env,MSXLAB_USER_DATA:'/tmp/msxlab-activity-'+Date.now()};delete env.ELECTRON_RUN_AS_NODE;
await fs.cp('projects/kings-valley',dir,{recursive:true});const p=JSON.parse(await fs.readFile(dir+'/project.json','utf8'));p.id='activity-test';p.name='Activity test';p.breakpoints=[];await fs.writeFile(dir+'/project.json',JSON.stringify(p));let app;
try{
 app=await electron.launch({args:['.'],env});const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.panel-disassembler tbody tr',{timeout:20000});
 const info=JSON.parse(await fs.readFile('.msxlab-runtime.json','utf8'));const api=async(command,args={})=>{const response=await fetch(info.url,{method:'POST',headers:{Authorization:'Bearer '+info.token,'Content-Type':'application/json'},body:JSON.stringify({command,args})});const r=await response.json();assert(!r.error,r.error);return r.result;};
 await api('loadProject',{id:'activity-test'});await page.waitForTimeout(4000);await api('pause');await page.waitForFunction(()=>document.querySelector('.backend-badge').textContent==='PAUSED');
 const frame=page.frames().find(f=>f.url().includes('/engine/index.html'));
 async function request(command,args){return page.evaluate(({command,args})=>new Promise((resolve,reject)=>{const f=document.querySelector('iframe[title="MSX emulator"]'),id=Math.floor(Math.random()*1e9)+1e9;const handler=e=>{if(e.source===f.contentWindow&&e.data.id===id&&e.data.type==='reply'){window.removeEventListener('message',handler);e.data.error?reject(Error(e.data.error)):resolve(e.data.result);}};window.addEventListener('message',handler);f.contentWindow.postMessage({source:'msxlab-ui',id,command,args},location.origin);}),{command,args});}

 // One loop exercises CPU and buffered VRAM reads/writes; stop before repeating it.
 const program=[0x3a,0x00,0xe1,0x32,0x00,0xe1,0x3e,0x34,0xd3,0x99,0x3e,0x52,0xd3,0x99,0x3e,0xaa,0xd3,0x98,0x3e,0x34,0xd3,0x99,0x3e,0x12,0xd3,0x99,0xdb,0x98,0xc3,0x00,0xc0];
 await frame.evaluate(program=>{const m=WMSX.room.machine,b=m.eval('bus'),c=m.eval('cpu');program.forEach((v,i)=>b.write(0xc000+i,v));b.write(0xe100,7);const r=c.saveState();Object.assign(r,{PC:0xc000,SP:0xf000,Tn:0,p:0,ai:false,IFF1:0,INT:255});c.loadState(r);},program);
 await request('resetActivity');await request('activity',true);await request('breakpoints',[{address:0xc000,enabled:true}]);await request('run');await page.waitForTimeout(250);let snap=await request('snapshot');assert.equal(snap.status,'paused');assert.equal(snap.activity.execute[0xc000],1);assert.equal(snap.activity.read[0xe100],1);assert.equal(snap.activity.write[0xe100],1);assert.equal(snap.activity.vramWrite[0x1234],1);assert.equal(snap.activity.vramRead[0x1234],1);assert.equal(snap.registers.A,0xaa);const before=snap.activity;assert.deepEqual((await request('snapshot')).activity,before,'Debugger inspection must not pollute counters');
 await request('activity',false);await request('run');await page.waitForTimeout(200);assert.deepEqual((await request('snapshot')).activity,{...before,enabled:false});await request('resetActivity');assert.deepEqual((await request('snapshot')).activity.execute,{});
 await request('activity',true);await request('run');await page.waitForTimeout(200);await page.getByLabel('Show cpu reads',{exact:true}).check();await page.getByLabel('Show cpu writes',{exact:true}).check();await page.getByLabel('Show vram reads',{exact:true}).check();const map=page.locator('.dual-memory-map');assert.equal(await map.locator('canvas.memory-activity').count(),2);await page.waitForTimeout(100);assert(await map.locator('[data-space=cpu] .memory-activity').evaluate(c=>c.getContext('2d').getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0)));
 if(process.env.MSXLAB_EVIDENCE_DIR)await map.screenshot({path:process.env.MSXLAB_EVIDENCE_DIR+'/MSXLab-activity.png'});
 const saved=await request('saveState');await request('loadState',saved);assert.deepEqual((await request('snapshot')).activity.execute,{});assert.deepEqual(errors,[]);console.log('PASS live CPU instruction/read/repeated-write counters, buffered VRAM reads/writes, inspection exclusion, stop/reset/restore and overlay rendering');
}finally{if(app)await app.close();await fs.rm(dir,{recursive:true,force:true});await fs.rm(env.MSXLAB_USER_DATA,{recursive:true,force:true});}
