import {_electron as electron} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const dir='projects/advanced-test',env={...process.env,MSXLAB_USER_DATA:'/tmp/msxlab-advanced-'+Date.now()};delete env.ELECTRON_RUN_AS_NODE;
await fs.cp('projects/kings-valley',dir,{recursive:true});const p=JSON.parse(await fs.readFile(dir+'/project.json','utf8'));p.id='advanced-test';p.name='Advanced test';p.breakpoints=[];await fs.writeFile(dir+'/project.json',JSON.stringify(p));let app;
try{
 app=await electron.launch({args:['.'],env});const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.panel-disassembler tbody tr',{timeout:20000});
 const info=JSON.parse(await fs.readFile('.msxlab-runtime.json','utf8'));const api=async(command,args={})=>{const response=await fetch(info.url,{method:'POST',headers:{Authorization:'Bearer '+info.token,'Content-Type':'application/json'},body:JSON.stringify({command,args})});const r=await response.json();assert(!r.error,r.error);return r.result;};
 await api('loadProject',{id:'advanced-test'});await page.waitForTimeout(4000);await api('pause');await page.waitForFunction(()=>document.querySelector('.backend-badge').textContent==='PAUSED');
 const frame=page.frames().find(f=>f.url().includes('/engine/index.html'));
 async function request(command,args){return page.evaluate(({command,args})=>new Promise((resolve,reject)=>{const f=document.querySelector('iframe[title="MSX emulator"]'),id=Math.floor(Math.random()*1e9)+1e9;const handler=e=>{if(e.source===f.contentWindow&&e.data.id===id&&e.data.type==='reply'){window.removeEventListener('message',handler);e.data.error?reject(Error(e.data.error)):resolve(e.data.result);}};window.addEventListener('message',handler);f.contentWindow.postMessage({source:'msxlab-ui',id,command,args},location.origin);}),{command,args});}
 // Controlled CPU program on the current engine: LD A,11; store E100; INC A; JP C000.
 await frame.evaluate(()=>{const m=WMSX.room.machine,b=m.eval('bus'),c=m.eval('cpu');[0x3e,0x11,0x32,0x00,0xe1,0x3c,0xc3,0x00,0xc0].forEach((v,i)=>b.write(0xc000+i,v));b.write(0xe100,0);const r=c.saveState();Object.assign(r,{PC:0xc000,SP:0xf000,Tn:0,p:0,ai:false,IFF1:0,INT:255});c.loadState(r);});
 await request('trackWrites',true);await request('writeWatch',[0xe100]);await request('run');await page.waitForTimeout(200);let snap=await request('snapshot');assert.equal(snap.status,'paused');assert.equal(snap.hit.reason,'write watchpoint');assert.equal(snap.cpu[0xe100],0x11);assert.equal(snap.lastWrites.at(-1).pc,0xc002);
 await request('writeWatch',[]);await request('breakpoints',[{address:0xc006,enabled:true,condition:'A == $12'}]);await request('run');await page.waitForTimeout(200);snap=await request('snapshot');assert.equal(snap.registers.PC,0xc006);assert.equal(snap.registers.A,0x12);
 const saved=await request('saveState');await request('step');await page.waitForTimeout(100);await request('loadState',saved);snap=await request('snapshot');assert.equal(snap.registers.PC,0xc006);await request('step');await page.waitForTimeout(100);assert.equal((await request('snapshot')).registers.PC,0xc000);
 await request('breakpoints',[]);await request('trace',true);await request('profile',true);await request('run');await page.waitForTimeout(180);await request('pause');await page.waitForTimeout(150);snap=await request('snapshot');assert(snap.trace.length>0&&snap.trace.length<=500);assert(Object.keys(snap.counts).length>0);
 const restartState=await request('saveState');await request('loadState',restartState);const cleared=await request('snapshot');assert.equal(cleared.trace.length,0);assert.equal(cleared.lastWrites.length,0);assert.equal(Object.keys(cleared.counts).length,0);assert.equal(cleared.monitoring.trace,true);assert.equal(cleared.monitoring.profile,true);
 await request('recordInput');await assert.rejects(()=>request('loadState',restartState),/Stop recording/);await frame.evaluate(()=>WMSX.room.keyboard.processMSXKey('SPACE',true));await page.waitForTimeout(70);await frame.evaluate(()=>WMSX.room.keyboard.processMSXKey('SPACE',false));await page.waitForTimeout(80);const recording=await request('stopRecording');assert.equal(recording.events,2);await request('replayInput');await page.waitForTimeout(800);snap=await request('snapshot');assert.equal(snap.recording.replaying,false);
 await request('pause');await page.waitForTimeout(100);const inspect=await request('inspect');assert(inspect.png.startsWith('data:image/png;base64,'));assert(inspect.width>200);
 // Pending interrupt is represented as interrupt entry, never as an executed opcode.
 await request('trace',true);await request('profile',true);await request('trackWrites',false);
 await frame.evaluate(()=>{const c=WMSX.room.machine.eval('cpu'),r=c.saveState();Object.assign(r,{PC:0xc000,SP:0xf000,Tn:0,p:0,ai:true,IFF1:1,INT:254,IM:1});c.loadState(r);});
 await request('step');await page.waitForTimeout(100);snap=await request('snapshot');assert.equal(snap.trace[0]?.kind,'interrupt');assert.equal(snap.counts[0xc000],undefined);
 // Persisted watchpoint command covers fetch reads and VRAM writes too.
 await request('trace',false);await request('profile',false);await request('breakpoints',[]);
 await frame.evaluate(()=>{const c=WMSX.room.machine.eval('cpu'),r=c.saveState();Object.assign(r,{PC:0xc000,SP:0xf000,Tn:0,p:0,ai:false,IFF1:0,INT:255});c.loadState(r);});
 await request('watchpoints',[{space:'cpu',address:0xc000,access:'read'}]);await request('run');await page.waitForTimeout(100);snap=await request('snapshot');assert.equal(snap.hit.reason,'read watchpoint');assert.equal(snap.registers.PC,0xc002);
 await request('watchpoints',[]);
 await frame.evaluate(()=>{const m=WMSX.room.machine,b=m.eval('bus'),c=m.eval('cpu');[0x3e,0x5a,0xd3,0x98,0xc3,0x04,0xc1].forEach((v,i)=>b.write(0xc100+i,v));b.output(0x99,0);b.output(0x99,0x40);const r=c.saveState();Object.assign(r,{PC:0xc100,SP:0xf000,Tn:0,p:0,ai:false,IFF1:0,INT:255});c.loadState(r);});
 await request('watchpoints',[{space:'vram',address:0,access:'write'}]);await request('run');await page.waitForTimeout(100);snap=await request('snapshot');assert.equal(snap.hit.reason,'VRAM write watchpoint');assert.equal(snap.vram[0],0x5a);assert.equal(snap.lastWrites.at(-1).pc,0xc102);
 const pausedVideo=snap.video;await page.waitForTimeout(120);const still=await request('snapshot');assert.equal(still.registers.PC,snap.registers.PC);assert.deepEqual(still.video,pausedVideo);
 // Open every registered panel so all resource renderers execute.
 for(const name of ['Fonts','Tiles','Palette','Level Map','Search','Memory Changes','Write Watchpoints','Profiler','References','Research History','Data Charts','Structures','Session & Replay']){await page.getByRole('button',{name:'Panels',exact:true}).click();await page.getByRole('button',{name,exact:true}).click();}
 assert.deepEqual(errors,[]);console.log('PASS CPU read/write and VRAM write watchpoints, stable CPU/video pause, writer PC, conditional breakpoint, save/restore + hooks, trace, profiler, keyboard replay, inspection, all panels');
}finally{if(app)await app.close();await fs.rm(dir,{recursive:true,force:true});await fs.rm(env.MSXLAB_USER_DATA,{recursive:true,force:true});}
