import {_electron as electron} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const id='assets-verification',dir='projects/'+id,profile='/tmp/msxlab-assets-'+Date.now();await fs.cp('projects/demo',dir,{recursive:true});const project=JSON.parse(await fs.readFile(dir+'/project.json','utf8'));project.id=id;project.name='Asset verification';project.assets=[];await fs.writeFile(dir+'/project.json',JSON.stringify(project));
const env={...process.env,MSXLAB_USER_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;let app;const errors=[];
async function api(command,args={}){const i=JSON.parse(await fs.readFile('.msxlab-runtime.json','utf8'));const r=await fetch(i.url,{method:'POST',headers:{Authorization:'Bearer '+i.token,'Content-Type':'application/json'},body:JSON.stringify({command,args})});const data=await r.json();assert(!data.error,data.error);return data.result;}
try{app=await electron.launch({args:['.'],env});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.panel-disassembler tbody tr');await api('loadProject',{id});await page.waitForTimeout(700);await page.getByRole('button',{name:'Panels',exact:true}).click();await page.getByRole('button',{name:'Fonts',exact:true}).click();const panel=page.locator('.panel-fonts');await panel.getByLabel('Graphics source').selectOption('cpu');await panel.getByLabel('Font trial text').fill('ABCD');assert.equal(await panel.getByLabel('Asset view').inputValue(),'text');await panel.getByText('Project assets (0)',{exact:true}).click();await panel.getByLabel('Asset name').fill('Test font');await panel.getByRole('button',{name:'Save new',exact:true}).click();await panel.getByText('Project assets (1)',{exact:true}).waitFor();await page.waitForTimeout(300);let saved=JSON.parse(await fs.readFile(dir+'/project.json','utf8'));assert.equal(saved.assets[0].config.text,'ABCD');assert.equal(saved.assets[0].config.source,'cpu');
 await panel.getByLabel('Asset preset').selectOption({label:'Level map'});await panel.getByLabel('Map columns').fill('20');await panel.getByLabel('Map entries').selectOption('u16be');await panel.getByRole('button',{name:'Update',exact:true}).click();await page.waitForTimeout(200);saved=JSON.parse(await fs.readFile(dir+'/project.json','utf8'));assert.equal(saved.assets[0].config.mapEntry,'u16be');await panel.getByLabel('Asset preset').selectOption({label:'Font 8×8'});await panel.getByLabel('Saved asset').selectOption('');await panel.getByLabel('Saved asset').selectOption(saved.assets[0].id);assert.equal(await panel.getByLabel('Map columns').inputValue(),'20');
 await panel.getByLabel('Asset view').selectOption('atlas');await panel.getByLabel('Asset zoom').selectOption('3');await panel.locator('canvas').click({position:{x:3,y:3}});await panel.getByText(/Item 0 · pixel/).waitFor();if(process.env.MSXLAB_EVIDENCE_DIR)await page.screenshot({path:process.env.MSXLAB_EVIDENCE_DIR+'/MSXLab-assets.png'});
 await api('loadProject',{id:'demo'});await panel.getByText('Project assets (0)',{exact:true}).waitFor();assert.equal(await panel.getByLabel('Saved asset').inputValue(),'');await api('loadProject',{id});await panel.getByText('Project assets (1)',{exact:true}).waitFor();await panel.getByLabel('Saved asset').selectOption(saved.assets[0].id);assert.equal(await panel.getByLabel('Map entries').inputValue(),'u16be');assert.deepEqual(errors,[]);console.log('PASS asset UI: font preview, formats, project save/update/reload/isolation, map endian/size, zoom and source navigation');
}finally{if(app)await app.close();await fs.rm(dir,{recursive:true,force:true});await fs.rm(profile,{recursive:true,force:true});}
