import assert from 'node:assert/strict';
import fs from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
let state={project:{id:'test',labels:[]},session:1,snapshot:{cpu:[1,2],vram:[0,0],rom:[0,0],seq:1,registers:{PC:0},memorySlots:{columns:[]}}};
let fail=false;const calls=[],engineCalls=[];
globalThis.__automationMock={store:{get:()=>state},command:async (name,args)=>{engineCalls.push({name,args});return name==='snapshot'?structuredClone(state.snapshot):name==='capture'?'data:image/png;base64,test':{bytes:[3]};},updateProject:p=>Object.assign(state.project,p),flushResearch:async()=>{if(fail)throw Error('save failed');}};
let source=fs.readFileSync('src/backend/automation.ts','utf8').replace("import {store,command,updateProject,flushResearch} from '../state/debugger';","const {store,command,updateProject,flushResearch}=globalThis.__automationMock;");
const {automation}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));
const call=async(name,args)=>{calls.push({name,args});return {status:'paused'};};
const api=(name,args={})=>automation(name,args,call);
assert.equal((await api('apiCapabilities')).version,2);
await api('rememberState',{name:'before'});state.snapshot.cpu[1]=9;state.snapshot.registers.PC=2;state.snapshot.seq=2;
let diff=(await api('compareState',{name:'before'})).data;assert.equal(diff.total,1);assert.equal(diff.changes[0].after,9);assert.equal(diff.registers.PC.after,2);
state.session++;await assert.rejects(api('compareState',{name:'before'}),/session/);state.session--;
await api('markInitialState');assert.deepEqual(calls.pop(),{name:'saveCheckpoint',args:{name:'api-initial',replace:false}});
await api('restartProject');assert.equal(calls.pop().name,'loadProject');
const label={id:'x',name:'TEST',space:'cpu',type:'DATA',address:1,end:1,comment:'Test'};
await api('upsertLabels',{labels:[label]});assert.equal(state.project.labels[0].name,'TEST');await api('undoResearch');assert.equal(state.project.labels.length,0);
await assert.rejects(api('upsertLabels',{labels:[{...label,address:-1}]}),/address/);
await assert.rejects(api('upsertLabels',{labels:[{...label,memoryScope:{primary:4,secondary:null}}]}),/slot/);
await api('upsertLabels',{labels:[label]});state.project.labels[0].name='manual';await assert.rejects(api('undoResearch'),/changed/);
await assert.rejects(api('runFor',{milliseconds:6000}),/milliseconds/);
assert.equal((await api('captureImage')).data.mimeType,'image/png');
state.snapshot.status='paused';state.project.watchpoints=[];await api('runUntil',{event:'write',space:'cpu',address:1,timeoutMs:10});assert.equal(engineCalls.filter(c=>c.name==='watchpoints').length,2);assert.deepEqual(engineCalls.at(-1).args,[]);await assert.rejects(api('runUntil',{event:'slot'}),/Supported events/);
console.log('PASS automation snapshots, session guards, lifecycle routing, images, label validation and conflict-safe undo');
