import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createRequire} from 'node:module';import {createServer} from 'vite';
const require=createRequire(import.meta.url),{makeDisk}=require('../electron/disk.cjs');
const server=await createServer({server:{middlewareMode:true}});
try{
 const {decode}=await server.ssrLoadModule('/src/backend/disassemble.ts');
 const cases=[{bytes:[0x21,0x34,0x12],size:3,text:'LD HL,1234'},{bytes:[0xdd,0x21,0x34,0x12],size:4,text:'LD IX,1234'},{bytes:[0xfd,0xcb,0xfe,0x46],size:4,text:'BIT 0,(IY-02)'},{bytes:[0x20,0xfe],size:2,text:'JR NZ,$4000'},{bytes:[0xcd,0x10,0xc0],size:3,text:'CALL C010'},{bytes:[0xdd,0x00],size:2,text:'NOP'}];
 for(const x of cases){const mem=Array(65536).fill(0);mem.splice(0x4000,x.bytes.length,...x.bytes);const actual=decode(mem,0x4000);assert.equal(actual.size,x.size);assert.equal(actual.text,x.text);}
 const {tilePixel,spritePixel,spriteAttributes}=await server.ssrLoadModule('/src/backend/graphics.ts');
 const v=Array(16384).fill(0),r=Array(8).fill(0);r[2]=6;r[3]=128;r[4]=0;r[5]=54;r[6]=7;v[6144]=1;v[8]=128;v[8192]=0xf1;assert.equal(tilePixel(v,r,0,0).color,15);assert.equal(tilePixel(v,r,1,0).color,1);
 r[1]=2;v[14336+16]=128;assert(spritePixel(v,r,0,8,0));assert(!spritePixel(v,r,0,0,0));v[6912]=10;v[6913]=20;v[6914]=0;v[6915]=0x85;v[6916]=208;const sp=spriteAttributes(v,r);assert.equal(sp.length,1);assert.equal(sp[0].x,-12);assert.equal(sp[0].y,11);
 const template=await fs.readFile('resources/environments/msxdos1/template.dsk');const original=Buffer.from(template);const bytes=Buffer.alloc(4000,0xab);const disk=makeDisk(template,[{name:'TEST.COM',content:bytes}]);assert.deepEqual(template,original);assert.equal(disk.length,737280);assert.equal(disk.subarray(3584,3595).toString(),'TEST    COM');assert.equal(disk.readUInt32LE(3584+28),4000);assert.equal(disk.readUInt16LE(3584+26),2);assert.deepEqual(disk.subarray(7168,7168+4000),bytes);assert.deepEqual(disk.subarray(512,2048),disk.subarray(2048,3584));assert.throws(()=>makeDisk(template,[{name:'LONGFILENAME.COM',content:bytes}]));assert.throws(()=>makeDisk(template,[{name:'BIG.COM',content:Buffer.alloc(737280)}]));
 const {readNumber}=await server.ssrLoadModule('/src/backend/values.ts');assert.equal(readNumber([255],0,'s8'),-1);assert.equal(readNumber([0x34,0x12],0,'u16le'),0x1234);assert.equal(readNumber([0x34,0x12],0,'u16be'),0x3412);assert.equal(readNumber([0,0,128,63],0,'f32le'),1);assert.equal(readNumber([1],0,'u16le'),null);
 const {matchPattern}=await server.ssrLoadModule('/src/backend/patterns.ts');assert(matchPattern('LD A,#0; LD B,#0',[{text:'LD A,01'},{text:'LD B,01'}]));assert(!matchPattern('LD A,#0; LD B,#0',[{text:'LD A,01'},{text:'LD B,02'}]));
 const {MockDebuggerBackend}=await server.ssrLoadModule('/src/backend/MockDebuggerBackend.ts');const mock=new MockDebuggerBackend();await mock.command('step');let snap=await mock.command('snapshot');assert.equal(snap.registers.PC,0x8002);assert.equal(snap.registers.A,1);assert.equal(snap.cpu[0xc000],0);await mock.command('step');assert.equal((await mock.command('snapshot')).cpu[0xc000],1);await mock.command('over');snap=await mock.command('snapshot');assert.equal(snap.registers.PC,0x8008);assert.equal(snap.registers.SP,0xf000);assert.equal(snap.registers.A,2);mock.dispose();
 console.log('PASS numeric formats, pattern binding, coherent mock scenario; decoder, indexed operands, relative branches, VDP pixels, sprites, FAT12 and capacity');
}finally{await server.close();}
