import {_electron as electron} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import path from 'node:path';
const tmp='/tmp/msxlab-launch-ui-'+Date.now(),env={...process.env,MSXLAB_USER_DATA:tmp+'/profile'};delete env.ELECTRON_RUN_AS_NODE;await fs.mkdir(tmp,{recursive:true});let app,id;
async function api(command,args={}){const info=JSON.parse(await fs.readFile('.msxlab-runtime.json','utf8'));const r=await fetch(info.url,{method:'POST',headers:{Authorization:'Bearer '+info.token,'Content-Type':'application/json'},body:JSON.stringify({command,args})});const data=await r.json();assert(!data.error,data.error);return data.result;}
try{const code=Buffer.alloc(0x70);Buffer.from([0x3e,0x67,0x32,0,0xe1,0x11,0x40,1,0x0e,0x0f,0xcd,5,0,0x32,1,0xe1,0x11,0,0xe2,0x0e,0x1a,0xcd,5,0,0x11,0x40,1,0x0e,0x14,0xcd,5,0,0x32,2,0xe1,0xc3,0x23,1]).copy(code);code.write('DATA    BIN',0x41);await fs.writeFile(tmp+'/test.com',code);await fs.writeFile(tmp+'/DATA.BIN',Buffer.from([11,22,33]));const rom=Buffer.alloc(16384);rom.write('AB');rom.writeUInt16LE(0x4010,2);rom[0x10]=0xc9;await fs.writeFile(tmp+'/extra.rom',rom);
 app=await electron.launch({args:['.'],env});const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.panel-disassembler tbody tr');const p=await api('createProject',{sourcePath:tmp+'/test.com'});id=p.id;await api('loadProject',{id});assert((await page.locator('.panel-projects').innerText()).includes(p.name));
 await page.getByRole('button',{name:'Launch setup…',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Project launch setup'});await dialog.getByRole('textbox',{name:'Project name',exact:true}).fill('Configured DOS test');await dialog.getByRole('textbox',{name:'Boot command'}).fill('APP');
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},tmp+'/DATA.BIN');await dialog.getByRole('button',{name:'Add disk file…'}).click();await dialog.getByRole('textbox',{name:'Disk filename 1'}).waitFor();
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},tmp+'/extra.rom');await dialog.getByRole('button',{name:'Choose ROM…'}).click();
 await dialog.getByRole('button',{name:'Save & restart'}).click();await dialog.waitFor({state:'detached'});await page.waitForTimeout(12000);const saved=JSON.parse(await fs.readFile('projects/'+id+'/project.json','utf8'));assert.equal(saved.name,'Configured DOS test');assert.equal(saved.launch.extras[0].name,'DATA.BIN');assert(saved.secondaryRom.endsWith('SECOND.ROM'));assert.deepEqual((await api('readMemory',{address:0xe100,length:3})).bytes,[0x67,0,0]);assert.deepEqual((await api('readMemory',{address:0xe200,length:3})).bytes,[11,22,33]);
 await page.getByRole('button',{name:'Launch setup…',exact:true}).click();await dialog.getByRole('textbox',{name:'Launch profile name'}).fill('With resources');await dialog.getByRole('button',{name:'Save profile',exact:true}).click();await dialog.getByRole('button',{name:'Apply launch profile With resources'}).waitFor();await dialog.getByRole('button',{name:'Close launch setup'}).click();
 const frame=page.frames().find(f=>f.url().includes('/engine/index.html'));assert((await frame.evaluate(()=>WMSX.CARTRIDGE2_URL)).endsWith('SECOND.ROM'));
 await api('configureLaunch',{id,options:{removeFiles:['DATA.BIN'],secondaryRom:null},run:true});const after=JSON.parse(await fs.readFile('projects/'+id+'/project.json','utf8'));assert(!after.secondaryRom);assert.equal(after.launch.extras.length,0);await page.getByRole('button',{name:'Launch setup…',exact:true}).click();await dialog.getByRole('button',{name:'Apply launch profile With resources'}).click();await dialog.waitFor({state:'detached'});const restored=JSON.parse(await fs.readFile('projects/'+id+'/project.json','utf8'));assert.equal(restored.launch.extras.length,1);assert(restored.secondaryRom);assert.deepEqual(errors,[]);console.log('PASS launch UI/API: configure DOS project, bundle extra file + second ROM, actual COM reads bundled file through DOS, remove resources and restart');
}finally{if(app)await app.close();if(id)await fs.rm('projects/'+id,{recursive:true,force:true});await fs.rm(tmp,{recursive:true,force:true});}
