import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{createFromFile,updateBuild}=require('../electron/projects.cjs'),{configure,profile}=require('../electron/launch.cjs');const tmp='/tmp/msxlab-launch-config-'+Date.now();await fs.mkdir(tmp);let project;
try{
 await fs.writeFile(tmp+'/test.com',Buffer.from([0xc9]));await fs.writeFile(tmp+'/data.bin',Buffer.from([1,2,3,4]));project=await createFromFile(tmp+'/test.com','Launch test');const dir='projects/'+project.id;
 assert.equal(project.engineSha256.length,64);assert.equal(project.launchHash.length,64);assert(project.launch.dos.system.sha256);assert(project.launch.template.sha256);
 project=await configure(project,{name:'Configured',machine:'MSX1J',addFiles:[{name:'DATA.BIN',sourcePath:tmp+'/data.bin'}],bootCommand:'APP ARG'});
 let disk=await fs.readFile(dir+'/'+project.disk);const names=Array.from({length:112},(_,i)=>disk.subarray(3584+i*32,3595+i*32).toString()).filter(n=>n.charCodeAt(0));assert(names.includes('DATA    BIN'));assert(project.buildFiles.some(f=>f.name==='DATA.BIN'&&f.size===4));assert.equal(project.name,'Configured');
 const named=await profile(project,'save',{name:'With data'});const profileId=named.activeLaunchProfile;project=named;assert.equal(named.launchProfiles[0].settings.engineSha256,named.engineSha256);const wrong=structuredClone(named);wrong.launchProfiles[0].settings.engineSha256='0'.repeat(64);await assert.rejects(()=>profile(wrong,'apply',{profileId}),/engine version changed/);
 const before=await fs.readFile(dir+'/project.json','utf8');for(const options of [{addFiles:[{name:'APP.COM',sourcePath:tmp+'/data.bin'}]},{machine:'INVALID'},{addFiles:[{name:'DATA.BIN',sourcePath:tmp+'/data.bin'}]},{bootCommand:'APP\nBAD'},{engine:'unknown'}]){await assert.rejects(()=>configure(project,options));assert.equal(await fs.readFile(dir+'/project.json','utf8'),before);}
 const readFile=fs.readFile;fs.readFile=async(file,...args)=>String(file).endsWith('/wmsx.js')?Buffer.from('changed engine'):readFile(file,...args);try{await assert.rejects(()=>configure(project,{}),/registered checksum/);assert.equal(await readFile(dir+'/project.json','utf8'),before);}finally{fs.readFile=readFile;}
 await fs.writeFile(tmp+'/test.com',Buffer.from([0x00,0xc9]));const updated=await updateBuild(project,tmp+'/test.com');assert.deepEqual(updated.launch,project.launch);assert(updated.buildFiles.some(f=>f.name==='DATA.BIN'));assert.notEqual(updated.disk,project.disk);assert((await fs.stat(dir+'/'+project.disk)).size>0);
 await fs.writeFile(tmp+'/data.bin',Buffer.from([9,9]));const again=await updateBuild(updated,tmp+'/test.com');assert.equal(again.buildFiles.find(f=>f.name==='DATA.BIN').size,4);
 const bad=path.join(dir,again.launch.extras[0].path);const original=await fs.readFile(bad);await fs.writeFile(bad,Buffer.from([5]));const old=await fs.readFile(dir+'/project.json','utf8');await assert.rejects(()=>updateBuild(again,tmp+'/test.com'),/resource changed/);assert.equal(await fs.readFile(dir+'/project.json','utf8'),old);await fs.writeFile(bad,original);
 const removed=await configure(again,{removeFiles:['DATA.BIN']});assert(!removed.buildFiles.some(f=>f.name==='DATA.BIN'));
 const restored=await profile(removed,'apply',{profileId});assert(restored.buildFiles.some(f=>f.name==='DATA.BIN'));assert.equal(restored.buildSha256,again.buildSha256);assert.equal(restored.activeLaunchProfile,profileId);await assert.rejects(()=>profile(restored,'save',{name:'With data'}));const deleted=await profile(restored,'delete',{profileId});assert.equal(deleted.launchProfiles.length,0);assert(!deleted.activeLaunchProfile);
 console.log('PASS launch profiles: pinned DOS/template, files on FAT12, boot command, update retains dependencies, original source changes isolated, hash mismatch and invalid configs preserve project');
}finally{if(project)await fs.rm('projects/'+project.id,{recursive:true,force:true});await fs.rm(tmp,{recursive:true,force:true});}
