import assert from 'node:assert/strict';import {createServer} from 'vite';const server=await createServer({server:{middlewareMode:true}});
try{const {searchMemory,compareMemory,numericValue}=await server.ssrLoadModule('/src/backend/memorySearch.ts');const bytes=[0x3e,5,0x32,0x3e,4,0x32,0xff,0xfe,0,1],base={start:0,end:9,format:'u8'};
 assert.deepEqual(searchMemory(bytes,{...base,mode:'hex',query:'3E ?? 32'}).matches.map(r=>r.address),[0,3]);assert.deepEqual(searchMemory(bytes,{...base,mode:'number',query:'4'}).matches.map(r=>r.address),[4]);assert.deepEqual(searchMemory(bytes,{...base,format:'s8',mode:'number',query:'-1'}).matches.map(r=>r.address),[6]);assert.deepEqual(searchMemory(bytes,{...base,start:7,format:'u16be',mode:'number',query:'1'}).matches.map(r=>r.address),[8]);assert.equal(searchMemory([1,2,1,2],{start:1,end:3,format:'u16le',mode:'number',query:'513',aligned:true}).matches[0].address,2);
 assert.throws(()=>searchMemory(bytes,{...base,mode:'hex',query:'3E ?'}));assert.throws(()=>searchMemory(bytes,{...base,end:10,mode:'number',query:'4'}));assert.throws(()=>numericValue('256','u8'));assert.throws(()=>numericValue('-129','s8'));assert.throws(()=>numericValue('1.5','u16le'));assert.throws(()=>numericValue('1e99','f32le'));
 const float=[...new Uint8Array(new Float32Array([0.1]).buffer)];assert.equal(searchMemory(float,{start:0,end:3,format:'f32le',mode:'number',query:'0.1'}).total,1);
 const before=[5,5,5,1,0],after=[4,6,5,0,0];const range={start:0,end:4,format:'u8'};assert.deepEqual(compareMemory(before,after,{...range,mode:'delta',value:'-1'}).map(r=>r.address),[0,3]);assert.deepEqual(compareMemory(before,after,{...range,mode:'decreased',candidates:[0,1,2]}).map(r=>r.address),[0]);assert.equal(compareMemory(before,after,{...range,mode:'changed',candidates:[]}).length,0);assert.deepEqual(compareMemory(before,after,{...range,mode:'equal',value:'5'}).map(r=>r.address),[2]);assert.throws(()=>compareMemory(before,after,{...range,mode:'delta',value:''}));assert.equal(compareMemory([0,1],[0,0],{start:0,end:1,format:'u16le',mode:'decreased'})[0].before,256);
 const many=searchMemory(Array(15000).fill(1),{start:0,end:14999,format:'u8',mode:'number',query:'1'});assert.equal(many.total,15000);assert.equal(many.matches.length,10000);
 const {spriteRanges}=await server.ssrLoadModule('/src/backend/graphics.ts');assert.deepEqual(spriteRanges([0,2,0,0,0,0,7],{address:0x3ffc,pattern:255}),{attributes:{address:0x3ffc,end:0x3fff},pattern:{address:0x3fe0,end:0x3fff}});
 console.log('PASS memory search: masks, signed/endian/float numbers, alignment, ranges, bounded results, snapshot delta and candidate narrowing');
}finally{await server.close();}
