import assert from 'node:assert/strict';
import {createMemorySlots} from '../public/engine/memory-slots.js';
const base={isExpanded:()=>false};
const empty={...base,format:{name:'Empty'}};
const bios={...base,format:{name:'BIOS'},bytes:new Uint8Array(32768),read:a=>a<32768?0x42:255};
const bytes=new Uint8Array(8*16384);for(let b=0;b<8;b++)bytes.fill(b,b*16384,(b+1)*16384);
const banks=[7,5,2,0],mapper={...base,format:{name:'RAMMapper'},bytes,inputAll:p=>0xf8|banks[p-252]};
const rom={...base,format:{name:'Mirrored'},bytes:new Uint8Array(16384),saveState:()=>({ba:16384,m:true}),read:()=>0xab};
const unknown={...base,format:{name:'UnknownDevice'},bytes:new Uint8Array(16384),read:()=>{throw Error('must not read an unknown device')}};
let secondary=0x10,primary=0xf4; // BIOS, cartridge, RAM subslot 1, RAM subslot 0.
const expanded={isExpanded:()=>true,getSubSlot:n=>[mapper,unknown,empty,empty][n],getSecondarySlotConfig:()=>secondary};
const bus={getSlot:n=>[bios,rom,empty,expanded][n],getPrimarySlotConfig:()=>primary};
const inspect=createMemorySlots(bus,()=>[[1],[2]]),before=inspect.snapshot();
assert.deepEqual(before.columns.filter(c=>c.activePages.length).map(c=>[c.id,c.activePages]),[['0',[0]],['1',[1]],['3.0',[3]],['3.1',[2]]]);
assert.equal(before.columns.find(c=>c.id==='1').connector,'A');assert.equal(before.columns.find(c=>c.id==='2').connector,'B');assert.equal(before.columns.find(c=>c.id==='3.0').connector,null);
assert.equal(createMemorySlots(bus,()=>[[3,1],[2]]).snapshot().columns.find(c=>c.id==='3.1').connector,'A');
const ram=before.columns.find(c=>c.id==='3.0');assert.deepEqual(ram.banks,banks);assert.equal(ram.bankCount,8);
assert.deepEqual(inspect.read({primary:3,secondary:0,page:2,bank:6,length:3}),{address:32768,bank:6,bytes:[6,6,6]});
assert.deepEqual(inspect.snapshot(),before,'inspection must not switch slots or banks');
assert.deepEqual(inspect.read({primary:0,page:3}),{address:49152,bytes:[]});
assert.equal(inspect.read({primary:1,page:0,length:1}).bytes[0],0xab);
assert.equal(before.columns.find(c=>c.id==='3.1').start,null);
assert.throws(()=>inspect.read({primary:3,secondary:1,page:0}));assert.throws(()=>inspect.read({primary:3,secondary:0,bank:8}));assert.throws(()=>inspect.read({primary:3,secondary:null}));
secondary=0;primary=0xff;banks[1]=4;
assert.deepEqual(inspect.snapshot().columns.find(c=>c.id==='3.0').activePages,[0,1,2,3]);
assert.equal(inspect.snapshot().columns.find(c=>c.id==='3.0').banks[1],4);
console.log('PASS primary/subslot mapping, physical bank reads, live mapping updates and read-only inspection');
assert.equal(inspect.read({primary:3,secondary:0,page:1,bank:6,length:16384}).bytes.length,16384);
assert.deepEqual(inspect.read({primary:3,secondary:0,page:1,bank:6,offset:16382,length:2}),{address:32766,bank:6,bytes:[6,6]});
assert.throws(()=>inspect.read({primary:3,secondary:0,bank:0,offset:16383,length:2}));
assert.deepEqual(banks,[7,4,2,0]);
console.log('PASS full bank, end-of-bank range and unchanged mapper selection');
assert.equal(inspect.matches({primary:3,secondary:0,bank:4},0x4000),true);
assert.equal(inspect.matches({primary:3,secondary:0,bank:5},0x4000),false);
assert.equal(inspect.matches({primary:3,secondary:1,bank:4},0x4000),false);
assert.equal(inspect.matches({primary:1,secondary:null},0x4000),false);
assert.equal(inspect.matches(undefined,0x4000),true);
banks[1]=5;
assert.equal(inspect.matches({primary:3,secondary:0,bank:4},0x4000),false);
assert.equal(inspect.matches({primary:3,secondary:0,bank:5},0x4000),true);
primary=0xf4;
assert.equal(inspect.matches({primary:1,secondary:null},0x4000),true);
assert.equal(inspect.matches({primary:1,secondary:0},0x4000),false);
console.log('PASS breakpoint scope follows live slot, subslot and mapper switches');
