import {_electron as electron} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const id='research-ui-test',profile='/tmp/msxlab-research-ui-'+Date.now(),dir=new URL('../projects/'+id+'/',import.meta.url);await fs.cp(new URL('../projects/kings-valley/',import.meta.url),dir,{recursive:true});const p=JSON.parse(await fs.readFile(new URL('project.json',dir),'utf8'));p.id=id;p.name='Research UI Test';p.breakpoints=[];await fs.writeFile(new URL('project.json',dir),JSON.stringify(p));
const env={...process.env,MSXLAB_USER_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;let app;const errors=[];
async function api(command,args={}){const info=JSON.parse(await fs.readFile('.msxlab-runtime.json','utf8'));const r=await fetch(info.url,{method:'POST',headers:{Authorization:'Bearer '+info.token,'Content-Type':'application/json'},body:JSON.stringify({command,args})});const data=await r.json();assert(!data.error,data.error);return data.result;}
try{app=await electron.launch({args:['.'],env});const page=await app.firstWindow();page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.panel-disassembler tbody tr');await api('loadProject',{id});await page.waitForTimeout(3500);await api('pause');
 const code=page.locator('.panel-disassembler');async function go(a){await page.getByRole('textbox',{name:'Go to address or symbol'}).fill(a);await page.getByRole('textbox',{name:'Go to address or symbol'}).press('Enter');}
 await go('454D');await code.getByText('PROC · SPRITE.REV.MOVE',{exact:true}).waitFor();await code.getByRole('combobox',{name:'Listing mode'}).selectOption('procedure');const addresses=await code.locator('tbody tr td:nth-child(2)').allTextContents();assert.equal(addresses[0],'454C');assert(addresses.every(a=>parseInt(a,16)>=0x454c&&parseInt(a,16)<=0x4567));
 await code.getByRole('button',{name:'Edit block'}).click();await code.getByRole('textbox',{name:'Label comment'}).fill('Research UI: mirror sprites');await code.getByRole('textbox',{name:'Label length'}).fill('28');assert.equal(await code.getByRole('textbox',{name:'Label end'}).inputValue(),'4567');await code.getByRole('button',{name:'Save 454C',exact:true}).click();await page.waitForTimeout(200);assert.equal(JSON.parse(await fs.readFile(new URL('project.json',dir),'utf8')).labels.find(l=>l.name==='SPRITE.REV.MOVE').comment,'Research UI: mirror sprites');
 await code.getByRole('combobox',{name:'Listing mode'}).selectOption('annotated');await go('4323');assert.equal(await code.locator('tbody tr').first().getAttribute('data-row-kind'),'data');assert((await code.locator('tbody tr').first().innerText()).includes('DB '));await code.getByRole('combobox',{name:'Listing mode'}).selectOption('code');assert.equal(await code.locator('tbody tr').first().getAttribute('data-row-kind'),'code');
 const labels=page.locator('.panel-labels');await labels.getByRole('combobox',{name:'Label category'}).selectOption('PROC');assert((await labels.locator('tbody tr').count())>0);assert((await labels.locator('tbody tr td:nth-child(3)').allTextContents()).every(t=>t.startsWith('PROC')));
 await page.getByRole('button',{name:'Panels',exact:true}).click();await page.getByRole('button',{name:'References',exact:true}).click();await page.locator('.panel-references').getByRole('button',{name:'Scan marked procedures'}).click();await page.waitForTimeout(100);assert((await page.locator('.panel-references tbody tr').count())>0);

 await page.getByRole('button',{name:'Panels',exact:true}).click();await page.getByRole('button',{name:'Labels',exact:true}).click();
 await labels.getByRole('button',{name:'Import / export',exact:true}).click();
 const imported={format:'msxlab-labels',version:1,labels:[{name:'UI_BITMAP',address:0xc000,end:0xc01f,space:'cpu',type:'DATA BM2',comment:'Imported bitmap fixture'}]};
 await labels.getByLabel('Import label file').setInputFiles({name:'fixture-labels.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});
 await labels.getByRole('button',{name:'Import valid labels',exact:true}).click();await labels.getByRole('status').filter({hasText:'Imported: 1 added'}).waitFor();
 const after=JSON.parse(await fs.readFile(new URL('project.json',dir),'utf8'));assert.equal(after.labels.find(l=>l.name==='UI_BITMAP').end,0xc01f);assert.equal((await fs.readdir(new URL('research/imports/',dir))).length,1);
 await labels.getByRole('button',{name:'Export labels',exact:true}).click();await labels.getByRole('status').filter({hasText:'Export saved:'}).waitFor();const exports=await fs.readdir(new URL('research/exports/',dir));const exported=JSON.parse(await fs.readFile(new URL('research/exports/'+exports[0],dir),'utf8'));assert.equal(exported.labels.length,after.labels.length);assert.equal(exported.format,'msxlab-labels');
 await labels.getByRole('button',{name:'Close label transfer'}).click();await labels.getByRole('combobox',{name:'Label category'}).selectOption('DATA');await labels.getByPlaceholder('Filter labels…').fill('UI_BITMAP');
 const engine=page.frames().find(f=>f.url().includes('/engine/index.html'));await labels.getByRole('button',{name:'Open block UI_BITMAP'}).click();const bitmap=page.locator('.panel-bitmap').filter({hasText:'Block $C000–$C01F · 32 bytes'});assert.equal(await bitmap.getByRole('combobox',{name:'Graphics source'}).inputValue(),'cpu');assert.equal(await bitmap.getByRole('combobox',{name:'Bits per pixel'}).inputValue(),'2');assert.equal(await bitmap.getByRole('textbox',{name:'Address',exact:true}).inputValue(),'C000');await bitmap.getByText('Block $C000–$C01F · 32 bytes').waitFor();assert.equal(page.frames().find(f=>f.url().includes('/engine/index.html')),engine);
 const found=await api('readLabels',{query:'UI_BITMAP'});assert.equal(found.total,1);assert.equal(found.labels[0].length,32);const listing=await api('readDisassembly',{address:0xc000,limit:2});assert.equal(listing.rows[0].kind,'data');assert.equal(listing.rows[0].block.name,'UI_BITMAP');const routine=await api('readDisassembly',{address:0x454d,mode:'procedure'});assert.equal(routine.address,0x454c);assert(routine.rows.every(r=>r.address+r.size-1<=0x4567));assert((await api('readReferences',{})).total>0);await assert.rejects(()=>api('readDisassembly',{limit:501}));
 const map=page.locator('.panel-memory-map');await map.getByText('VRAM · 16 KB',{exact:true}).waitFor();await map.locator('[data-space=vram] .memory-map-regions').click({position:{x:40,y:10}});assert.equal(await page.locator('.panel-memory').first().getByRole('combobox',{name:'Memory source'}).inputValue(),'vram');
 assert.deepEqual(errors,[]);console.log('PASS research UI: containing procedure, bounded listing, descriptions and length saved to own project, data/raw modes, category filter, references, import/archive/export and typed block viewer');
}catch(e){if(app){const page=await app.firstWindow();await page.screenshot({path:'work/research-ui-failure.png'});console.log(await page.locator('.panel-labels').evaluate(el=>({rect:el.getBoundingClientRect().toJSON(),tools:[...el.querySelectorAll('.panel-tools')].map(x=>({rect:x.getBoundingClientRect().toJSON(),scrollWidth:x.scrollWidth,clientWidth:x.clientWidth,scrollLeft:x.scrollLeft})),button:[...el.querySelectorAll('button')].find(x=>x.textContent==='Import / export')?.getBoundingClientRect().toJSON()})));}throw e;}finally{if(app)await app.close();await fs.rm(profile,{recursive:true,force:true});await fs.rm(dir,{recursive:true,force:true});}
