import {_electron as electron} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const id='sprite-writer-'+Date.now(),dir='projects/'+id,env={...process.env,MSXLAB_USER_DATA:'/tmp/'+id};delete env.ELECTRON_RUN_AS_NODE;let app;
await fs.cp('projects/kings-valley',dir,{recursive:true});const p=JSON.parse(await fs.readFile(dir+'/project.json','utf8'));p.id=id;p.name='King’s Valley · verification';p.breakpoints=[];p.watchpoints=[];await fs.writeFile(dir+'/project.json',JSON.stringify(p));
try{app=await electron.launch({args:['.'],env});const page=await app.firstWindow();await page.waitForSelector('.panel-disassembler tbody tr');const info=JSON.parse(await fs.readFile('.msxlab-runtime.json','utf8'));async function api(command,args={}){const r=await fetch(info.url,{method:'POST',headers:{Authorization:'Bearer '+info.token,'Content-Type':'application/json'},body:JSON.stringify({command,args})});const x=await r.json();assert(!x.error,x.error);return x.result;}
 await api('loadProject',{id});await page.waitForTimeout(14000);const frame=page.frames().find(f=>f.url().includes('/engine/index.html'));await frame.evaluate(()=>WMSX.room.keyboard.processMSXKey('SPACE',true));await page.waitForTimeout(1000);await frame.evaluate(()=>WMSX.room.keyboard.processMSXKey('SPACE',false));await page.waitForTimeout(3000);await api('pause');
 await page.getByRole('button',{name:'Panels',exact:true}).click();await page.getByRole('button',{name:'Sprites',exact:true}).click();const sprites=page.locator('.panel-sprites');await sprites.getByRole('button',{name:'Watch attributes sprite 0',exact:true}).click();await page.waitForTimeout(200);const point=JSON.parse(await fs.readFile(dir+'/project.json','utf8')).watchpoints[0];assert.equal(point.space,'vram');assert.equal(point.end,point.address+3);await api('run');let status;for(let i=0;i<80;i++){await page.waitForTimeout(100);status=await api('status');if(status.status==='paused')break;}assert.equal(status.status,'paused');assert.equal(status.hit.access.space,'vram');assert(status.hit.access.address>=point.address&&status.hit.access.address<=point.end);assert.equal(status.hit.access.kind,'instruction');
 const code=await api('readDisassembly',{address:status.hit.access.pc,mode:'raw',limit:1});assert(/OUT/.test(code.rows[0].text));console.log('SPRITE_WRITER',JSON.stringify({range:point,hit:status.hit,code:code.rows[0].text}));
 await page.getByRole('button',{name:'Panels',exact:true}).click();await page.getByRole('button',{name:'Write Watchpoints',exact:true}).click();await page.getByRole('button',{name:'Go to writer',exact:true}).click();assert.equal(await page.locator('.panel-disassembler').getByRole('textbox',{name:'Address',exact:true}).inputValue(),status.hit.access.pc.toString(16).toUpperCase().padStart(4,'0'));
 console.log('PASS live King’s Valley sprite attributes → VRAM range watch → OUT instruction → disassembler');
}finally{if(app)await app.close();await fs.rm(dir,{recursive:true,force:true});await fs.rm(env.MSXLAB_USER_DATA,{recursive:true,force:true});}
