import {_electron as electron} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const dir='projects/watch-api-test',env={...process.env,MSXLAB_USER_DATA:'/tmp/msxlab-watch-api-'+Date.now()};delete env.ELECTRON_RUN_AS_NODE;let app;
await fs.cp('projects/kings-valley',dir,{recursive:true});const p=JSON.parse(await fs.readFile(dir+'/project.json','utf8'));p.id='watch-api-test';p.breakpoints=[];p.watchpoints=[];await fs.writeFile(dir+'/project.json',JSON.stringify(p));
try{
 app=await electron.launch({args:['.'],env});const page=await app.firstWindow();await page.waitForSelector('.panel-disassembler tbody tr',{timeout:20000});const info=JSON.parse(await fs.readFile('.msxlab-runtime.json','utf8'));
 async function api(command,args={},fails=false){const response=await fetch(info.url,{method:'POST',headers:{Authorization:'Bearer '+info.token,'Content-Type':'application/json'},body:JSON.stringify({command,args})});const body=await response.json();if(fails){assert.equal(response.status,400);assert(body.error);return;}assert(!body.error,body.error);return body.result;}
 await api('loadProject',{id:p.id});await page.waitForTimeout(1000);await api('pause');await page.waitForFunction(()=>document.querySelector('.backend-badge').textContent==='PAUSED');const frame=page.frames().find(f=>f.url().includes('/engine/index.html'));
 async function fixture(bytes){await frame.evaluate(bytes=>{const c=WMSX.room.machine.eval('cpu'),b=WMSX.room.machine.eval('bus');bytes.forEach((n,i)=>b.write(0xc000+i,n));const r=c.saveState();Object.assign(r,{PC:0xc000,SP:0xf000,Tn:0,p:0,ai:false,IFF1:0,INT:255});c.loadState(r);},bytes);}
 async function snap(){return frame.evaluate(()=>({PC:WMSX.room.machine.eval('cpu').saveState().PC}));}
 const points=[{space:'cpu',address:0xe100,end:0xe102,access:'write'}];await api('setWatchpoints',{points});assert.equal(JSON.parse(await fs.readFile(dir+'/project.json','utf8')).watchpoints[0].end,0xe102);
 await api('writeMemory',{space:'cpu',address:0xe101,bytes:[0x11]});await fixture([0x3e,0x11,0x32,0x01,0xe1,0xc3,0x05,0xc0]);await api('run');await page.waitForTimeout(100);assert.equal((await snap()).PC,0xc005);assert.equal((await api('status')).status,'paused');
 const found=await api('searchMemory',{query:'17',start:0xe100,end:0xe102});assert(found.matches.some(m=>m.address===0xe101));const masked=await api('searchMemory',{query:'3E ?? 32',mode:'hex',start:0xc000,end:0xc008});assert.equal(masked.matches[0].address,0xc000);await api('searchMemory',{query:'256',format:'u8'},true);
 const firstHit=(await api('status')).hit;assert.deepEqual(firstHit.access,{space:'cpu',address:0xe101,access:'write',before:0x11,value:0x11,pc:0xc002,pcKnown:true,kind:'instruction',after:0x11});
 await api('setWatchpoints',{points:[{space:'io',address:0x40,end:0x4f,access:'write'}]});await fixture([0x3e,0xab,0xd3,0x42,0xc3,0x04,0xc0]);await api('run');await page.waitForTimeout(100);assert.equal((await snap()).PC,0xc004);assert.equal((await api('status')).hit.access.port,0xab42);assert.equal((await api('status')).hit.access.pc,0xc002);assert.equal((await api('status')).status,'paused');
 await api('setWatchpoints',{points:[{space:'io',address:0x42,access:'read'}]});await fixture([0xdb,0x42,0xc3,0x02,0xc0]);await api('run');await page.waitForTimeout(100);assert.equal((await snap()).PC,0xc002);assert.equal((await api('status')).hit.access.access,'read');assert.equal((await api('status')).hit.access.pc,0xc000);assert.equal((await api('status')).status,'paused');
 await api('setWatchpoints',{points:[{space:'cpu',address:0x10,end:0,access:'read'}]},true);assert.equal(JSON.parse(await fs.readFile(dir+'/project.json','utf8')).watchpoints[0].space,'io');
 await api('setWatchpoints',{points:[{...points[0],enabled:false}]});await api('setBreakpoints',{points:[{address:0xc006,condition:'A == $12'}]});await api('trace',{enabled:true});await fixture([0x3e,0x11,0x32,0x01,0xe1,0x3c,0xc3,0x06,0xc0]);await api('run');await page.waitForTimeout(100);assert.equal((await snap()).PC,0xc006);const trace=await api('readTrace');assert(trace.length>=3);assert.equal(trace.at(-1).address,0xc005);
 await api('setBreakpoints',{points:[{address:0xc000,condition:'invalid'}]},true);assert.equal(JSON.parse(await fs.readFile(dir+'/project.json','utf8')).breakpoints[0].address,0xc006);
 await api('readMemory',{address:0,length:0},true);await api('readMemory',{space:'bad',address:0,length:1},true);
 await api('setBreakpoints',{points:[]});await api('run');await api('stepOver',{},true);const pauseResult=await api('pause');assert.equal(pauseResult.status,'paused');await api('setWatchpoints',{points:[]});await fixture([0xc3,0x00,0xc0]);const untilResult=await api('until',{address:0xd123});assert.equal(untilResult.status,'paused');assert.equal(untilResult.hit.reason,'run-to timeout');
 await api('setWatchpoints',{points:[{space:'cpu',address:0xeffe,end:0xefff,access:'write'}]});await frame.evaluate(()=>{const c=WMSX.room.machine.eval('cpu'),r=c.saveState();Object.assign(r,{PC:0xc000,SP:0xf000,Tn:0,p:0,ai:true,IFF1:1,INT:254,IM:1});c.loadState(r);});const interrupt=await api('step');assert.equal(interrupt.hit.access.kind,'interrupt');assert.equal(interrupt.hit.access.pc,0xc000);assert.equal(interrupt.registers.PC,0x38);await api('setWatchpoints',{points:[]});await fixture([0xc3,0,0xc0]);await api('run');const manual=await api('pause');assert(!manual.hit.access);
 console.log('PASS range and unchanged-write watchpoints, I/O read/write, disabled points, persisted API configuration, trace API and input validation');
}finally{if(app)await app.close();await fs.rm(dir,{recursive:true,force:true});await fs.rm(env.MSXLAB_USER_DATA,{recursive:true,force:true});}
