const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const defaults={enabled:false,baseUrl:'https://llm.wavespeed.ai/v1',models:['openai/gpt-5.6-luna','anthropic/claude-sonnet-5','minimax/minimax-m3'],timeoutMs:60000};
function validate(value){const url=new URL(value.baseUrl);if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash)throw Error('Use an HTTPS API URL without credentials');if(!Array.isArray(value.models)||!value.models.length||value.models.some(m=>typeof m!=='string'||!m.trim()||m.length>150))throw Error('Specify at least one model');return {...defaults,baseUrl:url.toString().replace(/\/$/,''),models:value.models.map(m=>m.trim()),enabled:value.enabled===true};}
async function read(dir){try{return validate(JSON.parse(await fs.readFile(path.join(dir,'ai.json'),'utf8')));}catch(e){if(e.code==='ENOENT')return {...defaults};throw e;}}
async function save(dir,value){const config=validate(value);await fs.mkdir(dir,{recursive:true});const file=path.join(dir,'ai.json'),tmp=file+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(tmp,JSON.stringify(config,null,2),{mode:0o600});await fs.rename(tmp,file);return config;}
// Invoked by explicit assembly analysis through the main process.
// Caller must explicitly enable a configuration and supply only approved context.
async function chat(config,messages,{apiKey,fetchImpl=fetch}={}){if(!config.enabled)throw Error('AI is disabled');if(!apiKey)throw Error('AI API key is missing');if(!Array.isArray(messages)||!messages.length||messages.some(m=>!['system','user','assistant'].includes(m.role)||typeof m.content!=='string'))throw Error('Invalid AI messages');if(JSON.stringify(messages).length>200000)throw Error('AI context too large');const checked=validate(config);for(let i=0;i<checked.models.length;i++){const response=await fetchImpl(checked.baseUrl+'/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+apiKey,'Content-Type':'application/json'},body:JSON.stringify({model:checked.models[i],messages,stream:false}),signal:AbortSignal.timeout(checked.timeoutMs)});if(!response.ok){if([429,500,502,503,504].includes(response.status)&&i+1<checked.models.length)continue;throw Error('AI request failed (HTTP '+response.status+')');}const data=await response.json(),text=data.choices?.[0]?.message?.content;if(typeof text!=='string')throw Error('AI returned no text');return {text,model:data.model||checked.models[i],usage:data.usage};}throw Error('AI models unavailable');}
async function readKey(dir){if(process.env.WAVESPEED_API_KEY)return process.env.WAVESPEED_API_KEY.trim();try{const data=JSON.parse(await fs.readFile(path.join(dir,'ai-secrets.json'),'utf8'));return typeof data.WAVESPEED_API_KEY==='string'?data.WAVESPEED_API_KEY.trim():'';}catch(e){if(e.code==='ENOENT')return '';throw Error('Cannot read local AI key file');}}
module.exports={read,save,chat,readKey};
