const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..');
const defaults={executable:'/opt/homebrew/bin/z80asm',args:['-L','-o','{output}','{source}']};
const sample="; Пример COM: вывод строки через MSX-DOS\n org 0x100\n; Точка входа программы\nstart:\n ld de,message\n ld c,9\n call 5\n ret\n; Строка для функции DOS 9\nmessage: db 'Hello, MSX-DOS!',13,10,'$'\n";
async function sourceState(dir){
 const files=[];async function walk(folder,prefix=''){let entries;try{entries=await fs.readdir(folder,{withFileTypes:true});}catch(e){if(e.code==='ENOENT')return;throw e;}for(const e of entries){const name=prefix+e.name,full=path.join(folder,e.name);if(e.isDirectory())await walk(full,name+'/');else if(e.isFile()){const bytes=await fs.readFile(full);files.push({name,size:bytes.length,revision:crypto.createHash('sha256').update(bytes).digest('hex')});}}}
 await walk(path.join(dir,'source'));return files.sort((a,b)=>a.name.localeCompare(b.name));
}
function entry(config){const name=config?.entry||'main.asm';if(!/^[a-zA-Z0-9_-]+\.(asm|c|s|bas)$/.test(name))throw Error('Invalid source entry');return name;}
async function read(p){const dir=path.join(ROOT,'projects',p.id);let source,exists=true;try{source=await fs.readFile(path.join(dir,'source',entry(p.compiler)),'utf8');}catch(e){if(e.code!=='ENOENT')throw e;source=sample;exists=false;}return {source,revision:exists?crypto.createHash('sha256').update(source).digest('hex'):null,files:await sourceState(dir),config:p.compiler||defaults};}
function validate(config){if(!config||!path.isAbsolute(config.executable)||!Array.isArray(config.args)||config.args.length>100||config.args.some(a=>typeof a!=='string'||a.length>4096)||!config.args.some(a=>a.includes('{output}')))throw Error('Нужны абсолютный путь компилятора, массив аргументов и {output}');if(config.outputs&&(!Array.isArray(config.outputs)||config.outputs.length>16||config.outputs.some(n=>typeof n!=='string'||!/^[A-Z0-9_]{1,8}\.[A-Z0-9_]{1,3}$/.test(n)||['APP.COM','MSXDOS.SYS','COMMAND.COM','AUTOEXEC.BAT'].includes(n))))throw Error('Invalid compiler outputs');return {executable:config.executable,args:config.args,...(config.outputs?{outputs:config.outputs}:{}),...(config.entry?{entry:entry(config)}:{})};}
async function save(p,{source,config,expectedRevision}){if(p.kind!=='dos')throw Error('Сборка исходников пока доступна для COM');config=validate(config);if(typeof source!=='string'||source.length>1000000)throw Error('Исходник слишком большой');const dir=path.join(ROOT,'projects',p.id);if(expectedRevision!==undefined){const actual=await read(p);if(actual.revision!==expectedRevision)throw Error('Исходник изменён другой программой. Перечитайте файл и разрешите конфликт.');}await fs.mkdir(path.join(dir,'source'),{recursive:true});await fs.writeFile(path.join(dir,'source',entry(config)),source);const next={...p,compiler:config};const file=path.join(dir,'project.json'),tmp=file+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(tmp,JSON.stringify(next,null,2));await fs.rename(tmp,file);return next;}
function run(exe,args,cwd){return new Promise((resolve,reject)=>{const child=spawn(exe,args,{cwd,shell:false,env:{...process.env,PATH:'/opt/homebrew/bin:/usr/local/bin:'+process.env.PATH}});let log='',failure='';const timer=setTimeout(()=>{failure='Сборка превысила 60 секунд';child.kill('SIGKILL');},60000);const append=b=>{log+=b.toString();if(log.length>1000000){failure='Слишком большой журнал сборки';child.kill('SIGKILL');}};child.stdout.on('data',append);child.stderr.on('data',append);child.on('error',e=>{clearTimeout(timer);reject(e);});child.on('close',code=>{clearTimeout(timer);resolve({ok:code===0&&!failure,log:log+(failure?'\n'+failure:''),code});});});}
function symbols(log,source,length){const comments=new Map();let preceding=[];for(const line of source.split(/\r?\n/)){if(/^\s*;/.test(line)){preceding.push(line.replace(/^\s*;\s?/,''));continue;}const m=/^\s*([A-Za-z_.$][\w.$]*):\s*(.*)$/.exec(line);if(m&&!/^equ\b/i.test(m[2]))comments.set(m[1],[...preceding,m[2].split(';').slice(1).join(';').trim()].filter(Boolean).join('\n'));if(line.trim())preceding=[];}
 const result=[];for(const m of log.matchAll(/^([A-Za-z_.$][\w.$]*):\s*equ\s+\$([0-9a-f]+)\s*$/gim)){const address=parseInt(m[2],16);if(!comments.has(m[1])||address<256||address>=256+length)continue;result.push({id:'compiler:'+m[1],name:m[1],address,end:address,space:'cpu',type:'LABEL',comment:comments.get(m[1])||'Метка из исходника; адрес подтверждён компилятором.'});}return result;}
async function build(p,input){p=await save(p,input);const dir=path.join(ROOT,'projects',p.id),work=path.join(dir,'.compile',crypto.randomUUID());await fs.mkdir(work,{recursive:true});try{await fs.cp(path.join(dir,'source'),work,{recursive:true});const output=path.join(work,'APP.COM'),source=path.join(work,entry(p.compiler));const args=p.compiler.args.map(a=>a.replaceAll('{source}',source).replaceAll('{output}',output));let result;try{result=await run(p.compiler.executable,args,work);}catch(e){return {ok:false,log:String(e)};}await fs.mkdir(path.join(dir,'research'),{recursive:true});await fs.writeFile(path.join(dir,'research/last-build.log'),result.log);if(!result.ok)return result;let bytes;try{bytes=await fs.readFile(output);}catch{return {ok:false,log:result.log+'\nКомпилятор не создал {output}.'};}if(!bytes.length||bytes.length>0xff00)return {ok:false,log:result.log+'\nНедопустимый размер COM.'};if(p.compiler.outputs?.length){const extras=(p.launch?.extras||[]).filter(e=>!p.compiler.outputs.includes(e.name));for(const name of p.compiler.outputs)extras.push({name,...await require('./launch.cjs').importFile(dir,path.join(work,name),720*1024)});p={...p,launch:{...p.launch,extras}};}const generated=symbols(result.log,input.source,bytes.length);const manual=p.labels.filter(l=>!l.id.startsWith('compiler:'));const next=await require('./projects.cjs').updateBuild({...p,...(!manual.length?{researchForBuild:crypto.createHash('sha256').update(bytes).digest('hex')}:{}),labels:[...manual,...generated]},output);return {...result,project:next,labels:generated.length};}finally{await fs.rm(work,{recursive:true,force:true});}}
module.exports={read,save,build,symbols};
