const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('desktop',{
 importSource:()=>ipcRenderer.invoke('compiler:import'),
 readCompiler:id=>ipcRenderer.invoke('compiler:read',id),
 saveCompiler:(id,input)=>ipcRenderer.invoke('compiler:save',id,input),
 buildSource:(id,input)=>ipcRenderer.invoke('compiler:build',id,input),
 onRefresh:handler=>{const listener=(_event,shortcut)=>handler(shortcut);ipcRenderer.on('view:refresh',listener);return()=>ipcRenderer.removeListener('view:refresh',listener);},
 analyzeAssembly:text=>ipcRenderer.invoke('ai:assembly',text),
 readAiConfig:()=>ipcRenderer.invoke('ai:read'),
 saveAiConfig:config=>ipcRenderer.invoke('ai:save',config),
 onControl:handler=>{const listener=async(_event,data)=>{try{ipcRenderer.send('control:reply',{id:data.id,result:await handler(data.command,data.args)});}catch(e){ipcRenderer.send('control:reply',{id:data.id,error:e.message});}};ipcRenderer.on('control:request',listener);return()=>ipcRenderer.removeListener('control:request',listener);},
 preferences:ipcRenderer.sendSync('preferences:read'),
 savePreference:async(key,value)=>{const result=ipcRenderer.sendSync('preferences:write-sync',key,value);if(result.error)throw Error(result.error);return true;},
 exportMidi:(id,bytes)=>ipcRenderer.invoke('music:export-midi',id,bytes),
 exportMusic:(id,text)=>ipcRenderer.invoke('music:export',id,text),
 exportLabels:id=>ipcRenderer.invoke('research:export',id),
 archiveLabels:(id,name,text)=>ipcRenderer.invoke('research:archive',id,name,text),
 launchProfile:(id,action,args)=>ipcRenderer.invoke('launch:profile',id,action,args),
 pickLaunchFile:()=>ipcRenderer.invoke('launch:pick'),
 configureLaunch:(id,options)=>ipcRenderer.invoke('launch:configure',id,options),
 listMemoryFiles:(id)=>ipcRenderer.invoke('projects:memoryFiles',id),
 readMemoryFile:(id,path,offset,length)=>ipcRenderer.invoke('projects:memoryBytes',id,path,offset,length),
 listProjectFiles:(id,path='')=>ipcRenderer.invoke('projects:files',id,path),
 revealProjectFile:(id,path)=>ipcRenderer.invoke('projects:reveal',id,path),
 suggestRomName:(id,baseline)=>ipcRenderer.invoke('romVersions:suggest',id,baseline),
 listRomVersions:id=>ipcRenderer.invoke('romVersions:list',id),
 patchRomVersion:(id,name,hash,patches)=>ipcRenderer.invoke('romVersions:patch',id,name,hash,patches),
 saveRomVersion:(id,name,source)=>ipcRenderer.invoke('romVersions:save',id,name,source),
 loadRomVersion:(id,version)=>ipcRenderer.invoke('romVersions:load',id,version),
 setProjectType:(id,kind,source,options)=>ipcRenderer.invoke('projects:type',id,kind,source,options),
 listProjects:()=>ipcRenderer.invoke('projects:list'),
 loadProject:id=>ipcRenderer.invoke('projects:load',id),
 saveProject:(id,data)=>ipcRenderer.invoke('projects:save',id,data),
 listProjectDocuments:id=>ipcRenderer.invoke('projectDocuments:list',id),
 readProjectDocument:(id,path)=>ipcRenderer.invoke('projectDocuments:read',id,path),
 listDocuments:()=>ipcRenderer.invoke('documents:list'),
 readDocument:path=>ipcRenderer.invoke('documents:read',path),
 listSessions:id=>ipcRenderer.invoke('session:list',id),
 saveSession:(id,name,data)=>ipcRenderer.invoke('session:save',id,name,data),
 loadSession:(id,name)=>ipcRenderer.invoke('session:load',id,name),
 capture:(id,data)=>ipcRenderer.invoke('capture:save',id,data),
 importRom:()=>ipcRenderer.invoke('projects:import'),
 engines:()=>ipcRenderer.invoke('engines:list')
});
