import type {Space} from './types';
export interface AssetConfig {source:Space;base:number;end?:number|null;format:'packed'|'planes'|'msx-color'|'sprite16';bpp:number;width:number;height:number;count:number;columns:number;rowStride:number;itemStride:number;colorBase:number;colorMode:'row'|'tile'|'group';foreground:number;background:number;mapBase:number;mapWidth:number;mapHeight:number;mapEntry:'u8'|'u16le'|'u16be';mapOffset:number;firstCode:number;text:string;textSource?:'typed'|'memory';textBase?:number;textLength?:number;charset?:string;view:'atlas'|'map'|'text';}
export interface AssetDefinition {id:string;name:string;config:AssetConfig;colors:string[]}
export const defaultAsset:AssetConfig={source:'vram',base:0,format:'packed',bpp:1,width:8,height:8,count:256,columns:16,rowStride:0,itemStride:0,colorBase:0,colorMode:'row',foreground:15,background:0,mapBase:0,mapWidth:32,mapHeight:24,mapEntry:'u8',mapOffset:0,firstCode:0,text:'MSXLab 0123456789',view:'atlas'};
export function assetGeometry(c:AssetConfig){const row=c.rowStride||Math.ceil(c.width*(c.format==='packed'?c.bpp:1)/8),plane=row*c.height;return {row,plane,item:c.itemStride||(c.format==='sprite16'?32:plane*(c.format==='planes'?c.bpp:1))};}
export function assetPixel(memory:readonly number[],c:AssetConfig,item:number,x:number,y:number):{color:number;address:number;colorAddress?:number}|null{
 if(item<0||item>=c.count||x<0||x>=c.width||y<0||y>=c.height)return null;const g=assetGeometry(c);let address=c.base+item*g.item+y*g.row+Math.floor(x*(c.format==='packed'?c.bpp:1)/8);if(c.format==='sprite16')address=c.base+item*g.item+y+(x>=8?16:0);
 if(address<0||address>=memory.length||(c.end!=null&&address>c.end))return null;let value=0;
 if(c.format==='packed')value=(memory[address]>>(8-c.bpp-(x*c.bpp%8)))&((1<<c.bpp)-1);
 else if(c.format==='planes'){for(let p=0;p<c.bpp;p++){const a=address+p*g.plane;if(a>=memory.length||(c.end!=null&&a>c.end))return null;value|=((memory[a]>>(7-(x%8)))&1)<<p;}}
 else value=(memory[address]>>(7-(x%8)))&1;
 if(c.format==='msx-color'){const colorAddress=c.colorBase+(c.colorMode==='row'?item*c.height+y:c.colorMode==='tile'?item:Math.floor(item/8));if(colorAddress<0||colorAddress>=memory.length)return null;return {address,colorAddress,color:value?memory[colorAddress]>>4:memory[colorAddress]&15};}
 return {address,color:c.bpp===1||c.format==='sprite16'?(value?c.foreground:c.background):value};
}
export function mapItem(memory:readonly number[],c:AssetConfig,x:number,y:number){const size=c.mapEntry==='u8'?1:2,address=c.mapBase+(y*c.mapWidth+x)*size;if(x<0||y<0||x>=c.mapWidth||y>=c.mapHeight||address<0||address+size>memory.length)return null;const value=size===1?memory[address]:c.mapEntry==='u16le'?memory[address]|memory[address+1]<<8:memory[address]<<8|memory[address+1];return {address,item:value-c.mapOffset};}
export function assetDimensions(c:AssetConfig){return c.view==='map'?{width:c.mapWidth*c.width,height:c.mapHeight*c.height}:c.view==='text'?{width:Math.max(1,c.textSource==='memory'?(c.textLength||1):Array.from(c.text).length)*c.width,height:c.height}:{width:c.columns*c.width,height:Math.ceil(c.count/c.columns)*c.height};}
export function assetAt(memory:readonly number[],c:AssetConfig,x:number,y:number){const tx=Math.floor(x/c.width),ty=Math.floor(y/c.height);const map=c.view==='map'?mapItem(memory,c,tx,ty):null;const item=c.view==='map'?map?.item??-1:c.view==='text'?(c.textSource==='memory'?(memory[(c.textBase||0)+tx]??-1)-c.firstCode:c.charset?c.charset.indexOf(Array.from(c.text)[tx]||'\uffff'):(Array.from(c.text)[tx]?.codePointAt(0)??-1)-c.firstCode):ty*c.columns+tx;const pixel=assetPixel(memory,c,item,x%c.width,y%c.height);return pixel?{...pixel,item,mapAddress:map?.address??(c.view==='text'&&c.textSource==='memory'?(c.textBase||0)+tx:undefined)}:null;}
