import {numberSize,type NumberFormat} from './values';
export const searchFormats: NumberFormat[]=['u8','s8','u16le','s16le','u16be','s16be','u32le','s32le','f32le'];
export function memoryRange(length:number,start:number,end:number){if(!Number.isInteger(start)||!Number.isInteger(end)||start<0||end<start||end>=length)throw Error('Range must fit the selected memory space');return {start,end};}
function reader(bytes:number[],format:NumberFormat){if(!searchFormats.includes(format))throw Error('Unknown number format');const view=new DataView(Uint8Array.from(bytes).buffer);return (a:number)=>{switch(format){case'u8':return view.getUint8(a);case's8':return view.getInt8(a);case'u16le':return view.getUint16(a,true);case's16le':return view.getInt16(a,true);case'u16be':return view.getUint16(a,false);case's16be':return view.getInt16(a,false);case'u32le':return view.getUint32(a,true);case's32le':return view.getInt32(a,true);case'f32le':return view.getFloat32(a,true);}};}
export function numericValue(text:string,format:NumberFormat){if(!searchFormats.includes(format))throw Error('Unknown number format');const value=Number(text.trim());if(!text.trim()||!Number.isFinite(value))throw Error('Enter a finite number');const bits=numberSize(format)*8;if(format!=='f32le'&&(!Number.isInteger(value)||value<(format[0]==='s'?-(2**(bits-1)):0)||value>(format[0]==='s'?2**(bits-1)-1:2**bits-1)))throw Error('Number does not fit '+format);if(format==='f32le'&&!Number.isFinite(Math.fround(value)))throw Error('Number does not fit f32le');return format==='f32le'?Math.fround(value):value;}
export function searchMemory(bytes:number[],options:{mode:'hex'|'text'|'number';query:string;start:number;end:number;format:NumberFormat;aligned?:boolean}){
 const {start,end,mode,query,format}=options;memoryRange(bytes.length,start,end);let pattern:(number|null)[]=[];
 if(mode==='hex'){const tokens=query.trim().split(/\s+/);if(!query.trim()||tokens.some(t=>!/^([\da-f]{2}|\?\?)$/i.test(t)))throw Error('Use byte pairs or ?? (for example 3E ?? 32)');pattern=tokens.map(t=>t==='??'?null:parseInt(t,16));}
 else if(mode==='text'){if(!query)throw Error('Enter text');pattern=[...new TextEncoder().encode(query)];}
 else if(mode!=='number')throw Error('Unknown search mode');
 if(pattern.length>1024)throw Error('Search pattern is limited to 1024 bytes');
 const size=mode==='number'?numberSize(format):pattern.length,value=mode==='number'?numericValue(query,format):0,read=mode==='number'?reader(bytes,format):null,step=mode==='number'&&options.aligned?size:1,hits:{address:number;value?:number;bytes:number[]}[]=[];let total=0;
 // Alignment is absolute, not relative to the entered range start.
 for(let a=Math.ceil(start/step)*step;a+size-1<=end;a+=step)if(read?read(a)===value:pattern.every((v,i)=>v===null||bytes[a+i]===v)){total++;if(hits.length<10000)hits.push({address:a,...(read?{value:read(a)}:{}),bytes:bytes.slice(a,a+Math.min(size,16))});}return {matches:hits,total};
}
export type CompareMode='changed'|'same'|'increased'|'decreased'|'equal'|'delta';
export function compareMemory(before:number[],after:number[],options:{start:number;end:number;format:NumberFormat;mode:CompareMode;value?:string;candidates?:number[]|null;aligned?:boolean}){
 const {start,end,format,mode}=options;if(end-start+1>1048576)throw Error('Compare up to 1 MB at a time; narrow the range');memoryRange(before.length,start,end);memoryRange(after.length,start,end);if(!['changed','same','increased','decreased','equal','delta'].includes(mode))throw Error('Unknown comparison');const target=mode==='equal'?numericValue(options.value||'',format):mode==='delta'?Number(options.value):0;if(mode==='delta'&&(!options.value?.trim()||!Number.isFinite(target)))throw Error('Enter a finite signed difference');const a=reader(before,format),b=reader(after,format),size=numberSize(format),step=options.aligned?size:1;
 const results:{address:number;before:number;after:number}[]=[];
 const check=(address:number)=>{if(!Number.isInteger(address)||address<start||address+size-1>end||address%step!==0)return;const before=a(address),after=b(address),match=mode==='changed'?before!==after:mode==='same'?before===after:mode==='increased'?after>before:mode==='decreased'?after<before:mode==='equal'?after===target:after-before===target;if(match){if(results.length>=100000)throw Error('Too many candidates; narrow the range or comparison');results.push({address,before,after});}};
 if(options.candidates)options.candidates.forEach(check);else for(let address=Math.ceil(start/step)*step;address+size-1<=end;address+=step)check(address);return results;
}
