import type {DebuggerBackend,Snapshot,Breakpoint} from './types';
export class MockDebuggerBackend implements DebuggerBackend {
 private listeners=new Set<(s:Snapshot)=>void>();private timer:ReturnType<typeof setInterval>|null=null;private seq=0;private index=0;private running=false;private breaks:Breakpoint[]=[];private memory=Array(65536).fill(0);private trace:Snapshot['trace']=[];
 private a=0;private sp=0xf000;private flags=0;private tracing=false;private until:number|null=null;
 private pcs=[0x8000,0x8002,0x8005,0x8120,0x8121,0x8008];
 constructor(){this.memory.splice(0x8000,11,0x3e,1,0x32,0,0xc0,0xcd,0x20,0x81,0xc3,0,0x80);this.memory.splice(0x8120,2,0x3c,0xc9);}
 private snapshot():Snapshot{const a=this.a;return {seq:++this.seq,status:this.running?'running':'paused',engine:'Demo / Mock backend',registers:{PC:this.pcs[this.index],SP:this.sp,A:a,F:this.flags,B:0,C:0,DE:0xc000,HL:0xc000,IX:0,IY:0,AF2:0,BC2:0,DE2:0,HL2:0,I:0,R:this.index,IM:1,IFF1:0},rom:this.memory.slice(0x8000,0x8200),cpu:[...this.memory],vram:Array.from({length:16384},(_,i)=>(i%8===0||i%8===7)?255:129),vdpRegisters:[0,0,6,0,0,54,7,0xf1],video:{frame:this.seq,line:0},hit:null,trace:[...this.trace],pages:[{start:0,end:16383,slot:'0',format:'Demo BIOS'},{start:16384,end:32767,slot:'1',format:'Demo ROM'},{start:32768,end:49151,slot:'3',format:'Demo code'},{start:49152,end:65535,slot:'3',format:'Demo RAM'}],capabilities:{step:true,stepOver:true,breakpoints:true},lastWrites:[],counts:{},recording:{active:false,replaying:false,events:0,frames:0}};}
 private publish(){const s=this.snapshot();this.listeners.forEach(fn=>fn(s));}
 private step(){const s=this.snapshot();if(this.tracing){const sizes=[2,3,3,1,1,3];this.trace.push({address:s.registers.PC,bytes:this.memory.slice(s.registers.PC,s.registers.PC+sizes[this.index]),registers:s.registers});if(this.trace.length>500)this.trace.shift();}if(this.index===0)this.a=1;else if(this.index===1)this.memory[0xc000]=this.a;else if(this.index===2){this.sp=0xeffe;this.memory[0xeffe]=8;this.memory[0xefff]=0x80;}else if(this.index===3){this.a=(this.a+1)&255;this.flags=this.a===0?64:0;}else if(this.index===4)this.sp=0xf000;this.index=(this.index+1)%this.pcs.length;this.publish();}
 async command<T>(name:string,args?:any):Promise<T>{let result:any=true;if(name==='run'||name==='until'){if(name==='until'){if(!this.pcs.includes(args.address))throw Error('Address is outside the prepared demo');this.until=args.address;}else this.until=null;this.running=true;if(!this.timer)this.timer=setInterval(()=>{this.step();if(this.until===this.pcs[this.index]||this.breaks.some(b=>b.enabled&&b.address===this.pcs[this.index])){this.running=false;clearInterval(this.timer!);this.timer=null;this.publish();}},350);}else if(name==='pause'){this.running=false;if(this.timer)clearInterval(this.timer);this.timer=null;}else if(name==='step'||name==='over'){if(this.running)throw Error('Pause first');const count=name==='over'&&this.index===2?3:1;for(let i=0;i<count;i++)this.step();}else if(name==='breakpoints')this.breaks=args;else if(name==='snapshot')result=this.snapshot();else if(name==='trace'){this.tracing=!!args;this.trace=[];}else throw Error('Not supported by the mock backend');this.publish();return result;}
 subscribe(fn:(s:Snapshot)=>void){this.listeners.add(fn);queueMicrotask(()=>fn(this.snapshot()));return()=>{this.listeners.delete(fn);};}
 dispose(){if(this.timer)clearInterval(this.timer);this.listeners.clear();}
}
