export interface MusicCapture {scoreNotes?:NoteEvent[];source?:string;version:number;chip:string;clock:number;fps:number;frames:number;project:string;build?:string;samples:{frame:number;registers:number[]}[]}
export interface NoteEvent {address?:number;channel:number;start:number;end:number;midi:number|null;volume:number;noise:boolean;envelope:boolean;frequency:number}
export function psgTone(r:number[],channel:number,clock=1789772.5){const period=(r[channel*2]||0)|((r[channel*2+1]||0)&15)<<8,volume=(r[8+channel]||0)&15,envelope=!!((r[8+channel]||0)&16),noise=!((r[7]||0)&(8<<channel)),active=!((r[7]||0)&(1<<channel))&&(volume>0||envelope)&&period>=2,frequency=active?clock/(16*period):0;return {midi:active?Math.round(69+12*Math.log2(frequency/440)):null,volume,noise,envelope,frequency};}
export function noteName(midi:number|null){if(midi===null)return 'Rest';return ['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][((midi%12)+12)%12]+(Math.floor(midi/12)-1);}
export function musicNotes(c:MusicCapture):NoteEvent[]{if(c.scoreNotes)return c.scoreNotes;const result:NoteEvent[]=[];for(let ch=0;ch<3;ch++){let current:NoteEvent|null=null;for(const sample of c.samples){const tone=psgTone(sample.registers,ch,c.clock);if(current&&current.midi===tone.midi&&current.volume===tone.volume&&current.noise===tone.noise&&current.envelope===tone.envelope){current.end=c.frames;continue;}if(current){current.end=sample.frame;if(current.end>current.start)result.push(current);}current={channel:ch,start:sample.frame,end:c.frames,...tone};}if(current&&current.end>current.start)result.push(current);}return result;}
// Quantize absolute boundaries, retaining leading rests and channel alignment.
export function musicMML(c:MusicCapture,tempo:number){const notes=musicNotes(c),unit=c.fps*60/tempo/4;return [0,1,2].map(ch=>{const tokens=['T'+tempo,'L16'],events=notes.filter(n=>n.channel===ch);for(const n of events){const count=Math.max(0,Math.round(n.end/unit)-Math.round(n.start/unit));if(!count)continue;const valid=n.midi!==null&&n.midi>=24&&n.midi<=119;const token=valid?'O'+(Math.floor(n.midi!/12)-1)+' '+['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'][n.midi!%12]:'R';tokens.push('V'+(n.envelope?8:n.volume));for(let i=0;i<count;i++)tokens.push(token);}return tokens.join(' ');});}
export function musicBasic(c:MusicCapture,tempo:number){const notes=musicNotes(c),unit=c.fps*60/tempo/4,total=Math.round(c.frames/unit),voices=[0,1,2].map(ch=>notes.filter(n=>n.channel===ch)),indices=[0,0,0],lines:string[]=['10 REM PSG TRANSCRIPTION - QUANTIZED 1/16, RETRIGGERED NOTES'];for(let start=0;start<total;start+=4){const channels=[0,1,2].map(ch=>{const tokens=['T'+tempo,'L16'];for(let t=start;t<Math.min(total,start+4);t++){while(indices[ch]<voices[ch].length&&Math.round(voices[ch][indices[ch]].end/unit)<=t)indices[ch]++;const candidate=voices[ch][indices[ch]],n=candidate&&Math.round(candidate.start/unit)<=t?candidate:undefined;if(!n||n.midi===null||n.midi<24||n.midi>119){tokens.push('R');continue;}tokens.push('V'+(n.envelope?8:n.volume),'O'+(Math.floor(n.midi/12)-1),['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'][n.midi%12]);}return '"'+tokens.join(' ')+'"';});lines.push((20+start/4*10)+' PLAY '+channels.join(','));}return lines.join('\n');}
export function validMusicCapture(value:unknown):value is MusicCapture{const c=value as MusicCapture;return !!c&&(!c.scoreNotes||(Array.isArray(c.scoreNotes)&&c.scoreNotes.length<=10000&&c.scoreNotes.every(n=>Number.isInteger(n.channel)&&n.channel>=0&&n.channel<3&&Number.isFinite(n.start)&&n.start>=0&&Number.isFinite(n.end)&&n.end>n.start&&n.end<=c.frames&&(n.midi===null||Number.isInteger(n.midi)&&n.midi>=0&&n.midi<=127)&&Number.isFinite(n.frequency)&&n.frequency>=0&&Number.isFinite(n.volume)&&n.volume>=0&&n.volume<=15)))&&c.version===1&&c.chip==='AY-3-8910'&&[50,60].includes(c.fps)&&Number.isFinite(c.clock)&&c.clock>0&&Number.isInteger(c.frames)&&c.frames>=0&&c.frames<=100000&&Array.isArray(c.samples)&&c.samples.length<=7200&&c.samples.every((s,i)=>Number.isInteger(s.frame)&&s.frame>=0&&s.frame<=c.frames&&(!i||s.frame>c.samples[i-1].frame)&&Array.isArray(s.registers)&&s.registers.length===16&&s.registers.every(v=>Number.isInteger(v)&&v>=0&&v<=255));}
