export interface MemorySlotColumn {connector?:string|null;id:string;primary:number;secondary:number|null;expanded:boolean;format:string;kind:'empty'|'ram'|'rom'|'device';size:number;start:number|null;end:number|null;mirrored?:boolean;bankCount?:number;banks?:number[];activePages:number[]}
export interface MemorySlots {primaryConfig:number;columns:MemorySlotColumn[]}
export interface CallTimelineEvent {id:number;parent:number|null;address:number;start:number;end:number|null;depth:number;kind:string;complete:boolean}
export interface CallTimeline {active:boolean;cycles:number;cycleLimit:number;events:CallTimelineEvent[];reason:string;generation:number;unit:string}
export type Space='cpu'|'vram'|'rom';
export interface Registers {PC:number;SP:number;A:number;F:number;B:number;C:number;DE:number;HL:number;IX:number;IY:number;AF2:number;BC2:number;DE2:number;HL2:number;I:number;R:number;IM:number;IFF1:number;[key:string]:unknown}
export interface TraceEntry {kind?:'instruction'|'interrupt';address:number;bytes:number[];registers:Registers}
export interface Watchpoint {space:Space|'io';address:number;end?:number;access:'read'|'write';enabled?:boolean}
export interface MemoryActivity {enabled:boolean;execute:Record<string,number>;read:Record<string,number>;write:Record<string,number>;vramRead:Record<string,number>;vramWrite:Record<string,number>}
export interface Snapshot {memorySlots?:MemorySlots;callTimeline?:CallTimeline;calls?:{totals:Record<string,number>;sites:Record<string,number>;recorded:boolean};activity?:MemoryActivity;sound?:{registers:number[];capturing:boolean;frames:number;samples:number;fps:number};monitoring?:{writes:boolean;profile:boolean;trace:boolean};ioTrace?:{port:number;value:number;access:'read'|'write';pc:number;pcKnown?:boolean}[];recording:{active:boolean;replaying:boolean;events:number;frames:number};lastWrites:{space:Space;address:number;value:number;before:number;pc:number;pcKnown?:boolean}[];counts:Record<string,number>;pages:{start:number;end:number;slot:string;format:string}[];seq:number;status:'running'|'paused';registers:Registers;rom:number[];cpu:number[];vram:number[];vdpRegisters:number[];video:{frame:number;line:number};hit:null|{reason:string;address:number;access?:{space:'cpu'|'vram'|'io';address:number;port?:number;access:'read'|'write';pc:number;pcKnown?:boolean;kind?:'instruction'|'interrupt';before?:number;value:number;after?:number}};trace:TraceEntry[];capabilities:{step:boolean;stepOver:boolean;breakpoints:boolean};engine:string}
export interface MusicBlock {format:string;layout:"streams"|"table";channels:number[];tickRate:number;periodTable:number;romBase:number}
export interface MemoryScope {primary:number;secondary:number|null;bank?:number}
export interface Label {memoryScope?:MemoryScope;textProfile?:import("./textStrings").TextProfile;screen?:import("./screens").ScreenBlock;music?:MusicBlock;id:string;name:string;address:number;end:number;space:Space;type:string;comment:string}
export interface Breakpoint {memoryScope?:MemoryScope;address:number;enabled:boolean;condition?:string}
export interface LaunchResource {path:string;sha256:string}
export interface Project {mapGroups?:Record<string,string>;textProfile?:import("./textStrings").TextProfile;assets?:import("./assets").AssetDefinition[];engineSha256?:string;launchHash?:string;activeLaunchProfile?:string;launchProfiles?:{id:string;name:string;settings:{engine:string;engineSha256?:string;machine:string;launch:Project['launch']}}[];launch?:{dataDisk?:boolean;vdp?:'V9938';mode?:'loader';loaderName?:string;dosSource?:string;template?:LaunchResource;extras:{name:string;path:string;sha256:string}[];dos?:{system:LaunchResource;command:LaunchResource};secondaryRom?:LaunchResource;bootCommand?:string};secondaryRom?:string;buildFiles?:{name:string;size:number;sha256:string}[];version:1;id:string;name:string;kind:string;engine:string;machine:string;researchMismatch?:boolean;researchForBuild?:string;buildSha256?:string;romSha256?:string;rom?:string;program?:string;disk?:string;basicRun?:string;labels:Label[];breakpoints:Breakpoint[];watches:number[];patterns?:{libraryId?:string;id:string;name:string;pattern:string;comment:string;addresses:number[];scanRange?:{start:number;end:number};origin:string}[];watchpoints?:Watchpoint[];resources?:string[]}
export interface DebuggerBackend {command<T=unknown>(command:string,args?:unknown):Promise<T>;subscribe(fn:(snapshot:Snapshot)=>void):()=>void;dispose():void}
export interface RomVersion {id:string;name:string;created:string;size:number;sha256:string;changed:number}
export interface AiConfig {enabled:boolean;baseUrl:string;models:string[];timeoutMs:number}
export interface CompilerConfig {entry?:string;executable:string;args:string[]}
export interface Desktop {importSource():Promise<string|null>;readCompiler(id:string):Promise<{source:string;revision:string|null;files:{name:string;size:number;revision:string}[];config:CompilerConfig}>;saveCompiler(id:string,input:{source:string;config:CompilerConfig;expectedRevision?:string|null}):Promise<Project>;buildSource(id:string,input:{source:string;config:CompilerConfig;expectedRevision?:string|null}):Promise<{ok:boolean;log:string;project?:Project;labels?:number}>;listMemoryFiles(id:string):Promise<{name:string;path:string;size:number}[]>;readMemoryFile(id:string,path:string,offset:number,length:number):Promise<number[]>;onRefresh(handler:(shortcut?:string)=>void):()=>void;analyzeAssembly(text:string):Promise<{text:string}>;suggestRomName(id:string,baseline?:string):Promise<{name:string;description:string;changed:number;mode:string}>;readAiConfig():Promise<AiConfig>;saveAiConfig(config:AiConfig):Promise<AiConfig>;setProjectType(id:string,kind:string,source:string,options?:{machine:string;files:string[]}):Promise<Project>;listRomVersions(id:string):Promise<{activeHash:string;versions:RomVersion[]}>;patchRomVersion(id:string,name:string,hash:string,patches:{offset:number;before:number;value:number}[]):Promise<RomVersion>;saveRomVersion(id:string,name:string,source?:string):Promise<RomVersion>;loadRomVersion(id:string,version:string):Promise<Project>;listProjectFiles(id:string,path:string):Promise<{name:string;path:string;directory:boolean}[]>;revealProjectFile(id:string,path:string):Promise<boolean>;exportMidi(id:string,bytes:number[]):Promise<{name:string;path:string}>;exportMusic(id:string,text:string):Promise<{name:string;path:string}>;launchProfile(id:string,action:string,args:unknown):Promise<Project>;pickLaunchFile():Promise<string|null>;configureLaunch(id:string,options:unknown):Promise<Project>;exportLabels(id:string):Promise<{name:string;path:string}>;archiveLabels(id:string,name:string,text:string):Promise<boolean>;onControl(handler:(command:string,args:any)=>Promise<unknown>):()=>void;preferences:Record<string,string>;savePreference(key:string,value:string):Promise<void>;listProjects():Promise<{id:string;name:string;kind:string}[]>;loadProject(id:string):Promise<Project>;saveProject(id:string,p:Project):Promise<boolean>;listProjectDocuments(id:string):Promise<string[]>;readProjectDocument(id:string,path:string):Promise<string>;listDocuments():Promise<string[]>;readDocument(path:string):Promise<string>;listSessions(id:string):Promise<string[]>;saveSession(id:string,name:string,data:unknown):Promise<string>;loadSession(id:string,name:string):Promise<unknown>;capture(id:string,data:string):Promise<{name:string;path:string}>;importRom():Promise<Project|null>;engines():Promise<unknown>}
declare global {interface Window {desktop?:Desktop}}
