import {t as tr} from '../i18n';
import {BlockNavigation} from './BlockNavigation';
import {useEffect,useRef,useState} from 'react';
import {usePanelSetting} from '../state/panelSettings';
import {useDebugger,select,store,fail,updateProject} from '../state/debugger';
import {assetAt,assetDimensions,assetGeometry,defaultAsset,type AssetConfig} from '../backend/assets';
import {MSX1_PALETTE} from '../backend/graphics';
import {hex} from '../backend/disassemble';
export function AssetViewer({kind,onExpand}:{kind:string;onExpand?:()=>void}){
 const s=useDebugger(),canvas=useRef<HTMLCanvasElement>(null);
 const [legacyBase]=usePanelSetting('base',0),[legacySource]=usePanelSetting<AssetConfig['source']>('source','vram'),[legacyBpp]=usePanelSetting('bpp',1);
 const [legacyLayout]=usePanelSetting('layout','tiles'),[legacyWidth]=usePanelSetting('pixelWidth',128),[legacyHeight]=usePanelSetting('pixelHeight',128),[legacyStride]=usePanelSetting('stride',16),[legacyColumns]=usePanelSetting('columns',32),[legacyPattern]=usePanelSetting('patternBase',0);
 const [legacyEnd]=usePanelSetting<number|null>('blockEnd',null);
 const [config,setConfig]=usePanelSetting<AssetConfig>('assetConfig',{...defaultAsset,base:legacyBase,end:legacyEnd,source:legacySource,bpp:legacyBpp,view:kind==='levelmap'?'map':'atlas',...(kind==='levelmap'?{base:legacyPattern,mapBase:legacyBase,mapWidth:legacyColumns}:{}),...(kind==='bitmap'&&legacyLayout==='linear'?{width:legacyWidth,height:legacyHeight,rowStride:legacyStride,count:1,columns:1}:{})});
 const [colors,setColors]=usePanelSetting('assetColors',MSX1_PALETTE),[zoom,setZoom]=usePanelSetting('assetZoom',2),[grid,setGrid]=usePanelSetting('assetGrid',true);
 const [frozen,setFrozen]=useState<{bytes:number[];source:AssetConfig['source'];session:number}|null>(null);
 const [name,setName]=useState(''),[savedId,setSavedId]=useState(''),[picked,setPicked]=useState<ReturnType<typeof assetAt>>(null);
 const c={...defaultAsset,textBase:0,textLength:32,...config},memory=frozen?.source===c.source&&frozen.session===s.session?frozen.bytes:s.snapshot?.[c.source]||[],rawDimensions=assetDimensions(c),dimensions={width:Math.min(2048,rawDimensions.width),height:Math.min(2048,rawDimensions.height)},geometry=assetGeometry(c);
 useEffect(()=>setFrozen(null),[s.session,c.source]);
 function change(patch:Partial<AssetConfig>){setConfig({...c,...patch});setPicked(null);}
 useEffect(()=>{setSavedId('');setName('');setPicked(null);},[s.project?.id]);
 useEffect(()=>{const el=canvas.current;if(!el)return;el.width=Math.min(2048,dimensions.width);el.height=Math.min(2048,dimensions.height);const ctx=el.getContext('2d')!,data=ctx.createImageData(el.width,el.height);const rgb=colors.map(color=>[parseInt(color.slice(1,3),16),parseInt(color.slice(3,5),16),parseInt(color.slice(5,7),16)]);
 for(let y=0;y<el.height;y++)for(let x=0;x<el.width;x++){const p=assetAt(memory,c,x,y),v=p?rgb[p.color]||[255,0,255]:((x>>2)+(y>>2))%2?[58,62,68]:[35,39,44],i=(y*el.width+x)*4;data.data[i]=v[0];data.data[i+1]=v[1];data.data[i+2]=v[2];data.data[i+3]=255;}ctx.putImageData(data,0,0);
 },[memory,config,colors,dimensions.width,dimensions.height]);
 function numeric(key:keyof AssetConfig,label:string,max:number,min=0){return <label>{label}<input aria-label={label} type="number" min={min} max={max} value={Number(c[key])} onChange={e=>change({[key]:Math.max(min,Math.min(max,Math.floor(Number(e.target.value))||min))})}/></label>;}
 function address(key:'base'|'colorBase'|'mapBase'|'textBase',label:string){const size=key==='base'?(c.end!=null?Math.max(1,c.end-c.base+1):geometry.item*c.count):key==='mapBase'?c.mapWidth*c.mapHeight*(c.mapEntry==='u8'?1:2):key==='textBase'?c.textLength:key==='colorBase'?(c.colorMode==='row'?c.count*c.height:c.colorMode==='group'?Math.ceil(c.count/8):c.count):1;return <><label>{label}<input aria-label={key==='base'?tr("Address"):label} key={key+String(c[key])} defaultValue={hex(c[key]||0)} onBlur={e=>{const v=e.target.value.replace(/^\$/,'').replace(/^0x/i,'');if(/^[\da-f]{1,6}$/i.test(v))change({[key]:parseInt(v,16)});else e.target.value=hex(c[key]||0);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label><BlockNavigation address={c[key]||0} size={size||1} length={memory.length} label={label} onGo={value=>change({[key]:value,...(key==='base'&&c.end!=null?{end:value+size!-1}:{})})}/></>;}
 const presets:{name:string;config:Partial<AssetConfig>}[]=[{name:'Linear bitmap',config:{format:'packed',width:128,height:128,count:1,columns:1,view:'atlas'}},{name:'Font 8×8',config:{format:'packed',bpp:1,width:8,height:8,view:'atlas'}},{name:'Sprite 16×16',config:{format:'sprite16',bpp:1,width:16,height:16,view:'atlas',count:64,columns:8}},{name:'Colour tiles (row)',config:{format:'msx-color',bpp:1,width:8,height:8,colorMode:'row',view:'atlas'}},{name:'Packed 4 bpp',config:{format:'packed',bpp:4,width:8,height:8,view:'atlas'}},{name:'Planar 2 bpp',config:{format:'planes',bpp:2,width:8,height:8,view:'atlas'}},{name:'Level map',config:{view:'map'}},{name:'Text preview',config:{view:'text'}}];
 return <div className="asset-viewer">{c.end!=null&&<div className="panel-tools"><span>{tr("Block $")}{hex(c.base)}–${hex(c.end)} · {Math.max(0,c.end-c.base+1)}{" "}{tr("bytes")}</span><button onClick={()=>change({end:null})}>{tr("Show beyond block")}</button></div>}
 <details open={kind==='assets'?true:undefined}><summary>{tr("Project assets (")}{s.project?.assets?.length||0})</summary><div className="panel-tools"><select aria-label={tr("Saved asset")} value={savedId} onChange={e=>{setSavedId(e.target.value);const a=s.project?.assets?.find(a=>a.id===e.target.value);if(a){setConfig(a.config);setColors(a.colors);setName(a.name);setPicked(null);}}}><option value="">{tr("Choose saved asset…")}</option>{s.project?.assets?.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input aria-label={tr("Asset name")} placeholder={tr("Resource name")} value={name} onChange={e=>setName(e.target.value.slice(0,120))}/><button disabled={!s.project||!name.trim()} onClick={()=>{const id=crypto.randomUUID();updateProject({assets:[...(s.project?.assets||[]),{id,name:name.trim(),config:c,colors}]});setSavedId(id);}}>{tr("Save new")}</button><button disabled={!savedId||!name.trim()} onClick={()=>updateProject({assets:(s.project?.assets||[]).map(a=>a.id===savedId?{...a,name:name.trim(),config:c,colors}:a)})}>{tr("Update")}</button><button disabled={!savedId} onClick={()=>{updateProject({assets:s.project?.assets?.filter(a=>a.id!==savedId)});setSavedId('');}}>{tr("Delete")}</button></div></details>
 <div className="panel-tools">{onExpand&&<button onClick={onExpand}>{tr("Expand / restore")}</button>}<select aria-label={tr("Asset preset")} value="" onChange={e=>{const preset=presets[Number(e.target.value)];if(preset)change({...preset.config,rowStride:0,itemStride:0});}}><option value="">{tr("Format preset…")}</option>{presets.map((p,i)=><option key={p.name} value={i}>{tr(p.name)}</option>)}</select><select aria-label={tr("Graphics source")} value={c.source} onChange={e=>change({source:e.target.value as AssetConfig['source']})}>{['vram','cpu','rom'].map(x=><option key={x} value={x}>{tr({cpu:'CPU — mapped memory',vram:'VRAM — video memory',rom:'ROM — file bytes'}[x]!)}</option>)}</select>{address('base',tr("Pattern address"))}<button onClick={()=>change({base:s.selected,source:s.space})}>{tr("Use selection")}</button><button disabled={!s.snapshot} onClick={()=>setFrozen(frozen?null:{bytes:[...memory],source:c.source,session:s.session})}>{frozen&&frozen.source===c.source&&frozen.session===s.session?tr("Resume live"):tr("Freeze view")}</button><button disabled={!s.snapshot} onClick={()=>{const r=s.snapshot!.vdpRegisters||[],large=!!(r[1]&2);change({source:'vram',base:(r[6]&7)<<11,format:large?'sprite16':'packed',bpp:1,width:large?16:8,height:large?16:8,count:large?64:256,columns:8,rowStride:0,itemStride:0,view:'atlas',end:null});}}>{tr("VDP sprite patterns")}</button><button disabled={!s.snapshot} onClick={()=>{const r=s.snapshot!.vdpRegisters||[];change({source:'vram',base:(r[4]&7)<<11,format:'packed',bpp:1,width:8,height:8,count:256,columns:16,rowStride:0,itemStride:0,view:'atlas',end:null});}}>{tr("VDP font / tiles")}</button></div>
 <div className="panel-tools"><select aria-label={tr("Asset view")} value={c.view} onChange={e=>change({view:e.target.value as AssetConfig['view']})}><option value="atlas">{tr("Atlas")}</option><option value="map">{tr("Level map")}</option><option value="text">{tr("Text")}</option></select><select aria-label={tr("Asset format")} value={c.format} onChange={e=>change({format:e.target.value as AssetConfig['format'],...(e.target.value==='sprite16'?{width:16,height:16,bpp:1}:{}),rowStride:0,itemStride:0})}><option value="packed">{tr("Packed pixels")}</option><option value="planes">{tr("Separate bitplanes")}</option><option value="msx-color">{tr("MSX colour table")}</option><option value="sprite16">{tr("MSX 16×16 sprite")}</option></select>{(c.format==='packed'||c.format==='planes')&&<select aria-label={tr("Bits per pixel")} value={c.bpp} onChange={e=>change({bpp:Number(e.target.value),rowStride:0,itemStride:0})}>{[1,2,4].map(n=><option key={n} value={n}>{tr("{p0} bpp — {p0} bits per pixel, {p1} colours",{p0:n,p1:2**n})}</option>)}</select>}<select aria-label={tr("Asset zoom")} value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[1,2,3,4,6,8].map(n=><option key={n} value={n}>{n}×</option>)}</select><label><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/>{tr("Grid")}</label><button disabled={!s.snapshot||!s.project} onClick={async()=>{try{const result=await window.desktop!.capture(s.project!.id,canvas.current!.toDataURL());store.set({notice:'Resource image saved: '+result.name});}catch(e){fail(e);}}}>PNG</button></div>
 <details><summary>{tr("Dimensions, colours and decoding")}</summary><div className="panel-tools">{c.format!=='sprite16'&&<>{numeric('width',tr("Cell width"),512,1)}{numeric('height',tr("Cell height"),512,1)}</>}{numeric('count',tr("Items"),1024,1)}{numeric('columns',tr("Atlas columns"),32,1)}{numeric('rowStride',tr("Row bytes (0 auto)"),1024)}{numeric('itemStride',tr("Item bytes (0 auto)"),65536)}</div><div className="panel-tools">{numeric('foreground',tr("Ink"),15)}{numeric('background',tr("Paper"),15)}{c.format==='msx-color'&&<>{address('colorBase',tr("Colour address"))}<select aria-label={tr("Colour grouping")} value={c.colorMode} onChange={e=>change({colorMode:e.target.value as AssetConfig['colorMode']})}><option value="row">{tr("One byte per row")}</option><option value="tile">{tr("One byte per tile")}</option><option value="group">{tr("One byte per 8 tiles")}</option></select></>}</div><div className="palette-editor">{colors.map((color,i)=><label key={i}>{i}<input aria-label={tr("Asset colour ")+i} type="color" value={color} onChange={e=>setColors(colors.map((v,j)=>j===i?e.target.value:v))}/></label>)}<button onClick={()=>setColors(MSX1_PALETTE)}>{tr("Reset palette")}</button></div></details>
 {c.view==='map'&&<div className="panel-tools">{address('mapBase',tr("Map address"))}{numeric('mapWidth',tr("Map columns"),64,1)}{numeric('mapHeight',tr("Map rows"),64,1)}{numeric('mapOffset',tr("First tile ID"),65535)}<select aria-label={tr("Map entries")} value={c.mapEntry} onChange={e=>change({mapEntry:e.target.value as AssetConfig['mapEntry']})}><option value="u8">{tr("8 bit IDs")}</option><option value="u16le">{tr("16 bit LE IDs")}</option><option value="u16be">{tr("16 bit BE IDs")}</option></select></div>}
 {(c.view==='text'||kind==='fonts')&&<div className="panel-tools"><select aria-label={tr("Text source")} value={c.textSource||'typed'} onChange={e=>change({textSource:e.target.value as 'typed'|'memory',view:'text'})}><option value="typed">{tr("Typed text")}</option><option value="memory">{tr("Bytes as glyph codes")}</option></select>{c.textSource==='memory'&&<>{address('textBase',tr("Text address"))}{numeric('textLength',tr("Text length"),128,1)}</>}<input className="asset-text" aria-label={tr("Font trial text")} value={c.text} onChange={e=>change({text:e.target.value.slice(0,128),view:'text'})}/>{numeric('firstCode',tr("First character code"),65535)}<input aria-label={tr("Custom character order")} placeholder={tr("Optional characters in glyph order")} value={c.charset||''} onChange={e=>change({charset:e.target.value.slice(0,1024)})}/><span>{tr("Code − first code, or custom character order")}</span></div>}
 <div className="asset-scroll"><div className="asset-image" style={{width:dimensions.width*zoom,height:dimensions.height*zoom}}><canvas ref={canvas} style={{width:dimensions.width*zoom,height:dimensions.height*zoom}} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect(),p=assetAt(memory,c,Math.floor((e.clientX-rect.left)/zoom),Math.floor((e.clientY-rect.top)/zoom));setPicked(p);if(p)select(p.address,c.source);}}/>{grid&&<div className="asset-grid" style={{backgroundSize:`${c.width*zoom}px ${c.height*zoom}px`}}/>}</div></div>
 <div className="panel-tools">{picked?<><span>{tr("Item")}{" "}{picked.item}{" "}{tr("· pixel $")}{hex(picked.address)}{" "}{tr("· colour")}{" "}{picked.color}</span>{picked.mapAddress!==undefined&&<button onClick={()=>select(picked.mapAddress!,c.source)}>{c.view==='text'?tr("Text byte"):tr("Map entry")} ${hex(picked.mapAddress)}</button>}{picked.colorAddress!==undefined&&<button onClick={()=>select(picked.colorAddress!,c.source)}>{tr("Colour byte $")}{hex(picked.colorAddress)}</button>}</>:<span>{tr("Click a pixel → source bytes")}</span>}</div>
 
 <p className="panel-message">{dimensions.width}×{dimensions.height} · {geometry.item}{" "}{tr("bytes/item · preview limited to 2048×2048 · checkerboard = missing data. Raw interpretation; compressed levels need a game-specific decoder. Palette changes affect this view only.")}</p></div>;
}
