import {t as tr} from '../i18n';
import {useEffect} from 'react';
// One delegated tooltip also covers dynamically created panels and disabled buttons.
export function ButtonHints(){useEffect(()=>{const tip=document.createElement('div');tip.className='button-hint';tip.id='msx-button-hint';tip.role='tooltip';tip.hidden=true;document.body.append(tip);let current:HTMLElement|null=null,timer:ReturnType<typeof setTimeout>|undefined;let oldDescription:string|null=null;
 const symbols:Record<string,string>={'×':'Закрыть','+':'Добавить','−':'Уменьшить','-':'Уменьшить','↑':'Предыдущий блок','↓':'Следующий блок','↗':'Перейти к адресу','·':'Установить точку останова','●':'Удалить точку останова','☆':'Добавить в наблюдение'};
 function hide(){clearTimeout(timer);tip.hidden=true;if(current){if(oldDescription===null)current.removeAttribute('aria-describedby');else current.setAttribute('aria-describedby',oldDescription);}current=null;}
 function enter(event:Event){const target=(event.target as Element)?.closest?.('button,[role="button"]') as HTMLElement|null;if(target===current)return;hide();if(!target)return;current=target;oldDescription=target.getAttribute('aria-describedby');const title=target.getAttribute('title');if(title){target.dataset.buttonHint=title;target.removeAttribute('title');}const text=target.dataset.buttonHint||target.getAttribute('aria-label')||target.textContent?.trim()||'';const label=symbols[text]?tr(symbols[text]):text;if(!label)return;timer=setTimeout(()=>{if(!target.isConnected)return;tip.textContent=label;tip.hidden=false;const rect=target.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(rect.left,innerWidth-tip.offsetWidth-8))+'px';tip.style.top=(rect.bottom+8+tip.offsetHeight<innerHeight?rect.bottom+8:Math.max(8,rect.top-tip.offsetHeight-8))+'px';target.setAttribute('aria-describedby',[oldDescription,tip.id].filter(Boolean).join(' '));},1000);}
 function leave(e:MouseEvent){if(current&&!current.contains(e.relatedTarget as Node))hide();}
 document.addEventListener('mouseover',enter);document.addEventListener('mouseout',leave);document.addEventListener('focusin',enter);document.addEventListener('focusout',hide);document.addEventListener('pointerdown',hide,true);document.addEventListener('scroll',hide,true);window.addEventListener('blur',hide);return()=>{hide();tip.remove();document.removeEventListener('mouseover',enter);document.removeEventListener('mouseout',leave);document.removeEventListener('focusin',enter);document.removeEventListener('focusout',hide);document.removeEventListener('pointerdown',hide,true);document.removeEventListener('scroll',hide,true);window.removeEventListener('blur',hide);};},[]);return null;}
