import {t as tr} from '../i18n';
import {command,useDebugger} from '../state/debugger';
import {useMemo,useState} from 'react';
import {Code2,Gamepad2,Box,Music,Image,ChevronDown,ChevronRight,X,Search} from 'lucide-react';
import type {Label} from '../backend/types';
import type {callGraph} from '../backend/callGraph';
import {hex} from '../backend/disassemble';
type Graph=ReturnType<typeof callGraph>;
const areas=[{name:'Код',Icon:Code2},{name:'Управление',Icon:Gamepad2},{name:'Объекты',Icon:Box},{name:'Музыка',Icon:Music},{name:'Графика',Icon:Image}];
function area(l:Label){const n=l.name.toUpperCase();if(/MUSIC|SOUND|PSG|AUDIO|NOTA|NOTE/.test(n))return 3;if(/GFX|VRAM|DRAW|SPRITE|SCREEN|TILE|FONT|PALET|VDP/.test(n))return 4;if(/KEY|INPUT|JOYST|CONTROL|TECLA/.test(n))return 1;if(/PLAYER|PROTA|ENEMY|ACTOR|KNIFE|MOMIA|MUMMY|COLLIS|GEMA|GEM|PYR|LEVEL/.test(n))return 2;return 0;}
function description(l:Label){return l.comment.replace(/^[;\s-]+/gm,'').replace(/\s+/g,' ').trim();}
export function CallMap({labels,graph,onGo,close,embedded=false}:{labels:Label[];graph:Graph;onGo:(l:Label)=>void;close?:()=>void;embedded?:boolean}){
 const state=useDebugger(),calls=state.snapshot?.calls;
 const [columns,setColumns]=useState(8),[range,setRange]=useState<{start:number;end:number;name:string;generated?:boolean}|null>(null);
 const inRange=(l:Label)=>!range||(l.address>=range.start&&l.address<=range.end);
 const cpuLabels=useMemo(()=>labels.filter(l=>l.space==='cpu'),[labels]);
 const bins=useMemo(()=>Array.from({length:128},(_,i)=>{const start=i*512,end=start+511,found=cpuLabels.filter(l=>l.address<=end&&l.end>=start),owner=found.filter(l=>/^(AREA|SECTION)$/.test(l.type)).sort((a,b)=>(a.end-a.address)-(b.end-b.address))[0],item=found.find(l=>l.type==='PROC')||found[0];return {start,end,item,region:owner?{start:owner.address,end:owner.end,name:owner.name,generated:false}:{start:start&0xf000,end:(start&0xf000)+4095,name:'Участок памяти',generated:true}};}),[cpuLabels]);
 const [query,setQuery]=useState(''),[expanded,setExpanded]=useState<Set<string>>(new Set()),[expandAll,setExpandAll]=useState(false);
 const procedures=useMemo(()=>labels.filter(l=>l.space==='cpu'&&l.type==='PROC'&&inRange(l)).sort((a,b)=>a.address-b.address),[labels,range]);
 const roots=useMemo(()=>areas.map((_,a)=>{const members=procedures.filter(l=>area(l)===a),seen=new Set<string>(),result:Label[]=[];
 function visit(l:Label){if(seen.has(l.id))return;seen.add(l.id);for(const e of graph.outgoing.get(l.id)?.values()||[])if(area(e.label)===a&&inRange(e.label))visit(e.label);}
 for(const l of members)if(![...(graph.incoming.get(l.id)?.values()||[])].some(e=>area(e.label)===a&&inRange(e.label))){result.push(l);visit(l);}
 for(const l of members)if(!seen.has(l.id)){result.push(l);visit(l);}return result;}),[procedures,graph,range]);
 const q=query.trim().toLowerCase();
 const lanes=useMemo(()=>{
  const lists=areas.map((_,a)=>q?procedures.filter(l=>area(l)===a&&`${l.name} ${l.comment} ${hex(l.address)}`.toLowerCase().includes(q)):roots[a]);
  const counts=areas.map(()=>1);
  for(let i=5;i<columns;i++){let best=0;for(let a=1;a<5;a++)if(lists[a].length/counts[a]>lists[best].length/counts[best])best=a;counts[best]++;}
  return areas.flatMap((entry,a)=>Array.from({length:counts[a]},(_,part)=>({...entry,a,part,total:counts[a],items:lists[a].slice(Math.ceil(part*lists[a].length/counts[a]),Math.ceil((part+1)*lists[a].length/counts[a]))})));
 },[q,procedures,roots,columns]);

 function node(l:Label,path:string[],lane:number,sites?:number[]){const key=[...path,l.id].join('/'),cycle=path.includes(l.id),edges=[...(graph.outgoing.get(l.id)?.values()||[])].filter(e=>inRange(e.label)),open=!cycle&&path.length<12&&(expanded.has(key)!==(expandAll&&path.length<3)),a=area(l),Icon=areas[a].Icon;const count=calls?.recorded?(sites?sites.reduce((n,pc)=>n+(calls.sites[pc+':'+l.address]||0),0):(calls.totals[l.address]||0)):null;
 return <div className="callmap-node" key={key}><div className="callmap-node-line"><button className="callmap-toggle" title={cycle?tr("Повторный вызов"):open?tr("Свернуть ветку"):tr("Раскрыть вызовы")} aria-expanded={open} disabled={cycle||!edges.length||path.length>=12} onClick={()=>setExpanded(old=>{const next=new Set(old);next.has(key)?next.delete(key):next.add(key);return next;})}>{edges.length?(open?<ChevronDown size={13}/>:<ChevronRight size={13}/>):<span/>}</button><button className={'callmap-card callmap-tone-'+a} onClick={()=>onGo(l)} title={tr("{p0}\n${p1} · {p2} байт\n{p3}\nПерейти к функции",{p0:(l.name),p1:(hex(l.address)),p2:(l.end-l.address+1),p3:(description(l)||tr("Описание не добавлено"))})}><Icon size={20}/><span className="callmap-copy"><strong>{l.name}</strong><span>{description(l)||tr("Описание не добавлено")}</span></span><span className="callmap-meta"><code>${hex(l.address)}</code><b className="callmap-count" title={count===null?tr("Счётчик ещё не записан. Включите запись вызовов"):tr("Выполнено CALL/RST: {p0}{p1}",{p0:(count),p1:(sites?tr(" из этой функции"):tr(" всего"))})}>×{count===null?'—':new Intl.NumberFormat('ru',{notation:'compact',maximumFractionDigits:1}).format(count)}</b><small title={tr("Вызывают: {p0} разных функций. Вызывает: {p1} разных функций. Прямые связи по коду.",{p0:(graph.incoming.get(l.id)?.size||0),p1:(graph.outgoing.get(l.id)?.size||0)})}>← {graph.incoming.get(l.id)?.size||0} · → {graph.outgoing.get(l.id)?.size||0}{cycle?' ↩':''}</small></span></button></div>{open&&<div className="callmap-children">{edges.map(e=>node(e.label,[...path,l.id],lane,e.sites))}</div>}</div>;}
 return <section className={`callmap ${embedded?'callmap-embedded':''}`} role={embedded?'region':'dialog'} aria-label={tr("Дерево вызовов")}><header className="callmap-toolbar"><strong>{tr("Дерево вызовов")}</strong><span className="callmap-mode">{tr("По коду")}</span><button aria-pressed={!!state.snapshot?.monitoring?.profile} title={tr("Считать выполненные CALL/RST. Новая запись обнуляет счётчики")} onClick={()=>{void command('profile',!state.snapshot?.monitoring?.profile);}}>{state.snapshot?.monitoring?.profile?tr("Остановить счётчик"):tr("Записать вызовы")}</button><label><Search size={15}/><input autoFocus={!embedded} aria-label={tr("Поиск функций дерева")} placeholder={tr("Имя, описание или адрес…")} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label={tr("Число колонок дерева")} title={tr("Число колонок дерева")} value={columns} onChange={e=>setColumns(Number(e.target.value))}>{[5,6,8,10].map(n=><option key={n} value={n}>{n}{" "}{tr("колонок")}</option>)}</select><button onClick={()=>{setExpandAll(true);setExpanded(new Set());}} title={tr("Развернуть дерево до трёх уровней")} >{tr("Развернуть")}</button><button onClick={()=>{setExpandAll(false);setExpanded(new Set());}}>{tr("Свернуть")}</button>{close&&<button title={tr("Закрыть дерево")} onClick={close}><X size={18}/></button>}</header><div className="callmap-memory"><div className="program-map-strip" aria-label={tr("Карта памяти дерева функций")}>{bins.map((b,i)=><button key={i} aria-label={tr("${p0}–${p1}",{p0:(hex(b.start)),p1:(hex(b.end))})} aria-pressed={!!range&&b.start<=range.end&&b.end>=range.start} style={{background:!b.item?'#a5adb944':['#72b7ec','#a98aed','#edb275','#bc8ee3','#64be9d'][area(b.item)],opacity:range&&(b.end<range.start||b.start>range.end)?.3:1}} title={tr("${p0}–${p1} · {p2}",{p0:(hex(b.start)),p1:(hex(b.end)),p2:(b.region.generated?tr(b.region.name):b.region.name)})} onClick={()=>setRange(b.region)}/>)}</div><div className="callmap-memory-caption"><span>$0000 — $FFFF</span><span>{range?tr("{p0} · ${p1}–${p2}",{p0:(range.generated?tr(range.name):range.name),p1:(hex(range.start)),p2:(hex(range.end))}):tr("Вся память")} · {procedures.length}{" "}{tr("функций")}</span><button disabled={!range} onClick={()=>setRange(null)}>{tr("Вся память")}</button></div></div><div className="callmap-columns" style={{gridTemplateColumns:`repeat(${columns},minmax(190px,1fr))`}}>{lanes.map(({name,Icon,a,part,total,items})=><section key={`${a}-${part}`} className={'callmap-column callmap-tone-'+a}><header><Icon size={21}/><strong>{tr(name)}{total>1&&<small> {part+1}/{total}</small>}</strong><small>{items.length}{" "}{tr("веток")}</small></header><div className="callmap-scroll">{items.map(l=>node(l,[],a))}{!items.length&&<p>{tr("Функции не найдены")}</p>}</div></section>)}</div><footer>{tr("← сколько функций вызывают · → сколько функций вызывает · связи по коду · × выполнений с начала записи")}</footer></section>;
}
