import {t as tr} from '../i18n';
import {Children,isValidElement,useState,useEffect,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
export function GroupedMemorySelect({value,onChange,children,ariaLabel='Память метки',triggerText}:{value:string;onChange:(value:string)=>void;children:ReactNode;ariaLabel?:string;triggerText?:ReactNode}){
 const [anchor,setAnchor]=useState<{left:number;top:number}|null>(null);
 const groups:{label:string;options:{value:string;text:ReactNode}[]}[]=[];
 function scan(nodes:ReactNode){Children.forEach(nodes,node=>{if(!isValidElement(node))return;const props=node.props as {children:ReactNode;label:string;value:string};if(node.type==='optgroup'){const options:{value:string;text:ReactNode}[]=[];Children.forEach(props.children,child=>{if(isValidElement<any>(child))options.push({value:(child.props as {value:string}).value,text:(child.props as {children:ReactNode;ariaLabel?:string;triggerText?:ReactNode}).children});});groups.push({label:props.label,options});}else if(node.type==='option')groups.push({label:'',options:[{value:props.value,text:props.children}]});});}scan(children);
 useEffect(()=>{if(!anchor)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setAnchor(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[anchor]);
 return <><button type="button" aria-label={tr(ariaLabel)} aria-haspopup="dialog" aria-expanded={!!anchor} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setAnchor(anchor?null:{left:Math.max(8,Math.min(r.left,innerWidth-330)),top:Math.max(8,Math.min(r.bottom+4,innerHeight-420))});}}>{triggerText??groups.flatMap(g=>g.options).find(o=>o.value===value)?.text??value} ▾</button>{anchor&&createPortal(<><div className="memory-source-dismiss" onClick={()=>setAnchor(null)}/><div role="dialog" aria-label={tr(ariaLabel)} className="label-memory-menu" style={anchor}>{groups.map((g,i)=><section key={i}>{g.label&&<h3>{g.label}</h3>}{g.options.map(o=><button type="button" key={o.value} aria-pressed={value===o.value} onClick={()=>{onChange(o.value);setAnchor(null);}}><span>{value===o.value?'✓':''}</span>{o.text}</button>)}</section>)}</div></>,document.body)}</>;
}
