import {message as localizeMessage} from '../i18n';
import {t as tr} from '../i18n';
import {useEffect,useState} from 'react';
import {useDebugger,flushResearch,loadProject,store} from '../state/debugger';
export function LaunchSetup({close}:{close:()=>void}){
 const s=useDebugger(),p=s.project!;const [profileName,setProfileName]=useState('');const [name,setName]=useState(p.name),[machine,setMachine]=useState(p.machine),[vdp,setVdp]=useState(p.launch?.vdp||'auto'),[engine,setEngine]=useState(p.engine),[engines,setEngines]=useState<{id:string;name:string;adapter:string}[]>([]);
 const [files,setFiles]=useState<{name:string;sourcePath:string}[]>([]),[removed,setRemoved]=useState<string[]>([]),[dos,setDos]=useState<'keep'|'default'|'custom'>('keep'),[system,setSystem]=useState(''),[command,setCommand]=useState(''),[rom,setRom]=useState<string|null|undefined>(undefined),[boot,setBoot]=useState(p.launch?.bootCommand||'APP'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{void window.desktop!.engines().then(data=>setEngines((data as {engines:typeof engines}).engines)).catch(e=>setError(String(e)));},[]);
 async function pick(set:(value:string)=>void){try{const path=await window.desktop!.pickLaunchFile();if(path)set(path);}catch(e){setError(String(e));}}
 function current(session:number){if(store.get().project?.id!==p.id||store.get().session!==session)throw Error('Project or launch session changed');}
 async function save(){const session=s.session;setBusy(true);setError('');try{await flushResearch();current(session);await window.desktop!.configureLaunch(p.id,{name,machine,engine,vdp,addFiles:files,removeFiles:removed,...(p.kind==='dos'?{bootCommand:boot}:{}),...(dos==='default'?{dos:null}:dos==='custom'?{dos:{systemPath:system,commandPath:command}}:{}),...(rom!==undefined?{secondaryRom:rom}:{})});current(session);store.set({projects:await window.desktop!.listProjects()});current(session);await loadProject(p.id);close();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 const dirty=vdp!==(p.launch?.vdp||'auto')||name!==p.name||machine!==p.machine||engine!==p.engine||files.length>0||removed.length>0||dos!=='keep'||rom!==undefined||boot!==(p.launch?.bootCommand||'APP');
 async function profile(action:string,args:unknown){const session=s.session;setBusy(true);setError('');try{await flushResearch();current(session);const updated=await window.desktop!.launchProfile(p.id,action,args);current(session);if(action==='apply'){await loadProject(p.id);close();}else{store.set({project:updated});setProfileName('');}}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <div className="modal-shade"><section className="settings-dialog launch-dialog" role="dialog" aria-label={tr("Project launch setup")}><header><h2>{tr("Project launch setup")}</h2><button disabled={busy} onClick={close} aria-label={tr("Close launch setup")}>×</button></header><p>{p.kind.toUpperCase()}{" "}{tr("· Changes rebuild the complete launch bundle and restart this project. Originals stay on disk.")}</p>
 <label>{tr("Project name")}<input aria-label={tr("Project name")} value={name} maxLength={120} onChange={e=>setName(e.target.value)}/></label><div className="launch-grid"><label>{tr("Machine")}<select aria-label={tr("Launch machine")} value={machine} onChange={e=>setMachine(e.target.value)}><option>MSX1E</option><option>MSX1J</option></select></label><label>{tr("Engine")}<select aria-label={tr("Launch engine")} value={engine} onChange={e=>setEngine(e.target.value)}>{!engines.some(e=>e.id===engine)&&<option value={engine}>{engine}</option>}{engines.filter(e=>e.adapter==='webmsx-6.0.8').map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label></div>
 <label>{tr("Видеопроцессор")}<select aria-label={tr("Видеопроцессор")} value={vdp} onChange={e=>setVdp(e.target.value)}><option value="auto">{tr("По модели компьютера")}</option><option value="V9938">Yamaha V9938 · YIS503II</option></select></label>
 <h3>{tr("Saved launch profiles")}</h3><p>{dirty?tr("Apply changes before saving or selecting a profile."):tr("Save the current setup; profiles reuse the latest program build.")}</p><div className="panel-tools"><input aria-label={tr("Launch profile name")} placeholder={tr("Profile name")} value={profileName} onChange={e=>setProfileName(e.target.value)}/><button disabled={busy||dirty||!profileName.trim()} onClick={()=>void profile('save',{name:profileName})}>{tr("Save profile")}</button></div>{p.launchProfiles?.map(item=><div className="panel-tools" key={item.id}><strong>{item.name}{item.id===p.activeLaunchProfile?' ✓':''}</strong><span>{item.settings.machine}</span><button disabled={busy||dirty} aria-label={tr("Apply launch profile ")+item.name} onClick={()=>void profile('apply',{profileId:item.id})}>{tr("Apply & restart")}</button><button disabled={busy||dirty} aria-label={tr("Delete launch profile ")+item.name} onClick={()=>void profile('delete',{profileId:item.id})}>{tr("Delete")}</button></div>)}
 <h3>{tr("Second cartridge")}</h3><div className="panel-tools"><span className="launch-path">{rom===null?tr("None"):rom||p.launch?.secondaryRom?.path||tr("None")}</span><button disabled={busy} onClick={()=>void pick(setRom)}>{tr("Choose ROM…")}</button><button disabled={busy} onClick={()=>setRom(null)}>{tr("Remove ROM")}</button></div>
 {p.kind==='dos'&&<><h3>{tr("DOS environment")}</h3><select aria-label={tr("DOS environment")} value={dos} onChange={e=>setDos(e.target.value as typeof dos)}><option value="keep">{tr("Keep current (")}{p.launch?.dosSource==='custom'?tr("custom project files"):tr("pinned MSX-DOS 1")})</option><option value="default">{tr("Shared MSX-DOS 1")}</option><option value="custom">{tr("Custom compatible DOS files")}</option></select>{dos==='custom'&&<><div className="panel-tools"><span className="launch-path">{system||tr("MSXDOS.SYS")}</span><button onClick={()=>void pick(setSystem)}>{tr("Choose MSXDOS.SYS…")}</button></div><div className="panel-tools"><span className="launch-path">{command||tr("COMMAND.COM")}</span><button onClick={()=>void pick(setCommand)}>{tr("Choose COMMAND.COM…")}</button></div><p>{tr("Use a compatible MSX-DOS 1 pair. DOS 2/Nextor may require other hardware and boot support.")}</p></>}<label>{tr("AUTOEXEC command")}<input aria-label={tr("Boot command")} value={boot} maxLength={120} onChange={e=>setBoot(e.target.value)}/></label></>}
 {p.kind!=='rom'&&<><h3>{tr("Additional disk files")}</h3><p>{tr("Root directory, DOS 8.3 names. APP.COM / APP.BAS and system filenames are reserved.")}</p>{p.launch?.extras.filter(f=>!removed.includes(f.name)).map(f=><div className="panel-tools" key={f.name}><span>{f.name}</span><button onClick={()=>setRemoved([...removed,f.name])}>{tr("Remove")}{" "}{f.name}</button></div>)}{files.map((f,i)=><div className="panel-tools" key={i}><input aria-label={tr("Disk filename ")+(i+1)} value={f.name} onChange={e=>setFiles(files.map((v,j)=>j===i?{...v,name:e.target.value}:v))}/><span className="launch-path">{f.sourcePath}</span><button onClick={()=>setFiles(files.filter((_,j)=>j!==i))}>×</button></div>)}<button disabled={busy} onClick={()=>void pick(sourcePath=>setFiles([...files,{sourcePath,name:sourcePath.split('/').at(-1)!.toUpperCase()}]))}>{tr("Add disk file…")}</button></>}
 {p.buildFiles?.length? <details><summary>{tr("Current disk contents ·")}{" "}{p.buildFiles.length}{" "}{tr("files")}</summary>{p.buildFiles.map(f=><div key={f.name}>{f.name} · {f.size}{" "}{tr("bytes")}</div>)}</details>:null}
 {error&&<p role="alert">{localizeMessage(error)}</p>}<div className="panel-tools"><button disabled={busy||dos==='custom'&&(!system||!command)} onClick={()=>void save()}>{busy?tr("Building…"):tr("Save & restart")}</button><button disabled={busy} onClick={close}>{tr("Cancel")}</button></div></section></div>;
}
