import {message as localizeMessage} from '../i18n';
import {t as tr} from '../i18n';
import {useState} from 'react';
import type {DockviewApi} from 'dockview-react';
const KEY='msxlab.layouts.v1';
type SavedLayout={id:string;name:string;layout:ReturnType<DockviewApi['toJSON']>};
export function Layouts({api,close}:{api:DockviewApi;close:()=>void}){
 const [items,setItems]=useState<SavedLayout[]>(()=>{try{const parsed=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(parsed)?parsed:[];}catch{return [];}});
 const [rename,setRename]=useState<string|null>(null);const [renameValue,setRenameValue]=useState('');
 const [name,setName]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function save(next:SavedLayout[]){setBusy(true);try{const value=JSON.stringify(next);if(value.length>1900000)throw Error('Layout collection is too large; remove unused layouts');await window.desktop?.savePreference(KEY,value);localStorage.setItem(KEY,value);setItems(next);setMessage('Saved');return true;}catch(e){setMessage(e instanceof Error?e.message:'Could not save layouts');return false;}finally{setBusy(false);}}
 function apply(item:SavedLayout){const previous=api.toJSON();try{api.fromJSON(item.layout);setMessage('Applied: '+item.name);}catch{api.fromJSON(previous);setMessage('Could not restore this layout');}}
 return <div className="modal-shade" onClick={close}><section className="settings-dialog layouts-dialog" role="dialog" aria-label={tr("Saved layouts")} onClick={e=>e.stopPropagation()}><header><h2>{tr("Saved layouts")}</h2><button aria-label={tr("Close layouts")} onClick={close}>×</button></header><p>{tr("Save panel positions, sizes, tabs and view settings. Layouts are available across projects; the running game and theme stay unchanged.")}</p><form className="panel-tools" onSubmit={async e=>{e.preventDefault();const title=name.trim();if(!title)return;if(items.some(x=>x.name.toLowerCase()===title.toLowerCase())){setMessage('This name exists. Use Update to replace its layout.');return;}if(await save([...items,{id:crypto.randomUUID(),name:title,layout:api.toJSON()}]))setName('');}}><input aria-label={tr("Layout name")} placeholder={tr("Layout name")} maxLength={80} value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy||!name.trim()} type="submit">{tr("Save current layout")}</button></form><div className="saved-layout-list">{!items.length&&<p>{tr("No named layouts yet.")}</p>}{items.map(item=><div className="panel-tools" key={item.id}>{rename===item.id?<form className="layout-rename" onSubmit={async e=>{e.preventDefault();const next=renameValue.trim();if(!next)return;if(items.some(x=>x.id!==item.id&&x.name.toLowerCase()===next.toLowerCase())){setMessage('This name already exists');return;}if(await save(items.map(x=>x.id===item.id?{...x,name:next}:x)))setRename(null);}}><input aria-label={tr("New layout name")} maxLength={80} value={renameValue} onChange={e=>setRenameValue(e.target.value)}/><button disabled={busy} type="submit">{tr("Rename")}</button><button type="button" onClick={()=>setRename(null)}>{tr("Cancel")}</button></form>:<strong style={{flex:1}}>{item.name}</strong>}<button disabled={busy} onClick={()=>apply(item)} aria-label={tr("Apply layout ")+item.name}>{tr("Apply")}</button><button disabled={busy} onClick={()=>void save(items.map(x=>x.id===item.id?{...x,layout:api.toJSON()}:x))} aria-label={tr("Update layout ")+item.name}>{tr("Update")}</button><button disabled={busy} aria-label={tr("Rename layout ")+item.name} onClick={()=>{setRename(item.id);setRenameValue(item.name);}}>{tr("Rename…")}</button><button disabled={busy} onClick={()=>void save(items.filter(x=>x.id!==item.id))} aria-label={tr("Delete layout ")+item.name}>{tr("Delete")}</button></div>)}</div><p role="status">{localizeMessage(message)}</p></section></div>;
}
