import {message as localizeMessage} from '../i18n';
import {t as tr} from '../i18n';
import {SlotRegions} from './SlotRegions';
import {useEffect,useState} from 'react';
import {Cpu,MemoryStick,Layers,HardDrive,ArrowUpRight} from 'lucide-react';
import {useDebugger,command,select} from '../state/debugger';
import type {MemorySlotColumn} from '../backend/types';
import {hex} from '../backend/disassemble';
export function MemorySlotsPanel(){
 const s=useDebugger(),data=s.snapshot?.memorySlots;
 const groups=[0,1,2,3].map(primary=>({primary,columns:data?.columns.filter(c=>c.primary===primary)||[]}));
 const connector=(columns:MemorySlotColumn[])=>[...new Set(columns.map(c=>c.connector).filter(Boolean))].join(' / ');
 const role=(c:MemorySlotColumn)=>c.kind==='ram'?tr("Оперативная память"):c.format==='DiskPatch'?tr("ROM дискового контроллера"):c.kind==='empty'?tr("Пусто"):c.format==='BIOS'||c.format==='MSX2BIOSExt'?tr("Системная ROM"):c.connector?tr("Разъём ")+c.connector:c.format;
 const tone=(c:MemorySlotColumn)=>c.kind==='empty'?'empty':c.kind==='ram'?'ram':c.format==='BIOS'||c.format==='MSX2BIOSExt'?'bios':c.format==='DiskPatch'?'disk':c.format==='MSXMUSIC'?'device':c.kind==='rom'?'cartridge':'device';
 const name=(c:MemorySlotColumn,p:number)=>c.format==='BIOS'?(p===1?'BASIC ROM':'BIOS ROM'):c.format==='MSX2BIOSExt'?tr("Расширение BIOS"):c.format==='DiskPatch'?tr("Дисковый ROM"):c.format==='MSXMUSIC'?tr("Музыкальный ROM"):c.kind==='ram'?'RAM':c.kind==='rom'?tr("Картридж ROM"):c.kind==='empty'?tr("Нет памяти"):c.format;
 const isEmpty=(c:MemorySlotColumn,p:number)=>c.kind==='empty'||(c.start!==null&&c.end!==null&&(c.start>p*16384+16383||c.end<p*16384));
 const [picked,setPicked]=useState<{id:string;page:number}|null>(null),[bank,setBank]=useState<number|null>(null),[preview,setPreview]=useState<{bytes:number[];address:number}|null>(null),[error,setError]=useState('');
 const slot=data?.columns.find(c=>c.id===picked?.id),page=picked?.page??0,currentBank=slot?.banks?.[page],inspectBank=slot?.bankCount?Math.min(bank??currentBank??0,slot.bankCount-1):undefined;
 useEffect(()=>{setPicked(null);setBank(null);setPreview(null);},[s.session]);
 useEffect(()=>{setPreview(null);setError('');},[slot?.id,page,inspectBank,s.session]);
 useEffect(()=>{let live=true;if(!slot||slot.kind==='empty')return;if(slot.start===null){setError('Диапазон и байты этого устройства требуют отдельного декодера.');return;}void command<{bytes:number[];address:number}>('readSlotMemory',{primary:slot.primary,secondary:slot.secondary,page,bank:inspectBank,length:64}).then(result=>{if(!live)return;if(result)setPreview(result);else setError('Байты этого устройства недоступны для отдельного просмотра.');});return()=>{live=false;};},[slot?.id,page,inspectBank,s.session,s.snapshot?.seq]);
 const Icon=({column}:{column:MemorySlotColumn})=>column.kind==='ram'?<MemoryStick size={19}/>:column.kind==='rom'?<HardDrive size={19}/>:<Layers size={19}/>;
 return <div className="memory-slots-view"><div className="panel-tools"><Cpu size={19}/><strong>{tr("Слоты памяти")}</strong><span className="slots-live">{tr("По текущему подключению CPU")}</span></div><p className="panel-message">{tr("Строка — адресное окно 16 КБ. Колонка — слот или подслот. Цветная рамка и отметка «Видит CPU» показывают подключённую память.")}</p>
 <p className="panel-message">{tr("A и B — разъёмы картриджей: для игр и совместимых расширений, в том числе внешнего контроллера дисковода. Расширенный слот может содержать и RAM, и ROM в разных подслотах.")}</p><div className="slots-legend"><span className="bios">BIOS / BASIC</span><span className="cartridge">{tr("Картридж")}</span><span className="ram">RAM</span><span className="disk">{tr("Дисковый ROM")}</span><span className="device">{tr("Устройство")}</span><span className="active-key">{tr("● Сейчас видит CPU")}</span></div>
 {!data?<p className="panel-message">{tr("Карта слотов появится после подключения эмулятора.")}</p>:<div className="slots-scroll"><table className="slots-table" style={{minWidth:282+(data.columns.length*142)}}>
 <thead><tr className="slots-primary"><th rowSpan={2}>{tr("Адрес CPU")}</th><th rowSpan={2} className="cpu-map-heading"><Cpu size={18}/>{tr("Видит процессор")}</th>{groups.map(g=><th key={g.primary} colSpan={g.columns.length}>{tr("Слот")}{" "}{g.primary}{connector(g.columns)&&<b className="slot-connector">{tr("Разъём")}{" "}{connector(g.columns)}</b>}<small>{g.columns.length>1?tr("Расширенный · 4 подслота"):tr("Основной")}</small></th>)}</tr><tr>{data.columns.map(c=><th key={c.id} className="slots-subheading">{c.secondary!==null?tr("Подслот {p0}",{p0:(c.id)}):tr("Без подслотов")}<small>{role(c)}</small></th>)}</tr></thead>
 <tbody>{[0,1,2,3].map(p=>{const visible=data.columns.find(c=>c.activePages.includes(p));return <tr key={p}>
 <th className="slots-address"><strong>${hex(p*16384)}</strong><small>– ${hex(p*16384+16383)}</small><span>{tr("16 КБ · стр.")}{" "}{p}</span></th>
 <td className="cpu-map-cell"><div className={`cpu-visible ${visible&&!isEmpty(visible,p)?tone(visible):'empty'}`}><strong>{visible&&!isEmpty(visible,p)?name(visible,p):tr("Нет памяти")}</strong><span>{visible?tr("Слот {p0}{p1}",{p0:(visible.id),p1:(visible.connector?' · '+visible.connector:'')}):tr("Не определён")}</span>{visible?.bankCount?<b>{tr("Банк")}{" "}{visible.banks?.[p]}</b>:<small>{tr("Окно")}{" "}{p}</small>}<ArrowUpRight size={16}/></div></td>
 {data.columns.map(c=>{const active=c.activePages.includes(p),empty=isEmpty(c,p);return <td key={c.id}><button className={`slot-cell ${tone(c)} ${active?'mapped':''} ${empty?'empty':''} ${picked?.id===c.id&&picked.page===p?'picked':''}`} aria-label={tr("Слот {p0}, страница {p1}{p2}",{p0:(c.id),p1:(p),p2:(active?tr(", подключён"):'')})} aria-pressed={picked?.id===c.id&&picked.page===p} onClick={()=>{setPicked({id:c.id,page:p});setBank(null);}}><span className="slot-type"><Icon column={c}/>{empty?tr("Нет памяти"):name(c,p)}</span><strong>{c.bankCount&&!empty?tr("Банк {p0}",{p0:(c.banks?.[p])}):empty?'—':c.format==='BIOS'?(p===1?tr("Интерпретатор BASIC"):tr("Системная ROM")):c.kind==='ram'?tr("Оперативная память"):c.mirrored?tr("Зеркало картриджа"):c.format}</strong><small>{c.bankCount?tr("{p0} банков · {p1} КБ",{p0:(c.bankCount),p1:(c.size/1024)}):c.start===null?tr("Область зависит от устройства"):!empty?tr("{p0} КБ в слоте",{p0:(c.size/1024)}):''}</small><SlotRegions labels={s.project?.labels||[]} slot={c} page={p} compact/><span className="slot-active">{active?tr("● Видит CPU"):c.bankCount?tr("Посмотреть банки →"):''}</span></button></td>;})}
 </tr>;})}</tbody></table></div>}

 {slot&&picked&&<section className="slot-detail"><div className="panel-tools"><strong>{tr("Слот")}{" "}{slot.id} · ${hex(page*16384)}–${hex(page*16384+16383)}</strong><span>{slot.connector?tr("Разъём ")+slot.connector+' · ':''}{slot.format}</span>{slot.format==='DiskPatch'&&<span>{tr("ROM контроллера дисковода · отдельный подслот, не RAM")}</span>}{slot.activePages.includes(page)&&(bank===null||bank===currentBank)&&<button onClick={()=>select(page*16384,'cpu')}><ArrowUpRight size={15}/>{tr("К адресу CPU")}</button>}<button onClick={()=>setPicked(null)}>{tr("Закрыть")}</button></div>
 {slot.bankCount&&<><p>{tr("Сейчас выбран банк")}{" "}<b>{currentBank}</b>{tr(". Нажмите другой банк, чтобы посмотреть его содержимое. Подключение в игре не меняется.")}</p><div className="slot-banks">{Array.from({length:slot.bankCount},(_,n)=>{const mapped=slot.banks?.flatMap((b,p)=>b===n&&slot.activePages.includes(p)?[p]:[])||[];return <button key={n} className={n===inspectBank?'selected':''} title={mapped.length?tr("Виден CPU в страницах {p0}",{p0:(mapped.join(', '))}):tr("Не подключён к CPU")} onClick={()=>setBank(n)}><b>{n}</b><SlotRegions labels={s.project?.labels||[]} slot={slot} page={page} bank={n}/><small>{n===currentBank?tr("этот ряд"):mapped.length?tr("CPU: ")+mapped.join(','):tr("доступен")}</small></button>;})}</div></>}
 <p className="panel-message">{tr("Подписи размещения — области AREA проекта с привязкой к слоту и банку. Они описывают исследованное размещение, а не автоматическое распознавание текущих байтов.")}</p><SlotRegions labels={s.project?.labels||[]} slot={slot} page={page} bank={inspectBank}/>{error&&<p>{localizeMessage(error)}</p>}{preview&&<><p className="slot-preview-caption">{tr("Первые")}{" "}{preview.bytes.length}{" "}{tr("байт")}{" "}{slot.bankCount?tr("банка {p0}",{p0:(inspectBank)}):tr("в этом окне")} · HEX</p><pre className="slot-bytes">{Array.from({length:Math.ceil(preview.bytes.length/16)},(_,i)=>`$${hex(preview.address+i*16)}  ${preview.bytes.slice(i*16,i*16+16).map(b=>hex(b,2)).join(' ')}`).join('\n')||tr("В этом окне нет памяти.")}</pre></>}
 </section>}</div>;
}
