import {message as localizeMessage} from '../i18n';
import {t as tr} from '../i18n';
import {decodeMusicBlock} from '../backend/musicBlocks';
import {usePanelSetting} from '../state/panelSettings';
import {musicMidi} from '../backend/midi';
import {useMusicPlayback} from './useMusicPlayback';
import {useEffect,useRef,useState,useMemo} from 'react';
import {useDebugger,command,fail,store,select} from '../state/debugger';
import {musicNotes,musicBasic,validMusicCapture,noteName,psgTone,type MusicCapture} from '../backend/music';
export function MusicPanel({onExpand}:{onExpand?:()=>void}){const [source,setSource]=usePanelSetting('musicSource','capture');const s=useDebugger(),[psgCapture,setCapture]=useState<MusicCapture|null>(null),[tempo,setTempo]=useState(120),[channels,setChannels]=useState([true,true,true]),[busy,setBusy]=useState(false),[files,setFiles]=useState<string[]>([]),[file,setFile]=useState('');const wasRecording=useRef(false),generation=useRef(0);const sound=s.snapshot?.sound;const [blockId,setBlockId]=usePanelSetting('musicBlockId','');const blocks=s.project?.labels.filter(l=>l.type==='MUSIC')||[];const block=blocks.find(l=>l.id===blockId)||blocks[0];
 const score=useMemo(()=>{if(source!=='rom')return {capture:null,error:''};if(!block||!s.snapshot)return {capture:null,error:'Create a Музыка block in Labels'};try{return {capture:decodeMusicBlock(block,s.snapshot,s.project!.id),error:''};}catch(e){return {capture:null,error:String(e)};}},[source,block,s.snapshot?.rom.length,s.session,s.project?.id]);
 const capture=source==='rom'?score.capture:psgCapture,hasMusic=!!capture&&(!!capture.samples.length||!!capture.scoreNotes?.length);const playback=useMusicPlayback(capture,channels);
 useEffect(()=>{generation.current++;setCapture(null);setFile('');setFiles([]);wasRecording.current=false;const g=generation.current;if(s.project)void window.desktop!.listSessions(s.project.id).then(names=>{if(g===generation.current)setFiles(names.filter(n=>n.startsWith('music-')));}).catch(fail);},[s.session]);
 async function read(){const g=generation.current,data=await command<MusicCapture>('musicRead');if(g===generation.current&&data)setCapture(data);}
 useEffect(()=>{if(wasRecording.current&&!sound?.capturing)void read();wasRecording.current=!!sound?.capturing;},[sound?.capturing]);
 async function save(){if(!capture||!s.project)return;try{const g=generation.current,name='music-'+Date.now();await window.desktop!.saveSession(s.project.id,name,{...capture,basic:musicBasic(capture,tempo),tempo});if(g===generation.current){setFiles([...files,name]);setFile(name);}store.set({notice:'Music capture saved in project sessions: '+name});}catch(e){fail(e);}}
 const notes=useMemo(()=>capture?musicNotes(capture):[],[capture]),basic=useMemo(()=>capture?musicBasic(capture,tempo):'',[capture,tempo]),shown=notes.filter(n=>channels[n.channel]),fps=capture?.fps||60;
 const sourceButtons=<div className="panel-tools"><button aria-pressed={source==='capture'} onClick={()=>setSource('capture')}>{tr("PSG capture")}</button><button aria-pressed={source==='rom'} onClick={()=>{playback.stop();setSource('rom');}}>{tr("Ноты из ROM")}</button></div>;

 return <>{sourceButtons}{source==='rom'&&<div className="panel-tools"><select aria-label={tr("ROM melody")} value={block?.id||''} onChange={e=>setBlockId(e.target.value)}>{blocks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><span>{block?.music?.format} · {block?.music?.tickRate}{" "}{tr("ticks/s · configured in Labels")}</span>{score.error&&<span role="alert">{localizeMessage(score.error)}</span>}</div>}<div className="panel-tools">{onExpand&&<button onClick={onExpand}>{tr("Expand / restore")}</button>}<button disabled={busy||!sound||sound.capturing} onClick={async()=>{playback.stop();setBusy(true);try{if(await command('musicStart')!==undefined){setCapture(null);setSource('capture');}}finally{setBusy(false);}}}>{tr("Record PSG")}</button><button disabled={!sound?.capturing} onClick={async()=>{await command('musicStop');await read();}}>{tr("Stop capture")}</button><button disabled={!sound||sound.capturing} onClick={()=>void read()}>{tr("Read capture")}</button><span>{sound?.capturing?tr("Recording"):tr("Stopped")} · {sound?.samples||0}{" "}{tr("frames sampled")}</span></div><p className="panel-message">{tr("Record PSG, then Run / play the game. Captures up to 7200 frame samples. Frame sampling can miss very short notes; this records playback, not the original game score.")}</p>
 <table className="debug-table"><thead><tr><th>{tr("Voice")}</th><th>{tr("Music note")}</th><th>Hz</th><th>{tr("Volume")}</th><th>{tr("Effects")}</th></tr></thead><tbody>{[0,1,2].map(ch=>{const n=psgTone(sound?.registers||[],ch);return <tr key={ch}><td>{'ABC'[ch]}</td><td>{sound?noteName(n.midi):tr("Unavailable")}</td><td>{n.frequency.toFixed(1)}</td><td>{n.volume}</td><td>{n.noise?tr("Noise "):''}{n.envelope?tr("Envelope"):''}</td></tr>;})}</tbody></table>
 <div className="panel-tools">{['A','B','C'].map((name,ch)=><button key={name} aria-label={tr("Channel ")+name} aria-pressed={channels[ch]} style={{color:['#57baff','#e6a5eb','#72d6a2'][ch],opacity:channels[ch]?1:.35,borderColor:channels[ch]?['#57baff','#e6a5eb','#72d6a2'][ch]:undefined}} onClick={()=>setChannels(channels.map((on,i)=>i===ch?!on:on))}>{channels[ch]?'●':'○'} {name}</button>)}<label>{tr("Tempo")}{" "}<input aria-label={tr("Music tempo")} type="number" min={32} max={255} value={tempo} onChange={e=>setTempo(Math.max(32,Math.min(255,Math.floor(Number(e.target.value))||120)))}/></label><button disabled={!hasMusic} onClick={()=>void save()}>{tr("Save music")}</button><button disabled={!hasMusic||!channels.some(Boolean)} title={tr("Export selected channels as MIDI tracks")} onClick={async()=>{if(!capture||!s.project)return;try{const result=await window.desktop!.exportMidi(s.project.id,Array.from(musicMidi(capture,channels)));store.set({notice:'MIDI saved: '+result.path});}catch(e){fail(e);}}}>{tr("Export MIDI")}</button><select aria-label={tr("Saved music")} value={file} onChange={e=>setFile(e.target.value)}><option value="">{tr("Saved captures…")}</option>{files.map(f=><option key={f}>{f}</option>)}</select><button disabled={!file||busy} onClick={async()=>{const g=generation.current;setBusy(true);try{const data=await window.desktop!.loadSession(s.project!.id,file) as MusicCapture;if(!validMusicCapture(data))throw Error('Invalid PSG capture');if(g===generation.current){setCapture(data);setSource('capture');}}catch(e){fail(e);}finally{setBusy(false);}}}>{tr("Load music")}</button></div>
 <div className="panel-tools"><button disabled={!hasMusic||playback.playing||sound?.capturing} onClick={()=>void playback.play().catch(fail)}>{tr("▶ Play")}</button><button disabled={!playback.playing} onClick={playback.pause}>{tr("Ⅱ Pause")}</button><button disabled={!capture} onClick={playback.stop}>{tr("■ Stop")}</button><span>{playback.position.toFixed(1)} / {playback.duration.toFixed(1)}{" "}{tr("s")}</span><input aria-label={tr("Playback position")} type="range" min={0} max={playback.duration||1} step={.01} value={playback.position} onChange={e=>playback.seek(Number(e.target.value))}/></div><p className="panel-message">{tr("Audio preview: selected tone voices. Noise and hardware envelopes are not reproduced exactly. Pause the game to listen without its sound.")}</p><div className="music-roll"><svg width={Math.max(600,Math.min(12000,45+(capture?.frames||0)/fps*60))} height={340} role="img" aria-label={tr("PSG piano roll")} onClick={e=>{const box=e.currentTarget.getBoundingClientRect();playback.seek((e.clientX-box.left-45)/60);}}>{Array.from({length:49},(_,i)=>{const midi=36+i,y=(84-midi)*6;return <g key={midi}><line x1={45} y1={y} x2="100%" y2={y} stroke="currentColor" opacity=".15"/>{midi%12===0&&<text x={2} y={y+9} fill="currentColor" fontSize={10}>{tr(noteName(midi))}</text>}</g>;})}{Array.from({length:Math.min(200,Math.ceil((capture?.frames||0)/fps)+1)},(_,second)=><g key={'time'+second}><line x1={45+second*60} x2={45+second*60} y1={0} y2={294} stroke="currentColor" opacity=".15"/><text x={45+second*60} y={310} fill="currentColor" fontSize={10}>{second}{tr("s")}</text></g>)}{shown.filter(n=>n.midi!==null).map((n,i)=><rect key={i} x={45+n.start/fps*60} y={(84-Math.max(36,Math.min(84,n.midi!)))*6} width={Math.max(1,(n.end-n.start)/fps*60)} height={5} fill={['#57baff','#e6a5eb','#72d6a2'][n.channel]} fillOpacity={.75} onDoubleClick={()=>{if(n.address!==undefined)select(n.address);}}><title>{tr("Channel")}{" "}{'ABC'[n.channel]} · {tr(noteName(n.midi))} · {(n.start/fps).toFixed(3)}–{(n.end/fps).toFixed(3)}{tr("s")}{n.midi!<36||n.midi!>84?tr(" · outside displayed pitch range"):''}</title></rect>)}<line aria-label={tr("Playback cursor")} x1={45+playback.position*60} x2={45+playback.position*60} y1={0} y2={315} stroke="#ffcf57" strokeWidth={2} pointerEvents="none"/></svg></div>
 <details><summary>{tr("Note events (")}{shown.length})</summary><div className="data-scroll"><table className="debug-table"><thead><tr><th>{tr("Channel")}</th><th>{tr("Source address")}</th><th>{tr("Start (s)")}</th><th>{tr("Duration")}</th><th>{tr("Music note")}</th><th>{tr("Noise / envelope")}</th></tr></thead><tbody>{shown.slice(0,1000).map((n,i)=><tr key={i}><td>{'ABC'[n.channel]}</td><td>{n.address!==undefined&&<button onClick={()=>select(n.address!)}>${n.address.toString(16).toUpperCase()}</button>}</td><td>{(n.start/fps).toFixed(3)}</td><td>{((n.end-n.start)/fps).toFixed(3)}</td><td>{tr(noteName(n.midi))}</td><td>{n.noise?tr("Noise "):''}{n.envelope?tr("Envelope"):''}</td></tr>)}</tbody></table></div></details>
 <details><summary>{tr("Music-related project labels")}</summary><div className="panel-tools">{s.project?.labels.filter(l=>l.type.startsWith('PROC')&&/MUSIC|SOUND|NOTE|PSG/.test(l.name)).slice(0,40).map(l=><button key={l.id} onClick={()=>select(l.address,l.space)}>{l.name}</button>)}</div><p className="panel-message">{tr("Project labels for music routines. The ROM source uses the King’s Valley score decoder.")}</p></details><details open><summary>{tr("MSX BASIC · approximate transcription")}</summary><p className="panel-message">{tr("Quantized to sixteenths at the chosen tempo. Notes are retriggered each step; noise, envelopes, vibrato and instruments are not reproduced. Out-of-range pitches become rests. Original PSG registers are retained in the saved capture.")}</p><button disabled={!hasMusic} onClick={async()=>{try{const result=await window.desktop!.exportMusic(s.project!.id,basic);store.set({notice:'BASIC music saved: '+result.name});}catch(e){fail(e);}}}>{tr("Export BASIC")}</button><textarea aria-label={tr("MSX BASIC music")} readOnly value={basic}/></details></>;
}
