import {t as tr} from '../i18n';
import {t,useLanguage} from '../i18n';
import {useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {Minimize2} from 'lucide-react';
const eventName='msxlab:panel-popup';
export function togglePanelPopup(id:string){window.dispatchEvent(new CustomEvent(eventName,{detail:id}));}
export function revealPanel(id:string){requestAnimationFrame(()=>requestAnimationFrame(()=>window.dispatchEvent(new CustomEvent('msxlab:panel-reveal',{detail:id}))));}
export function PanelPopup({id,title,children}:{id:string;title:string;children:ReactNode}){
 useLanguage();
 const [open,setOpen]=useState(false),[host]=useState(()=>{const el=document.createElement('div');el.className='panel-popup-content';return el;});
 const dock=useRef<HTMLDivElement>(null),floating=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDivElement>(null),previous=useRef<HTMLElement|null>(null);
 useEffect(()=>{function toggle(e:Event){const target=(e as CustomEvent<string>).detail;if(target===id){previous.current=document.activeElement as HTMLElement;setOpen(v=>!v);}else setOpen(false);}window.addEventListener(eventName,toggle);return()=>window.removeEventListener(eventName,toggle);},[id]);
 useEffect(()=>{function reveal(e:Event){if((e as CustomEvent<string>).detail!==id){setOpen(false);return;}const target=host;target.scrollIntoView({block:'nearest',inline:'nearest'});document.querySelectorAll('.panel-reveal-highlight').forEach(el=>el.remove());const overlay=document.createElement('div');overlay.className='panel-reveal-highlight';overlay.setAttribute('aria-hidden','true');const rect=target.getBoundingClientRect();Object.assign(overlay.style,{position:'fixed',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',boxSizing:'border-box',border:'4px solid #ffc400',boxShadow:'inset 0 0 18px #ffc40055,0 0 10px #ffc40088',pointerEvents:'none',zIndex:'10000',borderRadius:'4px'});document.body.appendChild(overlay);const animation=overlay.animate([{opacity:1},{opacity:.35,offset:.18},{opacity:1,offset:.36},{opacity:1,offset:.8},{opacity:0}],{duration:3200});animation.onfinish=()=>overlay.remove();}window.addEventListener('msxlab:panel-reveal',reveal);return()=>window.removeEventListener('msxlab:panel-reveal',reveal);},[id,host]);
 useLayoutEffect(()=>{const target=open?floating.current:dock.current;if(target)target.appendChild(host);if(open)dialog.current?.querySelector<HTMLButtonElement>('button')?.focus();else previous.current?.focus();},[open,host]);
 useEffect(()=>{if(!open)return;function key(e:KeyboardEvent){if(document.querySelector('.modal-shade'))return;if(e.key==='Escape'&&!document.querySelector('.modal-shade')){e.preventDefault();e.stopPropagation();setOpen(false);}if(e.key==='Tab'&&dialog.current){const nodes=Array.from(dialog.current.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')).filter(el=>el.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}document.addEventListener('keydown',key,true);return()=>document.removeEventListener('keydown',key,true);},[open]);
 return <><div className="panel-popup-dock" ref={dock}>{open&&<span className="panel-popup-placeholder">{t("Панель открыта в большом окне")}</span>}</div>{createPortal(children,host)}{open&&createPortal(<div className="panel-popup-shade" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}><div ref={dialog} className="panel-popup-window" role="dialog" aria-modal="true" aria-label={tr("Большая панель: ")+title}><header><strong>{title}</strong><button title={tr("Вернуть панель на прежнее место")} aria-label={tr("Вернуть панель на прежнее место")} onClick={()=>setOpen(false)}><Minimize2 size={17}/>{t("Вернуть обратно")}</button></header><div className="panel-popup-slot" ref={floating}/></div></div>,document.body)}</>;
}
