import {t as tr} from '../i18n';
import {callGraph} from '../backend/callGraph';
import {CallMap} from './CallMap';
import {CallTree} from './CallTree';
import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {X,Maximize2,Minimize2,Code2,Database,Image,Music,Layers,MessageSquare,Tag,FolderInput,ChevronDown} from 'lucide-react';
import {useDebugger,updateProject} from '../state/debugger';
import type {Label,Space} from '../backend/types';
import {hex} from '../backend/disassemble';

function category(l:Label){const text=l.name+' '+l.type;if(/MUSIC|SOUND|PSG|AUDIO/i.test(text))return 'Звук и музыка';if(/GFX|SPRITE|FONT|TILE|PALETTE|ANIM|DATA BM/i.test(text))return 'Графика и анимация';if(/LEVEL|PYRAM|PIRAM|SCREEN|MAP|ACTOR|ENEMY|MUMMY/i.test(text))return 'Уровни и объекты';if(/INIT|BOOT|START|RESET/i.test(text))return 'Запуск и инициализация';return null;}
function appearance(l:Label){if(l.type==='PROC')return {kind:'code',title:'Функция',Icon:Code2};if(l.type==='MUSIC')return {kind:'music',title:'Музыка',Icon:Music};if(/SCREEN|DATA BM/.test(l.type))return {kind:'graphics',title:'Графика / уровень',Icon:Image};if(/AREA|SECTION/.test(l.type))return {kind:'area',title:'Область',Icon:Layers};if(l.type==='COMMENT')return {kind:'comment',title:'Комментарий',Icon:MessageSquare};return {kind:'data',title:/DATA/.test(l.type)?'Данные':'Метка',Icon:/DATA/.test(l.type)?Database:Tag};}
function description(l:Label){return l.comment.replace(/^[;\s-]+/gm,'').replace(/\s+/g,' ').trim();}
function color(l?:Label){return !l?'#a5adb933':l.type==='MUSIC'?'#b18bc9':/SCREEN|DATA BM/.test(l.type)?'#65b89c':l.type==='PROC'?'#6bafe0':'#d3b66b';}
export function ProgramMap({close,onGo}:{close:()=>void;onGo:(label:Label)=>void}){
 const s=useDebugger(),[space,setSpace]=useState<Space>('cpu'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[group,setGroup]=useState('all'),[full,setFull]=useState(true),[columns,setColumns]=useState(10),[grouping,setGrouping]=useState('areas');
 const [treeView,setTreeView]=useState(false);
 const [calls,setCalls]=useState<Label|null>(null);
 const [memory]=useState(()=>s.snapshot?.cpu||[]);
 const graph=useMemo(()=>callGraph(memory,s.project?.labels||[]),[memory,s.project?.labels]);
 const [expanded,setExpanded]=useState<string[]>([]);
 const dialog=useRef<HTMLElement>(null),search=useRef<HTMLInputElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;search.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopPropagation();close();}if(e.key==='Tab'){const items=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button,input,select')||[]).filter(n=>!n.hasAttribute('disabled'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[]);
 const labels=useMemo(()=>s.project?.labels.filter(l=>l.space===space).sort((a,b)=>a.address-b.address||a.name.localeCompare(b.name))||[],[s.project?.labels,space]);
 const areas=labels.filter(l=>/^(AREA|SECTION)$/.test(l.type));
 const custom=s.project?.mapGroups||{};
 const groupFor=(l:Label)=>{if(custom[l.id])return custom[l.id];if(grouping==='themes'){const name=category(l);if(name)return name;}const area=areas.filter(a=>a.address<=l.address&&a.end>=l.end).sort((a,b)=>(a.end-a.address)-(b.end-b.address))[0];return area?area.name:`Участок $${hex(l.address&0xf000)}–$${hex((l.address&0xf000)+4095)}`;};
 const groups=[...new Set(labels.map(groupFor))];
 const groupLabel=(name:string)=>Object.values(custom).includes(name)||areas.some(a=>a.name===name)?name:name.startsWith('Участок $')?tr('Участок памяти')+name.slice(7):tr(name);
 const q=query.trim().toLowerCase().replace(/^\$/,'');
 const matches=labels.filter(l=>(!q||`${l.name} ${l.comment} ${hex(l.address)} ${hex(l.end)}`.toLowerCase().includes(q))&&(filter==='all'||filter==='functions'&&l.type==='PROC'||filter==='data'&&/^(DATA|SCREEN|MUSIC)/.test(l.type)||filter==='described'&&!!l.comment.trim()||filter==='empty'&&!l.comment.trim()));
 const owners=useMemo(()=>{const result=new Map<string,string>();const procedures=labels.filter(l=>l.type==='PROC').sort((a,b)=>(a.end-a.address)-(b.end-b.address));for(const l of labels.filter(l=>l.type==='COMMENT')){const parent=procedures.find(p=>p.address<=l.address&&p.end>=l.end);if(parent)result.set(l.id,parent.id);}return result;},[labels]);
 const visibleMatches=matches.filter(l=>query.trim()||filter!=='all'||!owners.has(l.id));
 const shown=visibleMatches.filter(l=>query.trim()||group==='all'||groupFor(l)===group);
 const size=space==='rom'?Math.max(1,s.snapshot?.rom.length||0,...labels.map(l=>l.end+1)):space==='vram'?16384:65536;
 const bins=Array.from({length:128},(_,i)=>{const start=Math.floor(i*size/128),end=Math.floor((i+1)*size/128)-1;const item=labels.filter(l=>l.address<=end&&l.end>=start).sort((a,b)=>(a.end-a.address)-(b.end-b.address))[0];return {start,end,item};});
 function assign(l:Label){const name=window.prompt(tr('Название группы (пустое — автоматическая группировка)'),custom[l.id]||groupFor(l));if(name===null)return;const next={...custom};if(name.trim())next[l.id]=name.trim();else delete next[l.id];updateProject({mapGroups:next});}
 return createPortal(<div className="modal-shade"><section ref={dialog} className={'program-map '+(full?'program-map-full':'')} role="dialog" aria-modal="true" aria-label={tr("Карта программы")}><header><h2>{tr("Карта программы ·")}{" "}{s.project?.name}</h2><button title={full?tr("Уменьшить"):tr("Развернуть")} onClick={()=>setFull(!full)}>{full?<Minimize2 size={18}/>:<Maximize2 size={18}/>}</button><button title={tr("Закрыть")} onClick={close}><X size={20}/></button></header>
 <div className="program-map-tools"><button onClick={()=>setTreeView(true)}>{tr("Дерево вызовов")}</button><label>{tr("Колонки")}{" "}<select aria-label={tr("Колонки карточек")} value={columns} onChange={e=>setColumns(Number(e.target.value))}>{[4,6,8,10].map(n=><option key={n} value={n}>{n}</option>)}</select></label><input ref={search} aria-label={tr("Поиск по карте")} placeholder={tr("Имя, описание или адрес…")} value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label={tr("Память карты")} value={space} onChange={e=>{setSpace(e.target.value as Space);setGroup('all');}}><option value="cpu">{tr("CPU · адреса программы")}</option><option value="rom">{tr("ROM · смещения файла")}</option><option value="vram">{tr("VRAM — video memory")}</option></select><select aria-label={tr("Группировка карты")} value={grouping} onChange={e=>{setGrouping(e.target.value);setGroup('all');}}><option value="areas">{tr("По областям")}</option><option value="themes">{tr("По темам (по именам)")}</option></select><select aria-label={tr("Фильтр карты")} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{tr("Все метки")}</option><option value="functions">{tr("Функции")}</option><option value="data">{tr("Данные")}</option><option value="described">{tr("С описанием")}</option><option value="empty">{tr("Без описания")}</option></select></div>
 <div className="program-map-strip">{bins.map((b,i)=><button key={i} style={{background:color(b.item)}} title={tr("${p0}–${p1} · {p2}",{p0:(hex(b.start)),p1:(hex(b.end)),p2:(b.item?.name||tr("Нет меток"))})} onClick={()=>{setQuery('');setFilter('all');setGroup(b.item?groupFor(b.item):'empty-bin');}}/>)}</div><div className="program-map-legend"><span>$0000 — ${hex(size-1)}</span><span>{tr("Голубой: код · зелёный: графика/уровни · фиолетовый: музыка · жёлтый: данные/метки · серый: нет меток")}</span></div>
 <div className="program-map-body"><nav aria-label={tr("Области программы")}><button className={group==='all'?'selected':''} onClick={()=>{setQuery('');setGroup('all');}}>{tr("Все области")}{" "}<span>{labels.length}</span></button>{groups.map(name=><button key={name} className={group===name?'selected':''} onClick={()=>{setQuery('');setGroup(name);}}>{groupLabel(name)}<span>{visibleMatches.filter(l=>groupFor(l)===name).length}</span></button>)}</nav><div className="program-map-results"><p>{query?tr("Поиск по всем областям"):group==='all'?tr("Все области"):groupLabel(group)} · {shown.length}{" "}{tr("карточек")}</p><div className="program-map-list" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{shown.map(l=>{const {kind,title,Icon}=appearance(l),notes=labels.filter(n=>owners.get(n.id)===l.id),open=expanded.includes(l.id),desc=description(l);return <div className={`program-map-row map-kind-${kind} ${desc?'':'map-undescribed'} ${open?'map-card-expanded':''}`} key={l.id}><button className="map-card-main" onClick={()=>{onGo(l);close();}} title={tr("{p0} · ${p1}–${p2}\n{p3}\nПерейти к метке",{p0:(l.name),p1:(hex(l.address)),p2:(hex(l.end)),p3:(l.comment||tr("Нет описания"))})}><span className="map-card-type"><Icon size={12}/>{tr(title)}</span><strong>{l.name}</strong><span className="map-card-description">{desc||tr("Нет описания")}</span><code>${hex(l.address)} · {l.end-l.address+1}{" "}{tr("б.")}</code></button>{l.type==='PROC'&&<button className="map-call-button" title={tr("Показать дерево вызовов")} onClick={()=>setCalls(l)}>↙ {graph.incoming.get(l.id)?.size||0} · ↗ {graph.outgoing.get(l.id)?.size||0}</button>}<div className="map-card-actions">{notes.length>0&&<button aria-expanded={open} aria-label={tr("Раскрыть комментарии функции")} title={tr("Раскрыть комментарии функции")} onClick={()=>setExpanded(open?expanded.filter(id=>id!==l.id):[...expanded,l.id])}><ChevronDown size={11}/>{notes.length}{" "}{tr("комм.")}</button>}<button title={tr("Изменить группу: ")+groupFor(l)} onClick={()=>assign(l)}><FolderInput size={12}/></button></div>{open&&<div className="map-card-notes">{notes.map(n=><button key={n.id} title={n.name} onClick={()=>{onGo(n);close();}}><code>${hex(n.address)}</code> {description(n)||n.name}</button>)}</div>}</div>;})}</div>{!shown.length&&<p>{tr("В этой области нет подходящих меток. Измените фильтр или выберите другую область.")}</p>}</div></div>
 {treeView&&<CallMap labels={s.project?.labels||[]} graph={graph} close={()=>setTreeView(false)} onGo={l=>{onGo(l);close();}}/>}
 {calls&&<CallTree key={calls.id} root={calls} graph={graph} close={()=>setCalls(null)} onGo={l=>{onGo(l);close();}}/>}
 </section></div>,document.body);
}
