import {t as tr} from '../i18n';
import {useEffect,useMemo,useState} from 'react';
import {useDebugger,select} from '../state/debugger';
import {hex} from '../backend/disassemble';
import {directReferences,researchIndex,type ResearchRow} from '../backend/research';
export function ReferencesPanel(){
 const s=useDebugger();const index=useMemo(()=>researchIndex(s.project?.labels||[]),[s.project?.labels]);const [refs,setRefs]=useState<ResearchRow[]>([]),[scanned,setScanned]=useState(false),[scope,setScope]=useState('all'),[kind,setKind]=useState('all'),[visible,setVisible]=useState(500);
 useEffect(()=>{setRefs([]);setScanned(false);setVisible(500);},[s.project?.id,s.project?.labels]);
 const block=index.procedureAt(s.selected);const start=block?.address??s.selected,end=block?.end??s.selected;
 const rows=refs.filter(r=>(kind==='all'||(kind==='calls'?r.call:!r.call))&&(scope==='all'||(scope==='incoming'?r.target!>=start&&r.target!<=end:r.address>=start&&r.address<=end)));
 return <><div className="panel-tools"><button disabled={!s.snapshot} onClick={()=>{if(s.snapshot){setRefs(directReferences(s.snapshot.cpu,index));setScanned(true);setVisible(500);}}}>{tr("Scan marked procedures")}</button><select aria-label={tr("Reference direction")} value={scope} onChange={e=>setScope(e.target.value)}><option value="all">{tr("All references")}</option><option value="incoming">{tr("To selected block")}</option><option value="outgoing">{tr("From selected block")}</option></select><select aria-label={tr("Reference kind")} value={kind} onChange={e=>setKind(e.target.value)}><option value="all">{tr("Calls + branches")}</option><option value="calls">{tr("Calls only")}</option><option value="branches">{tr("Branches only")}</option></select></div><p className="panel-message">{scanned?tr("{p0} references · captured memory",{p0:(rows.length)}):tr("Scan a memory snapshot to find direct references.")}{scope!=='all'&&<> · {block?.name||'$'+hex(start)}</>}<br/>{tr("Marked code only; data is excluded. Indirect targets are unresolved.")}</p>
 <svg className="call-graph" viewBox={`0 0 500 ${Math.max(80,Math.min(rows.length,16)*32)}`} role="img" aria-label={tr("Direct reference graph")}>{rows.slice(0,16).map((r,i)=><g key={r.address}><path d={`M 145 ${i*32+16} L 330 ${i*32+16}`} stroke="#6398b8" fill="none"/><rect x="10" y={i*32+3} width="135" height="26" rx="3" fill="#31536e" onClick={()=>select(r.address)}/><text x="16" y={i*32+21} fill="white" fontSize="11" onClick={()=>select(r.address)}>{(index.procedureAt(r.address)?.name||hex(r.address)).slice(0,20)}</text><rect x="330" y={i*32+3} width="160" height="26" rx="3" fill="#386b57" onClick={()=>select(r.target!)}/><text x="338" y={i*32+21} fill="white" fontSize="11" onClick={()=>select(r.target!)}>{(index.symbolAt(r.target!)?.name||hex(r.target!)).slice(0,22)}</text></g>)}</svg>
 <div className="data-scroll"><table className="debug-table"><thead><tr><th>{tr("Source / procedure")}</th><th>{tr("Instruction")}</th><th>{tr("Target")}</th></tr></thead><tbody>{rows.slice(0,visible).map(r=><tr key={r.address}><td><button onClick={()=>select(r.address)}>{hex(r.address)} · {index.procedureAt(r.address)?.name}</button></td><td>{r.text}</td><td><button onClick={()=>select(r.target!)}>→ {hex(r.target!)} {index.symbolAt(r.target!)?.name}</button></td></tr>)}</tbody></table>{rows.length>visible&&<button onClick={()=>setVisible(visible+500)}>{tr("Show more references")}</button>}</div></>;
}
