import {t as tr} from '../i18n';
import {AddressBar} from './DebugPanels';
import {BlockNavigation} from './BlockNavigation';
import {usePanelSetting} from '../state/panelSettings';
import {useEffect,useRef,useState} from 'react';
import {useDebugger,select,command,store,updateProject,fail,undoResearch,redoResearch} from '../state/debugger';
import {hex,parseAddress} from '../backend/disassemble';
import type {Space} from '../backend/types';
export {SearchPanel,ComparePanel} from './MemorySearchPanels';
export {WritesPanel} from './WatchpointsPanel';
export function ProfilerPanel(){const s=useDebugger();const counts=Object.entries(s.snapshot?.counts||{}).sort((a,b)=>b[1]-a[1]);return <><div className="panel-tools"><label><input type="checkbox" checked={s.snapshot?.monitoring?.profile||false} onChange={e=>{void command('profile',e.target.checked);}}/>{tr("Записывать число выполнений")}</label></div><p className="panel-message">{counts.length}{" "}{tr("адресов инструкций · число выполнений, не время. Остановка сохраняет результат; новая запись начинает подсчёт заново.")}</p><div className="data-scroll"><table className="debug-table"><tbody>{counts.slice(0,500).map(([a,n])=><tr key={a} onClick={()=>select(Number(a))}><td>{hex(Number(a))}</td><td>{n}</td><td>{s.project?.labels.find(l=>l.address===Number(a))?.name}</td></tr>)}</tbody></table></div></>;}
export {ReferencesPanel} from './ReferencesPanel';
export function HistoryPanel(){const s=useDebugger();const [name,setName]=useState('milestone'),[note,setNote]=useState(''),[versions,setVersions]=useState<string[]>([]);useEffect(()=>{if(s.project)void window.desktop?.listSessions(s.project.id).then(v=>setVersions(v.filter(n=>n.startsWith('research-'))));},[s.project?.id]);return <><div className="panel-tools"><button onClick={undoResearch}>{tr("Undo research")}</button><button onClick={redoResearch}>{tr("Redo")}</button></div><div className="panel-tools"><input aria-label={tr("Research version name")} value={name} onChange={e=>setName(e.target.value)} placeholder={tr("Version name")}/><button onClick={async()=>{try{if(!s.project)return;await window.desktop!.saveSession(s.project.id,'research-'+name,{version:1,note,project:s.project});setVersions((await window.desktop!.listSessions(s.project.id)).filter(n=>n.startsWith('research-')));store.set({notice:'Research version saved'});}catch(e){fail(e);}}}>{tr("Save version")}</button></div><input aria-label={tr("Research version note")} placeholder={tr("Note")} value={note} onChange={e=>setNote(e.target.value)}/><div className="data-scroll">{versions.map(v=><div className="panel-tools" key={v}><span>{v.slice(9)}</span><button onClick={async()=>{try{const data=await window.desktop!.loadSession(s.project!.id,v) as {version:number;project:typeof s.project};if(data.version!==1||data.project?.id!==s.project?.id)throw Error('Version does not belong to this project');updateProject({labels:data.project!.labels,patterns:data.project!.patterns,breakpoints:data.project!.breakpoints,watches:data.project!.watches,watchpoints:data.project!.watchpoints});store.set({notice:'Research version restored; Undo is available'});}catch(e){fail(e);}}}>{tr("Restore")}</button></div>)}</div><p className="panel-message">{tr("Undo/redo: last 50 session edits. Named versions persist on disk. Neither operation rewinds the machine.")}</p><p className="panel-message">{tr("Revision")}{" "}{s.revision} · {s.saved?tr("Saved"):tr("Saving…")}</p></>;}
export function ChartsPanel(){const s=useDebugger();const canvas=useRef<HTMLCanvasElement>(null);const samples=useRef<{seq:number;value:number}[]>([]);const address=s.selected;useEffect(()=>{samples.current=[];},[address,s.session]);useEffect(()=>{if(!s.snapshot)return;samples.current.push({seq:s.snapshot.seq,value:s.snapshot.cpu[address]});if(samples.current.length>200)samples.current.shift();const c=canvas.current;if(!c)return;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#7ebba6';ctx.beginPath();samples.current.forEach((v,i)=>{const x=i/199*c.width,y=c.height-v.value/255*c.height;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();},[s.snapshot,address]);return <><p className="panel-message">CPU {hex(address)}{" "}{tr("· 0–255 · sampled every 300 ms")}</p><canvas ref={canvas} width={600} height={180} className="chart-canvas"/></>;}
export function StructurePanel(){const s=useDebugger();const [schema,setSchema]=usePanelSetting('schema','x:u8\ny:u8\npointer:u16');let offset=s.selected;const fields=schema.split('\n').filter(Boolean).map(line=>{const [name,type]=line.split(':');const size=type==='u16'?2:1;const address=offset;offset+=size;const mem=s.snapshot?.cpu;return {name,type,address,value:mem?(mem[address]||0)+(size===2?(mem[(address+1)&65535]||0)*256:0):null};});return <><AddressBar value={s.selected} onGo={select}><BlockNavigation address={s.selected} size={offset-s.selected} length={s.snapshot?.cpu.length||0} onGo={select} label={tr("запись структуры")}/></AddressBar><textarea aria-label={tr("Structure fields")} className="structure-schema" value={schema} onChange={e=>setSchema(e.target.value)}/><p className="panel-message">{tr("name:u8 or name:u16 · little endian · base")}{" "}{hex(s.selected)}</p><table className="debug-table"><tbody>{fields.map((f,i)=><tr key={i} onClick={()=>select(f.address)}><td>{hex(f.address)}</td><td>{f.name}</td><td>{f.type}</td><td>{f.value}</td></tr>)}</tbody></table></>;}
