import {message as localizeMessage} from '../i18n';
import {t as tr} from '../i18n';
import {useMemo,useState} from 'react';
import {useDebugger,select} from '../state/debugger';
import {decodeRomSong,romSongs,kingsValleyHash} from '../backend/romMusic';
import {hex} from '../backend/disassemble';import {noteName} from '../backend/music';
const colors=['#57baff','#e6a5eb','#72d6a2'];
export function RomMusicViewer(){const s=useDebugger(),[song,setSong]=useState(0),[channels,setChannels]=useState([true,true,true]);const rom=s.snapshot?.rom;const hash=s.project?.romSha256||s.project?.buildSha256;
 const decoded=useMemo(()=>{if(!rom||hash!==kingsValleyHash)return {tracks:[],error:'This decoder requires the verified King’s Valley ROM.'};try{return {tracks:decodeRomSong(rom,romSongs[song].id,romSongs[song].count),error:''};}catch(e){return {tracks:[],error:String(e)};}},[rom,hash,song]);const tracks=decoded.tracks,ticks=Math.max(1,...tracks.map(t=>t.ticks)),notes=tracks.flatMap((t,ch)=>channels[ch]?t.notes.map(n=>({...n,ch})):[]),width=Math.max(700,ticks+60);
 return <><div className="panel-tools"><select aria-label={tr("ROM melody")} value={song} onChange={e=>setSong(Number(e.target.value))}>{romSongs.map((x,i)=><option key={x.id} value={i}>{tr(x.name)}</option>)}</select>{['A','B','C'].map((name,ch)=><button key={name} disabled={ch>=romSongs[song].count} aria-pressed={channels[ch]} style={{color:colors[ch],opacity:channels[ch]?1:.4}} onClick={()=>setChannels(channels.map((v,i)=>i===ch?!v:v))}>{channels[ch]?'●':'○'} {name}</button>)}</div><p className="panel-message">{tr("Notes decoded directly from ROM · time in sound-driver ticks · finite repeats expanded; one pass of infinite loops. Sound effects use a separate format.")}</p>{decoded.error&&<p role="alert">{localizeMessage(decoded.error)}</p>}<div className="panel-tools">{tracks.map((t,ch)=><span key={ch}>{'ABC'[ch]} · <button onClick={()=>select(t.address)}>${hex(t.address)}</button> · {t.ticks}{" "}{tr("ticks ·")}{" "}{localizeMessage(t.end)}</span>)}</div><div className="music-roll"><svg width={width} height={330} aria-label={tr("ROM score")} role="img">{Array.from({length:49},(_,i)=><g key={i}><line x1={50} x2={width} y1={i*6} y2={i*6} stroke="currentColor" opacity={.15}/>{i%12===0&&<text x={0} y={i*6+10} fill="currentColor" fontSize={10}>{tr(noteName(84-i))}</text>}</g>)}{Array.from({length:Math.ceil(ticks/48)+1},(_,i)=><text key={i} x={50+i*48} y={315} fontSize={10} fill="currentColor">{i*48}</text>)}{notes.filter(n=>n.midi!==null).map((n,i)=><rect key={i} x={50+n.start} y={(84-Math.min(84,Math.max(36,n.midi!)))*6} width={Math.max(1,n.duration-1)} height={5} fill={colors[n.ch]} opacity={.8} onClick={()=>select(n.address)} style={{cursor:'pointer'}}><title>{'ABC'[n.ch]} · {tr(noteName(n.midi))} · {n.duration}{" "}{tr("ticks · $")}{hex(n.address)}{" "}{tr("· click to inspect")}</title></rect>)}</svg></div><details open><summary>{tr("Notes and rests ·")}{" "}{notes.length}</summary><div className="data-scroll" style={{maxHeight:260}}><table className="debug-table"><thead><tr><th>{tr("Channel")}</th><th>{tr("ROM address")}</th><th>{tr("Byte")}</th><th>{tr("Music note")}</th><th>{tr("Start")}</th><th>{tr("Duration")}</th></tr></thead><tbody>{notes.sort((a,b)=>a.start-b.start||a.ch-b.ch).map((n,i)=><tr key={i} onClick={()=>select(n.address)}><td>{'ABC'[n.ch]}</td><td>{hex(n.address)}</td><td>{hex(n.byte,2)}</td><td>{tr(noteName(n.midi))}</td><td>{n.start}</td><td>{n.duration}</td></tr>)}</tbody></table></div></details><details><summary>{tr("Commands: tempo, volume, loops")}</summary>{tracks.map((t,ch)=><div key={ch}>{t.commands.map((c,i)=><div key={i}><button onClick={()=>select(c.address)}>{'ABC'[ch]} · ${hex(c.address)}</button> · {c.tick} · {localizeMessage(c.text)}</div>)}</div>)}</details></>;
}
