import {t as tr} from '../i18n';
import {useEffect,useRef,useState} from 'react';
import {watchAddress} from '../backend/watchActions';
import {command,select,store,useDebugger,fail} from '../state/debugger';
import {spriteAttributes,spritePixel,spriteRanges} from '../backend/graphics';
import {hex} from '../backend/disassemble';
import type {Snapshot} from '../backend/types';
export function ScreenInspector({close}:{close:()=>void}){
 const {project,session}=useDebugger();const [data,setData]=useState<{png:string;state:Snapshot;width:number;height:number}|null>(null);const [point,setPoint]=useState<{x:number;y:number}|null>(null);const image=useRef<HTMLImageElement>(null);const [crop,setCrop]=useState<{x:number;y:number;w:number;h:number}|null>(null);const down=useRef<{x:number;y:number}|null>(null);
 useEffect(()=>{let live=true;setData(null);setPoint(null);setCrop(null);(async()=>{await command('pause');for(let i=0;i<30&&live;i++){const result=await command<Snapshot>('snapshot');if(!live)return;if(result?.status==='paused'){const d=await command<any>('inspect');if(live&&d)setData(d);return;}await new Promise(r=>setTimeout(r,50));}})().catch(fail);return()=>{live=false;};},[session]);
 const sprites=data?spriteAttributes(data.state.vram,data.state.vdpRegisters):[];const size=(data?.state.vdpRegisters[1]||0)&2?16:8;const mag=(data?.state.vdpRegisters[1]||0)&1?2:1;
 const hits=point&&data?sprites.filter(sp=>sp.color&&point.x>=sp.x&&point.y>=sp.y&&point.x<sp.x+size*mag&&point.y<sp.y+size*mag&&spritePixel(data.state.vram,data.state.vdpRegisters,sp.pattern,Math.floor((point.x-sp.x)/mag),Math.floor((point.y-sp.y)/mag))):[];
 function coordinates(e:React.PointerEvent<HTMLImageElement>){const r=e.currentTarget.getBoundingClientRect();return {x:Math.max(0,Math.min(data!.width-1,Math.floor((e.clientX-r.left)/r.width*data!.width))),y:Math.max(0,Math.min(data!.height-1,Math.floor((e.clientY-r.top)/r.height*data!.height)))};}
 return <div className="screen-inspector"><div className="panel-tools"><button onClick={close}>{tr("Back to game")}</button><button disabled={!data||!crop} onClick={async()=>{if(!data||!crop||!project||!image.current)return;const c=document.createElement('canvas');c.width=crop.w;c.height=crop.h;c.getContext('2d')!.drawImage(image.current,crop.x,crop.y,crop.w,crop.h,0,0,crop.w,crop.h);const saved=await window.desktop!.capture(project.id,c.toDataURL());store.set({notice:'Saved crop '+saved.name});}}>{tr("Save selection")}</button></div>{data?<><img ref={image} src={data.png} draggable={false} onPointerDown={e=>{down.current=coordinates(e);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={e=>{const end=coordinates(e),start=down.current||end;setCrop({x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),w:Math.abs(end.x-start.x)+1,h:Math.abs(end.y-start.y)+1});setPoint({x:Math.floor(end.x/data.width*272)-8,y:Math.floor(end.y/data.height*208)-8});}}/><p className="panel-message">{tr("Paused MSX1 frame · click to inspect sprites; drag to select a crop.")}{" "}{crop&&tr("{p0}×{p1}",{p0:(crop.w),p1:(crop.h)})}</p>{point&&<div className="data-scroll">{hits.length?hits.map(sp=><div className="panel-tools" key={sp.index}><span>{tr("Sprite")}{" "}{sp.index} ({sp.x},{sp.y})</span><button onClick={()=>select(sp.address,'vram')}>{tr("Attributes")}{" "}{hex(sp.address)}</button><button onClick={()=>select(((data.state.vdpRegisters[6]&7)<<11)+(size===16?sp.pattern&252:sp.pattern)*8,'vram')}>{tr("Pattern")}</button><button onClick={()=>{const range=spriteRanges(data.state.vdpRegisters,sp).attributes;watchAddress(range.address,'vram',range.end);}}>{tr("Watch attributes")}</button><button onClick={()=>{const range=spriteRanges(data.state.vdpRegisters,sp).pattern;watchAddress(range.address,'vram',range.end);}}>{tr("Watch pattern")}</button></div>):<p className="panel-message">{tr("No opaque hardware sprite here; this may be background graphics.")}</p>}</div>}</>:<p className="panel-message">{tr("Taking a paused frame…")}</p>}</div>;
}
