import {message as localizeMessage} from '../i18n';
import {t as tr} from '../i18n';
import type {MemoryScope} from '../backend/types';
import {sameScope,scopeCaption} from '../backend/memoryScope';
import {assemblyContext} from '../backend/assembly-context';
import {Sparkles,Save,Tag} from 'lucide-react';
import {useState,useRef,useLayoutEffect} from 'react';import {createPortal} from 'react-dom';import type {ResearchRow} from '../backend/research';import {hex} from '../backend/disassemble';import {useDebugger,updateProject,store} from '../state/debugger';
export function SelectionActions({rows,memoryScope,onAddLabel}:{rows:ResearchRow[];memoryScope?:MemoryScope;onAddLabel?:()=>void}){const s=useDebugger(),[dialog,setDialog]=useState<null|{kind:'ai'|'pattern';rows:ResearchRow[];project:string;session:number;memoryScope?:MemoryScope}>(null),[text,setText]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const contiguous=rows.every((r,i)=>r.kind==='code'&&(!i||rows[i-1].address+rows[i-1].size===r.address));
 const anchor=useRef<HTMLSpanElement>(null),popup=useRef<HTMLDivElement>(null);
 useLayoutEffect(()=>{const node=anchor.current,scroll=node?.closest('.data-scroll');if(!node||!scroll)return;
 const place=()=>{const menu=popup.current,row=node.closest('tr');if(!menu||!row)return;const bounds=scroll.getBoundingClientRect(),r=row.getBoundingClientRect();const left=Math.max(8,bounds.left+6),right=Math.min(innerWidth-8,bounds.right-6),top=Math.max(8,bounds.top+4),bottom=Math.min(innerHeight-8,bounds.bottom-4);menu.style.maxWidth=Math.max(0,right-left)+'px';menu.style.maxHeight=Math.max(0,bottom-top)+'px';const box=menu.getBoundingClientRect();menu.style.left=Math.max(left,right-box.width)+'px';menu.style.top=Math.max(top,Math.min(r.top,bottom-box.height))+'px';menu.style.visibility=r.bottom<bounds.top||r.top>bounds.bottom?'hidden':'visible';};
 place();const observer=new ResizeObserver(place);observer.observe(scroll);if(popup.current)observer.observe(popup.current);window.addEventListener('resize',place);document.addEventListener('scroll',place,true);return()=>{observer.disconnect();window.removeEventListener('resize',place);document.removeEventListener('scroll',place,true);};},[rows[0]?.address,dialog]);
 async function open(kind:'ai'|'pattern'){if(!s.project)return;const chosen=rows.map(r=>({...r})),project=s.project.id,session=s.session;setError('');setName('Фрагмент '+hex(chosen[0].address));setText(kind==='pattern'?chosen.map(r=>r.text.replaceAll('$','')).join('; '):'');setDialog({kind,rows:chosen,project,session,memoryScope});if(kind==='ai'){setBusy(true);try{const result=await window.desktop!.analyzeAssembly((memoryScope?scopeCaption(memoryScope)+'\n\n':'')+assemblyContext(chosen,memoryScope?s.project.labels.filter(l=>sameScope(l.memoryScope,memoryScope)):s.project.labels,memoryScope?undefined:s.snapshot||undefined));setText(result.text);}catch(e){setError(String(e));}finally{setBusy(false);}}}
 function save(){if(!dialog||!text.trim())return;const current=store.get();if(current.project?.id!==dialog.project||current.session!==dialog.session){setError('Проект или сеанс изменился. Откройте действие заново.');return;}const p=current.project,first=Math.min(...dialog.rows.map(r=>r.address)),last=Math.max(...dialog.rows.map(r=>r.address+r.size-1));if(dialog.kind==='pattern'){const pieces=text.split(';').filter(x=>x.trim());if(!name.trim()||pieces.length>32){setError('Укажите имя и не более 32 инструкций.');return;}updateProject({patterns:[...(p.patterns||[]),{id:crypto.randomUUID(),name:name.trim(),pattern:text.trim(),comment:'',addresses:[],origin:'Created from selection at '+hex(first)}]});}else{const existing=p.labels.find(l=>l.space==='cpu'&&l.address===first&&l.type==='COMMENT'&&sameScope(l.memoryScope,dialog.memoryScope)&&(l.end===first||l.end===last));updateProject({labels:existing?p.labels.map(l=>l.id===existing.id?{...l,end:last,comment:[l.comment,text.trim()].filter(Boolean).join('\n\n')}:l):[...p.labels,{id:crypto.randomUUID(),name:'Comment '+hex(first),type:'COMMENT',space:'cpu',address:first,end:last,memoryScope:dialog.memoryScope,comment:text.trim()}]});}setDialog(null);}
 return <span ref={anchor} className="selection-actions-anchor" onClick={e=>e.stopPropagation()} onMouseDown={e=>e.stopPropagation()}>{createPortal(<div ref={popup} className="selection-action-menu selection-action-overlay" role="menu" aria-label={tr("Действия с выделением")}>{onAddLabel&&<button role="menuitem" onClick={onAddLabel}><Tag size={16} aria-hidden="true"/><span>{tr("Добавить метку…")}</span></button>}<button role="menuitem" onClick={()=>void open('ai')}><Sparkles size={16} aria-hidden="true"/><span>{tr("Проанализировать ИИ")}</span></button><button role="menuitem" disabled={!contiguous||rows.length>32} title={!contiguous?tr("Для шаблона выделите последовательные инструкции"):tr("Создать шаблон из выделенных инструкций, не более 32")} onClick={()=>void open('pattern')}><Save size={16} aria-hidden="true"/><span>{tr("Сохранить как шаблон")}</span></button></div>,document.body)}{dialog&&createPortal(<div className="modal-shade"><section className="settings-dialog selection-dialog" role="dialog" aria-label={dialog.kind==='ai'?tr("Анализ ассемблера"):tr("Новый шаблон")}><h2>{dialog.kind==='ai'?tr("Описание выделенного кода"):tr("Новый шаблон")}</h2><p>{dialog.rows.length}{" "}{tr("строк · $")}{hex(Math.min(...dialog.rows.map(r=>r.address)))}–${hex(Math.max(...dialog.rows.map(r=>r.address+r.size-1)))}</p>{dialog.kind==='pattern'&&<input aria-label={tr("Pattern name")} value={name} onChange={e=>setName(e.target.value)}/>}<textarea aria-label={tr("Selection result")} value={text} disabled={busy} onChange={e=>setText(e.target.value)} placeholder={busy?tr("Анализ…"):dialog.kind==='ai'?tr("Описание кода"):tr("Инструкции через ;")}/>{error&&<p role="alert">{localizeMessage(error)}</p>}<div className="panel-tools"><button disabled={busy||!text.trim()} onClick={save}>{tr("Сохранить")}</button><button onClick={()=>setDialog(null)}>{tr("Отмена")}</button></div></section></div>,document.body)}</span>;
}
