import {t as tr} from '../i18n';
import {useEffect,useState} from 'react';
import {useDebugger,command,store,fail} from '../state/debugger';
import {validateCheckpoint,type Checkpoint} from '../backend/checkpoints';
export function SessionPanel(){
 const s=useDebugger();const [name,setName]=useState('main'),[files,setFiles]=useState<string[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(id:string){const names=(await window.desktop!.listSessions(id)).filter(n=>n==='checkpoint'||n.startsWith('checkpoint-')).sort();if(store.get().project?.id===id){setFiles(names);setSelected(prev=>names.includes(prev)?prev:names[0]||'');}}
 useEffect(()=>{setFiles([]);setSelected('');if(s.project)void refresh(s.project.id).catch(fail);},[s.project?.id]);
 async function save(){if(!s.project)return;setBusy(true);try{if(!/^[A-Za-z0-9_-]{1,64}$/.test(name))throw Error('Use 1–64 letters, digits, hyphens or underscores');const p=s.project,data=await command('saveState');if(data){if(store.get().project?.id!==p.id||store.get().session!==s.session)throw Error('Project or launch session changed');const file='checkpoint-'+name;await window.desktop!.saveSession(p.id,file,{version:1,project:p.id,engine:p.engine,build:p.buildSha256||p.romSha256,launch:p.launchHash||null,createdAt:new Date().toISOString(),state:data});await refresh(p.id);setSelected(file);store.set({notice:'Checkpoint saved: '+name});}}catch(e){fail(e);}finally{setBusy(false);}}
 async function restore(){if(!s.project)return;setBusy(true);try{const p=s.project,data=await window.desktop!.loadSession(p.id,selected) as Checkpoint;validateCheckpoint(data,p);if(store.get().project?.id!==p.id||store.get().session!==s.session)throw Error('Project or launch session changed');const result=await command('loadState',data.state);if(result!==undefined)store.set({notice:'Checkpoint restored: '+selected});}catch(e){fail(e);}finally{setBusy(false);}}
 return <><div className="panel-tools"><input aria-label={tr("Checkpoint name")} value={name} maxLength={64} onChange={e=>setName(e.target.value)}/><button disabled={busy||!s.snapshot} onClick={()=>void save()}>{files.includes('checkpoint-'+name)?tr("Replace checkpoint"):tr("Save checkpoint")}</button></div><div className="panel-tools"><select aria-label={tr("Saved checkpoint")} value={selected} onChange={e=>setSelected(e.target.value)}>{!files.length&&<option value="">{tr("No checkpoints")}</option>}{files.map(f=><option key={f} value={f}>{f.replace(/^checkpoint-/, '')}</option>)}</select><button disabled={busy||!s.snapshot||!selected} onClick={()=>void restore()}>{tr("Restore checkpoint")}</button><button disabled={busy||!s.project} onClick={()=>{if(s.project)void refresh(s.project.id).catch(fail);}}>{tr("Refresh checkpoints")}</button></div><div className="panel-tools"><button onClick={()=>command('recordInput')} disabled={!s.snapshot||s.snapshot.recording.active}>{tr("Record keys")}</button><button onClick={()=>command('stopRecording')} disabled={!s.snapshot?.recording.active}>{tr("Stop recording")}</button><button onClick={()=>command('replayInput')} disabled={!s.snapshot||s.snapshot.recording.active}>{tr("Replay")}</button></div><div className="panel-tools"><button onClick={async()=>{try{if(!s.project)return;const data=await window.desktop!.loadSession(s.project.id,'keyboard-recording');if(await command('importRecording',data)!==undefined)store.set({notice:'Recording loaded'});}catch(e){fail(e);}}}>{tr("Load recording")}</button><button onClick={async()=>{try{const data=await command('exportRecording');if(data&&s.project){await window.desktop!.saveSession(s.project.id,'keyboard-recording',data);store.set({notice:'Keyboard recording saved'});}}catch(e){fail(e);}}}>{tr("Save recording")}</button></div><p className="panel-message">{s.snapshot?.recording.active?tr("Recording"):s.snapshot?.recording.replaying?tr("Replaying"):tr("Idle")} · {s.snapshot?.recording.events||0}{" "}{tr("key events")}</p><p className="panel-message">{tr("Checkpoints and recordings belong to this program and launch setup. Replay restores the starting machine state. Keyboard only; exact determinism is not yet verified.")}</p></>;
}
