import {FolderOpen,Save,Hammer,Play,Settings,LoaderCircle} from 'lucide-react';
import {t as tr} from '../i18n';
import {useEffect,useState,useRef} from 'react';
import {useDebugger,flushResearch,loadProject,store} from '../state/debugger';
export function SourceBuild(){const editor=useRef<HTMLTextAreaElement>(null);const s=useDebugger(),id=s.project!.id;const [source,setSource]=useState(''),[entry,setEntry]=useState('main.asm'),[exe,setExe]=useState(''),[args,setArgs]=useState('[]'),[log,setLog]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[settings,setSettings]=useState(false);
type Disk=Awaited<ReturnType<NonNullable<typeof window.desktop>['readCompiler']>>;
const baseline=useRef<{source:string;revision:string|null}|null>(null),latest=useRef({source,busy});latest.current={source,busy};
const [conflict,setConflict]=useState<Disk|null>(null),[files,setFiles]=useState<Disk['files']>([]);
function accept(v:Disk){baseline.current={source:v.source,revision:v.revision};setSource(v.source);latest.current.source=v.source;setConflict(null);}
useEffect(()=>{let live=true,reading=false;baseline.current=null;setReady(false);setConflict(null);
 async function refresh(){if(reading||latest.current.busy)return;reading=true;try{const v=await window.desktop!.readCompiler(id);if(!live)return;setFiles(v.files);
 if(!baseline.current){accept(v);setEntry(v.config.entry||'main.asm');setExe(v.config.executable);setArgs(JSON.stringify(v.config.args,null,2));setReady(true);}
 else if(v.revision!==baseline.current.revision){if(v.revision!==null&&latest.current.source===baseline.current.source){accept(v);setLog(tr('Исходник обновлён с диска.'));}else setConflict(v);}
 else setConflict(null);
 }catch(e){if(live)setLog(String(e));}finally{reading=false;}}
 void refresh();const timer=setInterval(refresh,1500);window.addEventListener('focus',refresh);return()=>{live=false;clearInterval(timer);window.removeEventListener('focus',refresh);};},[id]);
async function action(build:boolean){setBusy(true);setLog('');const session=s.session;try{const disk=await window.desktop!.readCompiler(id);let buildSource=source;if(baseline.current&&disk.revision!==baseline.current.revision){if(disk.revision===null||source!==baseline.current.source){setConflict(disk);return;}accept(disk);buildSource=disk.source;}if(conflict)return;const expectedRevision=disk.revision;const config={entry,executable:exe,args:JSON.parse(args)};await flushResearch();if(store.get().session!==session)throw Error('Проект изменился');if(build){const result=await window.desktop!.buildSource(id,{source:buildSource,config,expectedRevision});{const saved=await window.desktop!.readCompiler(id);if(saved.source===buildSource)baseline.current={source:buildSource,revision:saved.revision};}setLog(result.log+'\n'+(result.ok?tr('Сборка готова. Импортировано меток: {p0}.',{p0:result.labels}):tr('Сборка не выполнена. Предыдущая программа сохранена.')));if(result.ok&&store.get().session===session)await loadProject(id);}else{await window.desktop!.saveCompiler(id,{source:buildSource,config,expectedRevision});{const saved=await window.desktop!.readCompiler(id);if(saved.source===buildSource)baseline.current={source:buildSource,revision:saved.revision};}setLog(tr('Исходник и настройки сохранены.'));}}catch(e){setLog(String(e));}finally{setBusy(false);}}
useEffect(()=>{const node=editor.current;const build=()=>{if(!busy&&ready)void action(true);};node?.addEventListener('source-build-shortcut',build);return()=>node?.removeEventListener('source-build-shortcut',build);});
return <div className="source-build"><div className="panel-tools source-build-actions"><button title={tr("Открыть исходник…")} aria-label={tr("Открыть исходник…")} disabled={busy||!ready} onClick={async()=>{try{const text=await window.desktop!.importSource();if(text!==null)setSource(text);}catch(e){setLog(String(e));}}}><FolderOpen size={18}/></button><button title={tr("Сохранить исходник")} aria-label={tr("Сохранить исходник")} disabled={busy||!ready} onClick={()=>void action(false)}><Save size={18}/></button><button className="source-build-run" title={tr("Скомпилировать и запустить")+" (⌘R)"} aria-label={tr("Скомпилировать и запустить")} aria-busy={busy} disabled={busy||!ready} onClick={()=>void action(true)}>{busy?<LoaderCircle size={18}/>:<><Hammer size={18}/><Play size={13}/></>}</button><button title={tr("Настройки компиляции")} aria-label={tr("Настройки компиляции")} aria-expanded={settings} onClick={()=>setSettings(!settings)}><Settings size={18}/></button></div>{conflict&&<div className="project-warning" role="alert"><p>{conflict.revision===null?'Исходник удалён с диска.':'Исходник изменён и в редакторе, и на диске.'}</p><button disabled={conflict.revision===null} onClick={()=>accept(conflict)}>Принять с диска</button><button onClick={()=>{baseline.current={source:conflict.source,revision:conflict.revision};setConflict(null);}}>Оставить мой текст</button><small>Сборка продолжится после выбора версии и повторного нажатия.</small></div>}{settings&&<div className="source-build-settings"><label>{tr("Компилятор")}<input aria-label={tr("Компилятор")} value={exe} disabled={busy} onChange={e=>setExe(e.target.value)}/></label><label>{tr("Аргументы (JSON-массив)")}<textarea aria-label={tr("Аргументы компилятора")} value={args} disabled={busy} onChange={e=>setArgs(e.target.value)}/></label><p>{tr("{source} — главный исходник, {output} — новый COM. Команда запускается без оболочки. Импорт меток сейчас поддерживает вывод z80asm -L; другие компиляторы могут собирать COM без импорта.")}</p></div>}<p className="panel-message">source/{entry} · COM по $0100</p><details className="source-file-list"><summary>Файлы исходников · {files.length}</summary>{files.map(f=><div key={f.name}>{f.name} · {f.size} байт</div>)}</details><textarea ref={editor} onKeyDown={e=>{if(e.metaKey&&!e.ctrlKey&&!e.altKey&&!e.shiftKey&&e.code==='KeyR'){e.preventDefault();e.stopPropagation();if(!e.repeat&&!busy&&ready)void action(true);}}} className="source-editor" aria-label={tr("Исходный код")} spellCheck={false} disabled={busy||!ready} value={source} onChange={e=>setSource(e.target.value)}/>{log&&<pre className="build-log" role="status">{log}</pre>}</div>;}
