import {t as tr} from '../i18n';
import {useEffect,useRef,useState} from 'react';
import {titleSymbolAddresses as symbolAddresses,type TitleScreen,type TitleSource} from '../backend/titleScreens';
import {MSX1_PALETTE} from '../backend/graphics';
import {hex} from '../backend/disassemble';
import {select} from '../state/debugger';

function Atlas({screen,section,codes,mode,onPick}:{screen:TitleScreen;section:number;codes:number[];mode:'image'|'mask'|'colors';onPick:(code:number)=>void}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const c=ref.current;if(!c)return;c.width=160;c.height=Math.max(1,Math.ceil(codes.length/16))*10;const ctx=c.getContext('2d')!;ctx.fillStyle='#25303d';ctx.fillRect(0,0,c.width,c.height);
 for(let i=0;i<codes.length;i++)for(let y=0;y<8;y++){const a=symbolAddresses(screen,section,codes[i],y),bits=screen.vram[a.pattern]||0,colors=screen.vram[a.color]||0;for(let x=0;x<8;x++){const on=!!(bits&(128>>x)),index=mode==='colors'?(x<4?colors>>4:colors&15):on?colors>>4:colors&15;ctx.fillStyle=mode==='mask'?(on?'#ffffff':'#000000'):MSX1_PALETTE[index||(screen.registers[7]&15)];ctx.fillRect((i%16)*10+x,Math.floor(i/16)*10+y,1,1);}}},[screen,section,codes,mode]);
 return <canvas ref={ref} className="title-atlas" aria-label={mode==='image'?tr("Набор цветных символов"):mode==='mask'?tr("Набор масок символов"):tr("Цвета строк символов")} onClick={e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)*160/r.width,y=(e.clientY-r.top)*e.currentTarget.height/r.height,index=Math.floor(y/10)*16+Math.floor(x/10);if(index<codes.length)onPick(codes[index]);}}/>;
}
function SymbolBytes({screen,section,code}:{screen:TitleScreen;section:number;code:number}){const a=symbolAddresses(screen,section,code);return <div className="title-symbol-bytes"><strong>{tr("Символ $")}{hex(code,2)}{" "}{tr("· секция")}{" "}{section+1}</strong><span>{tr("Графика VRAM $")}{hex(a.pattern)}{" "}{tr("· цвет VRAM $")}{hex(a.color)}</span><table><thead><tr><th>{tr("Строка")}</th><th>{tr("Маска · HEX / биты")}</th><th>{tr("Цвет 1")}</th><th>{tr("Цвет 0")}</th></tr></thead><tbody>{Array.from({length:8},(_,y)=>{const a=symbolAddresses(screen,section,code,y),bits=screen.vram[a.pattern]||0,c=screen.vram[a.color]||0;return <tr key={y}><td>{y+1}</td><td><code>{hex(bits,2)} · {bits.toString(2).padStart(8,'0')}</code></td>{[c>>4,c&15].map((n,i)=><td key={i}><i style={{background:MSX1_PALETTE[n||(screen.registers[7]&15)]}}/>{hex(n,1)}</td>)}</tr>;})}</tbody></table><small>{tr("Код цвета 0 показывает фоновый цвет VDP. Адреса относятся к отображаемой раскладке.")}</small></div>;}
export function TitleSectionAtlas({screen}:{screen:TitleScreen}){const [section,setSection]=useState(0),[code,setCode]=useState(0),[open,setOpen]=useState(false);const codes=Array.from({length:256},(_,i)=>i);return <section className="title-section-atlas"><div className="title-section-choices">{[0,1,2].map(n=>{const a=symbolAddresses(screen,n,0);return <button key={n} aria-pressed={section===n&&open} onClick={()=>{setSection(n);setOpen(true);}}><b>{tr("Секция")}{" "}{n+1}{" "}{tr("· строки")}{" "}{n*8+1}–{n*8+8}</b><span>{tr("256 символов · $00–$FF")}</span><small>{tr("Графика $")}{hex(a.pattern)}{" "}{tr("· цвета $")}{hex(a.color)}</small></button>;})}<button onClick={()=>setOpen(!open)}>{open?tr("Скрыть набор"):tr("Показать набор")}</button></div>{open&&<><p>{tr("Один номер символа может выглядеть по-разному в трёх секциях. Нажмите символ, чтобы увидеть его байты. Регистры VDP могут совмещать банки; здесь показаны реальные адреса.")}</p><div className="title-atlas-row">{(['image','mask','colors'] as const).map((mode,i)=><figure key={mode}><figcaption>{tr(['Результат · 16 × 16 символов','Маски 1 / 0','Цвет 1 | цвет 0 по строкам'][i])}</figcaption><Atlas screen={screen} section={section} codes={codes} mode={mode} onPick={setCode}/></figure>)}<SymbolBytes screen={screen} section={section} code={code}/></div></>}</section>;}
function packetText(rom:readonly number[],source:TitleSource){if(!source.encoding.includes('RLE'))return '';let p=source.address+(source.name==='TXT_SOFWARE'?2:0),lines:string[]=[];while(p<=source.end){const address=p,command=rom[p++-0x4000],count=command&127;if(command===0){lines.push(`$${hex(address)}  00 → ${tr("конец")}`);break;}if(command===128){const dest=rom[p-0x4000]|rom[p+1-0x4000]<<8;p+=2;lines.push(`$${hex(address)}  80 → ${tr("адрес VRAM")} $${hex(dest&16383)}`);}else if(command&128){lines.push(`$${hex(address)}  ${hex(command,2)} → ${tr("{p0} буквальных байт",{p0:count})}: ${rom.slice(p-0x4000,p-0x4000+count).map(n=>hex(n,2)).join(' ')}`);p+=count;}else{lines.push(`$${hex(address)}  ${hex(command,2)} ${hex(rom[p++-0x4000],2)} → ${tr("повторить {p0} раз",{p0:count})}`);}}return lines.join('\n');}
export function TitleSourceCard({screen,source,rom}:{screen:TitleScreen;source:TitleSource;rom:readonly number[]}){const [code,setCode]=useState(0);const inSource=(address:number)=>{const o=screen.origins[address];return o>=source.address&&o<=source.end;};const codes=Array.from({length:256},(_,n)=>n).filter(n=>Array.from({length:8},(_,y)=>{const a=symbolAddresses(screen,0,n,y);return inSource(a.pattern)||inSource(a.color);}).some(Boolean)||screen.vram.slice(0x3800,0x3b00).some((tile,i)=>tile===n&&inSource(0x3800+i)));const selected=codes.includes(code)?code:codes[0]??0;const addresses=screen.origins.flatMap((origin,i)=>origin>=source.address&&origin<=source.end?[i]:[]);const ranges:number[][]=[];for(const address of addresses){const last=ranges.at(-1);if(last&&last[1]+1===address)last[1]=address;else ranges.push([address,address]);}
 return <details className="title-source"><summary><strong>{tr(source.role)}</strong><code>{source.name}</code><span>ROM +${hex(source.address-0x4000)} · {source.end-source.address+1}{" "}{tr("байт")}</span><small>{tr("Открыть байты, графику и цвета")}</small></summary><div className="title-source-expanded"><button onClick={()=>select(source.address-0x4000,'rom')}>{tr("Открыть ROM +$")}{hex(source.address-0x4000)}</button><p>{tr("Адрес в CPU: $")}{hex(source.address)}–${hex(source.end)}. {tr(source.encoding)}</p><h4>{tr("Так хранится в ROM · HEX")}</h4><pre>{Array.from({length:Math.ceil((source.end-source.address+1)/16)},(_,i)=>`+${hex(source.address-0x4000+i*16)}  ${rom.slice(source.address-0x4000+i*16,Math.min(source.end-0x4000+1,source.address-0x4000+(i+1)*16)).map(n=>hex(n,2)).join(' ')}`).join('\n')}</pre>{source.encoding.includes('RLE')&&<details><summary>{tr("Как распаковываются команды RLE")}</summary><pre>{packetText(rom,source)}</pre></details>}<h4>{tr("В восстановленном экране")}</h4><p>{ranges.length?tr("Байты этого блока используются в VRAM: {p0}",{p0:(ranges.map(([a,b])=>'$'+hex(a)+(a===b?'':'–$'+hex(b))).join(', '))}):tr("Блок содержит код сборки. Он задаёт размещение символов, а не хранит растровую картинку.")}</p>{codes.length>0&&<><p>{codes.length}{" "}{tr("связанных символов. Показан итоговый набор секции 1: маски и цвета могут поступать из разных блоков ROM.")}</p><div className="title-atlas-row">{(['image','mask','colors'] as const).map((mode,i)=><figure key={mode}><figcaption>{tr(['Картинка','Распакованные маски','Цвет 1 | цвет 0'][i])}</figcaption><Atlas screen={screen} section={0} codes={codes} mode={mode} onPick={setCode}/></figure>)}<SymbolBytes screen={screen} section={0} code={selected}/></div></>}</div></details>;
}
