import {t as tr} from '../i18n';
import {researchIndex} from '../backend/research';
import {watchAddress} from '../backend/watchActions';
import {useMemo,useState} from 'react';
import {command,select,store,updateProject,useDebugger} from '../state/debugger';
import {hex,parseAddress} from '../backend/disassemble';
import type {Watchpoint} from '../backend/types';
export function WritesPanel(){
 const s=useDebugger(),[space,setSpace]=useState<'cpu'|'vram'|'io'>('cpu'),[access,setAccess]=useState<'read'|'write'>('write'),[start,setStart]=useState(hex(s.selected)),[end,setEnd]=useState('');
 const watch=s.project?.watchpoints||[],event=s.snapshot?.hit?.access;const [selectedOnly,setSelectedOnly]=useState(false);const index=useMemo(()=>researchIndex(s.project?.labels||[]),[s.project?.labels]);const symbol=event&&event.space!=='io'?researchIndex(s.project?.labels||[],event.space).symbolAt(event.address):undefined;const writer=event&&event.pcKnown!==false?index.procedureAt(event.pc):undefined;
 function add(){const address=parseAddress(start),last=end?parseAddress(end):address,limit=space==='io'?256:space==='vram'?16384:65536;if(address===null||last===null||last<address||last>=limit){store.set({error:'Invalid watchpoint range'});return;}const point:Watchpoint={space,address,end:last,access:space==='vram'?'write':access,enabled:true};updateProject({watchpoints:[...watch,point]});}
 return <>
  {event&&<div className="watch-hit" role="status"><strong>{event.access==='write'?tr("Write"):tr("Read")} · {event.space.toUpperCase()} ${hex(event.address)} {symbol?.name}</strong><p>{event.before!==undefined?tr("{p0} → {p1}",{p0:(event.before),p1:(event.after??event.value)}):tr("Value {p0}",{p0:(event.value)})}{event.after!==undefined&&event.after!==event.value?tr(" · attempted {p0}",{p0:(event.value)}):''}</p><p>{event.pcKnown===false?tr("Instruction already in progress when monitoring started"):tr("{p0} ${p1}",{p0:(event.kind==='interrupt'?tr("Interrupt entry at PC"):tr("Instruction")),p1:(hex(event.pc))})}{writer?tr(" · {p0} +${p1}",{p0:(writer.name),p1:(hex(event.pc-writer.address))}):''}</p><button disabled={event.pcKnown===false} onClick={()=>select(event.pc)}>{event.kind==='interrupt'||event.access==='read'?tr("Go to instruction"):tr("Go to writer")}</button>{event.space!=='io'&&<button onClick={()=>select(event.address,event.space as 'cpu'|'vram')}>{tr("Go to accessed memory")}</button>}</div>}
  <div className="panel-tools"><button disabled={s.space==='rom'} onClick={()=>{if(s.space!=='rom'){setSpace(s.space);setStart(hex(s.selected));setEnd('');}}}>{tr("Use selected address")}</button><button disabled={s.space==='rom'} onClick={()=>watchAddress(s.selected,s.space)}>{tr("Watch selected writes")}</button></div>
  <div className="panel-tools"><label><input type="checkbox" checked={s.snapshot?.monitoring?.writes||false} onChange={e=>{void command('trackWrites',e.target.checked);}}/>{tr("Track writes / I/O")}</label></div>
  <form className="panel-tools" onSubmit={e=>{e.preventDefault();add();}}>
   <select aria-label={tr("Watchpoint space")} value={space} onChange={e=>{const n=e.target.value as typeof space;setSpace(n);setStart(n==='io'?'98':hex(s.selected%(n==='vram'?16384:65536)));setEnd('');if(n==='vram')setAccess('write');}}><option value="cpu">{tr("CPU — mapped memory")}</option><option value="vram">{tr("VRAM — video memory")}</option><option value="io">{tr("I/O port")}</option></select>
   <input aria-label={tr("Watchpoint start")} value={start} onChange={e=>setStart(e.target.value)} size={5} placeholder={tr("Start")}/><input aria-label={tr("Watchpoint end")} value={end} onChange={e=>setEnd(e.target.value)} size={5} placeholder={tr("End (optional)")}/>
   <select aria-label={tr("Access type")} value={access} onChange={e=>setAccess(e.target.value as typeof access)}><option value="write">{tr("Write")}</option><option value="read" disabled={space==='vram'}>{tr("Read")}</option></select><button>{tr("Add watchpoint")}</button>
  </form>
  <div className="watchpoint-list">{watch.map((w,i)=><div className="panel-tools" key={i}><input aria-label={tr("Enable watchpoint ")+i} type="checkbox" checked={w.enabled!==false} onChange={e=>updateProject({watchpoints:watch.map((p,j)=>j===i?{...p,enabled:e.target.checked}:p)})}/><span>{w.space} {hex(w.address)}{w.end!==undefined&&w.end!==w.address?'–'+hex(w.end):''} {tr(w.access)}</span><button onClick={()=>updateProject({watchpoints:watch.filter((_,j)=>j!==i)})}>{tr("Remove")}</button></div>)}</div>
  <p className="panel-message">{tr("Stop after access, including unchanged writes. CPU reads include instruction fetches. I/O matches the low port byte. Logs retain 500 entries.")}</p>
  <div className="panel-tools"><label><input type="checkbox" checked={selectedOnly} onChange={e=>setSelectedOnly(e.target.checked)}/>{tr("Only selected memory")}</label></div><div className="data-scroll"><table className="debug-table"><thead><tr><th>{tr("Address")}</th><th>{tr("Before → value")}</th><th>{tr("Writer PC")}</th></tr></thead><tbody>{s.snapshot?.lastWrites.filter(w=>!selectedOnly||w.space===s.space&&w.address===s.selected).slice().reverse().map((w,i)=><tr key={i}><td onClick={()=>select(w.address,w.space)}>{w.space} {hex(w.address)}</td><td>{hex(w.before,2)} → {hex(w.value,2)}</td><td onClick={()=>{if(w.pcKnown!==false)select(w.pc);}}>{w.pcKnown===false?tr("Unknown"):hex(w.pc)}<small className="label-detail">{w.pcKnown!==false&&index.procedureAt(w.pc)?.name}</small></td></tr>)}</tbody></table>
   <table className="debug-table"><thead><tr><th>{tr("I/O port")}</th><th>{tr("Access / value")}</th><th>{tr("Instruction")}</th></tr></thead><tbody>{s.snapshot?.ioTrace?.slice().reverse().map((e,i)=><tr key={i}><td>{hex(e.port)}</td><td>{tr(e.access)} {hex(e.value,2)}</td><td onClick={()=>{if(e.pcKnown!==false)select(e.pc);}}>{e.pcKnown===false?tr("Unknown"):hex(e.pc)}</td></tr>)}</tbody></table>
  </div>
 </>;
}
